$axure.loadCurrentPage({
  "url":"认证登陆.html",
  "generationDate":new Date(1404796804353.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a4d518b279214844b28d9aefde166a87",
    "type":"Axure:Page",
    "name":"认证登陆",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"88f2c26b92c14dadb79ccaaa55f9fbc3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":310,
              "height":550}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adf19b02dc4b4d09867bc3c482165714",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":310,
                  "height":550}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首界面/u0.jpg"}},
{
          "id":"20551ae24af74449bcf8dd25bd4f37f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE9EAEF},
            "location":{
              "x":20,
              "y":74},
            "size":{
              "width":309,
              "height":440},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"013a2c6713d84ff3bffaf9334af580cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE9EAEF},
                "location":{
                  "x":20,
                  "y":74},
                "size":{
                  "width":309,
                  "height":440},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首界面/u2.png"}},
{
          "id":"a24155e0b9f6436fb6d54967f87597df",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":48,
              "y":155},
            "size":{
              "width":254,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"09e722138a0d470aa3a0c77f13e77fcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "location":{
              "x":48,
              "y":209},
            "size":{
              "width":254,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"920f2207c95649e582965ddf9c8baf57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "location":{
                  "x":48,
                  "y":209},
                "size":{
                  "width":254,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证登陆/u5.png"}},
{
          "id":"3fb6978863c34cb68a5dbab76ff6690a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":48,
              "y":262},
            "size":{
              "width":254,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"4a47d05ba3594e9894e868f419f34e08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":48,
              "y":402},
            "size":{
              "width":254,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009999},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3b1856dcaf544b79c48041cef4353d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":48,
                  "y":402},
                "size":{
                  "width":254,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证登陆/u8.png"}},
{
          "id":"a489eb327e734a81ba209392167bd3f5",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":48,
              "y":377},
            "size":{
              "width":254,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"809c6658eab747249847c5c31882ed0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":48,
                  "y":377},
                "size":{
                  "width":254,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"864eeabcda8f409ab0aa0c630c481a08",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":93},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e2b821dd5cf4760a356c94a47d761ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":93},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证登陆/u12.png"}},
{
          "id":"43b4f07f5ab540ff8ba4040a333174b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":90,
              "y":99},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92e54cf2581a4d108c31b51c768fc73d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":99},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa2dac3973f043b383ece4df18957d5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":48,
              "y":490},
            "size":{
              "width":254,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52864f7347a0413cacd15902ec7c5051",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":48,
                  "y":490},
                "size":{
                  "width":254,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0517305ac34457daae851443475996b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":478},
            "size":{
              "width":309,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/认证登陆/u18_line.png"}},
{
          "id":"a724f7be3d0f4196889fc13dd3060997",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":168},
            "size":{
              "width":150,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/首界面/u21_start.png",
            "end~":"images/首界面/u21_end.png",
            "line~":"images/首界面/u24_line.png"}},
{
          "id":"571d9126bfb141bca322aac5d3c805f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":400,
              "y":165},
            "size":{
              "width":270,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18b7f058a5184b60a2aef59fc72018f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":400,
                  "y":165},
                "size":{
                  "width":270,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c0a70b3150e46758ca1d4e6c3f0b870",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":411},
            "size":{
              "width":150,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/首界面/u21_start.png",
            "end~":"images/首界面/u21_end.png",
            "line~":"images/首界面/u24_line.png"}},
{
          "id":"1cac49e6b0fa436a878886890681997f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":400,
              "y":408},
            "size":{
              "width":270,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56b7e7c05f42452990844e2191462912",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":400,
                  "y":408},
                "size":{
                  "width":270,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccf46a0ac36a4898ac2c3f599b5a824b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":263},
            "size":{
              "width":254,
              "height":39}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 手机版网址导航",
                      "target":{
                        "targetType":"page",
                        "url":"手机版网址导航.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5c53162c99ff41dd9434a540f006d8a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":0},
            "size":{
              "width":310,
              "height":550}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89eef321d8134615982bb192e194be12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":0},
                "size":{
                  "width":310,
                  "height":550}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首界面/u0.jpg"}},
{
          "id":"f237586ce1fa402ea768f1f73a6786c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE9EAEF},
            "location":{
              "x":680,
              "y":64},
            "size":{
              "width":309,
              "height":440},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"940bc505169f4afd866e9410f8e39020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE9EAEF},
                "location":{
                  "x":680,
                  "y":64},
                "size":{
                  "width":309,
                  "height":440},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首界面/u2.png"}},
{
          "id":"9dd8637a6df0496581a1906b0bb96f67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":708,
              "y":94},
            "size":{
              "width":254,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b571c190ef06447c90b3279617aa9b7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":708,
                  "y":94},
                "size":{
                  "width":254,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b183ff77491042a9afaeea97905c0edc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"0px",
            "location":{
              "x":708,
              "y":134},
            "size":{
              "width":254,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d1a65b0395b4957a561d8d00da5a3f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"0px",
                "location":{
                  "x":708,
                  "y":134},
                "size":{
                  "width":254,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0219a846589944afa7713c4d9092830e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":376},
            "size":{
              "width":420,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/认证登陆/u34_end.png",
            "line~":"images/认证登陆/u34_line.png"}},
{
          "id":"49d425e10b6c415cab9f7fba3ac7e8cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":366},
            "size":{
              "width":190,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"556c017f332945bf9039e46a67c127ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":366},
                "size":{
                  "width":190,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9f0eb6766294f329aa02c9c80b6667e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "location":{
              "x":126,
              "y":326},
            "size":{
              "width":82,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6835d4b49e9b461fb195af2a9102dc72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "location":{
                  "x":126,
                  "y":326},
                "size":{
                  "width":82,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证登陆/u37.png"}},
{
          "id":"2dbd973605414c2292a482dbe8a8e541",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":218,
              "y":326},
            "size":{
              "width":82,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6ef7adb3f8a4a4ca014a4d1acdde52f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":218,
                  "y":326},
                "size":{
                  "width":82,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证登陆/u39.png"}},
{
          "id":"1bddce4b06414f5f9278d6f333d87f6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":48,
              "y":330},
            "size":{
              "width":89,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee2e524652f94e9ca739d6497fc4aab0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":48,
                  "y":330},
                "size":{
                  "width":89,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"970e9dece4904b08805dd63f62c9eaa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":35,
              "y":307},
            "size":{
              "width":280,
              "height":60},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c36ac88a2dd64dd5a5950f1b704000eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":35,
                  "y":307},
                "size":{
                  "width":280,
                  "height":60},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证登陆/u43.png"}},
{
          "id":"125decaf5d954e45a584aff983e0be20",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":335},
            "size":{
              "width":80,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/认证登陆/u45_start.png",
            "end~":"images/认证登陆/u45_end.png",
            "line~":"images/认证登陆/u45_line.png"}},
{
          "id":"2597b382c51e44b091b2681dd023c4f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":400,
              "y":330},
            "size":{
              "width":280,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a3baff7ce4b480fb4010703682496b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":400,
                  "y":330},
                "size":{
                  "width":280,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "88f2c26b92c14dadb79ccaaa55f9fbc3":{
      "scriptId":"u0"},
    "adf19b02dc4b4d09867bc3c482165714":{
      "scriptId":"u1"},
    "20551ae24af74449bcf8dd25bd4f37f5":{
      "scriptId":"u2"},
    "013a2c6713d84ff3bffaf9334af580cf":{
      "scriptId":"u3"},
    "a24155e0b9f6436fb6d54967f87597df":{
      "scriptId":"u4"},
    "09e722138a0d470aa3a0c77f13e77fcb":{
      "scriptId":"u5"},
    "920f2207c95649e582965ddf9c8baf57":{
      "scriptId":"u6"},
    "3fb6978863c34cb68a5dbab76ff6690a":{
      "scriptId":"u7"},
    "4a47d05ba3594e9894e868f419f34e08":{
      "scriptId":"u8"},
    "c3b1856dcaf544b79c48041cef4353d2":{
      "scriptId":"u9"},
    "a489eb327e734a81ba209392167bd3f5":{
      "scriptId":"u10"},
    "809c6658eab747249847c5c31882ed0a":{
      "scriptId":"u11"},
    "864eeabcda8f409ab0aa0c630c481a08":{
      "scriptId":"u12"},
    "8e2b821dd5cf4760a356c94a47d761ee":{
      "scriptId":"u13"},
    "43b4f07f5ab540ff8ba4040a333174b3":{
      "scriptId":"u14"},
    "92e54cf2581a4d108c31b51c768fc73d":{
      "scriptId":"u15"},
    "fa2dac3973f043b383ece4df18957d5d":{
      "scriptId":"u16"},
    "52864f7347a0413cacd15902ec7c5051":{
      "scriptId":"u17"},
    "f0517305ac34457daae851443475996b":{
      "scriptId":"u18"},
    "a724f7be3d0f4196889fc13dd3060997":{
      "scriptId":"u19"},
    "571d9126bfb141bca322aac5d3c805f7":{
      "scriptId":"u20"},
    "18b7f058a5184b60a2aef59fc72018f6":{
      "scriptId":"u21"},
    "0c0a70b3150e46758ca1d4e6c3f0b870":{
      "scriptId":"u22"},
    "1cac49e6b0fa436a878886890681997f":{
      "scriptId":"u23"},
    "56b7e7c05f42452990844e2191462912":{
      "scriptId":"u24"},
    "ccf46a0ac36a4898ac2c3f599b5a824b":{
      "scriptId":"u25"},
    "5c53162c99ff41dd9434a540f006d8a7":{
      "scriptId":"u26"},
    "89eef321d8134615982bb192e194be12":{
      "scriptId":"u27"},
    "f237586ce1fa402ea768f1f73a6786c2":{
      "scriptId":"u28"},
    "940bc505169f4afd866e9410f8e39020":{
      "scriptId":"u29"},
    "9dd8637a6df0496581a1906b0bb96f67":{
      "scriptId":"u30"},
    "b571c190ef06447c90b3279617aa9b7a":{
      "scriptId":"u31"},
    "b183ff77491042a9afaeea97905c0edc":{
      "scriptId":"u32"},
    "9d1a65b0395b4957a561d8d00da5a3f5":{
      "scriptId":"u33"},
    "0219a846589944afa7713c4d9092830e":{
      "scriptId":"u34"},
    "49d425e10b6c415cab9f7fba3ac7e8cc":{
      "scriptId":"u35"},
    "556c017f332945bf9039e46a67c127ee":{
      "scriptId":"u36"},
    "f9f0eb6766294f329aa02c9c80b6667e":{
      "scriptId":"u37"},
    "6835d4b49e9b461fb195af2a9102dc72":{
      "scriptId":"u38"},
    "2dbd973605414c2292a482dbe8a8e541":{
      "scriptId":"u39"},
    "b6ef7adb3f8a4a4ca014a4d1acdde52f":{
      "scriptId":"u40"},
    "1bddce4b06414f5f9278d6f333d87f6f":{
      "scriptId":"u41"},
    "ee2e524652f94e9ca739d6497fc4aab0":{
      "scriptId":"u42"},
    "970e9dece4904b08805dd63f62c9eaa5":{
      "scriptId":"u43"},
    "c36ac88a2dd64dd5a5950f1b704000eb":{
      "scriptId":"u44"},
    "125decaf5d954e45a584aff983e0be20":{
      "scriptId":"u45"},
    "2597b382c51e44b091b2681dd023c4f5":{
      "scriptId":"u46"},
    "7a3baff7ce4b480fb4010703682496b1":{
      "scriptId":"u47"}}});