$axure.loadCurrentPage({
  "url":"手机端流程.html",
  "generationDate":new Date(1404796803646.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8bde77cb0edf44c1b13f159c9f571676",
    "type":"Axure:Page",
    "name":"手机端流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f93912f3b51a413abd0547d6dae80be6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":30},
            "size":{
              "width":130,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1087a60ac4dd422ab05967d008743296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":30},
                "size":{
                  "width":130,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端流程/u0.png"}},
{
          "id":"b1fc1150bf534ea0af5343711ea2040e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":395,
              "y":176},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a51344354abe4dec92df16c78ef2d061",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":395,
                  "y":176},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端流程/u2.png"},
          "referencePageUrl":"首界面.html"},
{
          "id":"97e3893972d34a81adc5bd200ce586bd",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":336},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41b222123486441892e5158e3a233515",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":336},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端流程/u2.png"}},
{
          "id":"e1e03fc7864846709114978af79def40",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":336},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ba52b6569ec44a786152a74ebeed67f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":336},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端流程/u2.png"}},
{
          "id":"f36a632386d6436d9f5b730bcf380ce3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":486},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a012c092a5984387962f1946ffb38d65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":486},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端流程/u2.png"}},
{
          "id":"02340f92e9d9444a9f44103bde782e06",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":655,
              "y":176},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b09ebe10c33f45dea955ad1c95479550",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":655,
                  "y":176},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端流程/u2.png"}},
{
          "id":"4f2c05ed90614aa49c90316a014bc6ef",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":655,
              "y":96},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65f840ee49a249a4a61b0b00b8afbe25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":655,
                  "y":96},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端流程/u2.png"}},
{
          "id":"030c722f46a243b8ad647a1c793e8d02",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":655,
              "y":256},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd641654360a4af785388f171e78357e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":655,
                  "y":256},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端流程/u2.png"}},
{
          "id":"c14e7f8cb764403a804b8a42d1092b26",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":445,
              "y":90},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc36d7f027b848bbb903d7e2a6456752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":445,
                  "y":90},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"c2d3e069e82c44229bfe91108631562c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":395,
              "y":206},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6289b0280a04e8c9c67665ba1c26a2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":395,
                  "y":206},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"b181e9dcd7c64f76adb5162cf122efad",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":495,
              "y":206},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"324a60aef2424c5093b9e99323d743ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":495,
                  "y":206},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"37297567921f4f99a149d549937c6b6d",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":495,
              "y":206},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4af2713848d4c2c9c09f18bf7056a41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":495,
                  "y":206},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"18032c39dfdc4e7d8de0ebce250c75b8",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":495,
              "y":206},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab8664108e4643a0aeb8cb36eae19d3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":495,
                  "y":206},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"7c0295ca42c54c80b78072af37ca915c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":396},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c629c36400694da3a72c849769463f32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":396},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"de63e2a4d6a9461f96509959f433cd09",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":396},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0054969ddc114ab192128f12e493b138",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":396},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"142a6c3b731a40b9a226a3701f46fb53",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":445,
              "y":236},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"126a7fe0d8a24db1820a0d1c0608b71c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":445,
                  "y":236},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"7e778cdb0a4247a6bda3bfbf1217f3d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":346},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7779b55b111e4f40bfabb708fd549658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":346},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e9389c0c06640f29da121e750b6bfc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":630,
              "y":346},
            "size":{
              "width":190,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"636edd1d316f42788ed09205e08ef3d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":630,
                  "y":346},
                "size":{
                  "width":190,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ef1cbb1b68744e7aabf86e9745cd1c7",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":370},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a15b3a5bffc74697ac2f62419a3630eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":370},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"d78532aa58264db6b3443906ed2bdf88",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":367},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"731552863e284d638caa8765b948c50c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":367},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"f6e4332fe6bb4370a96a42a250e20314",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":640,
              "y":85},
            "size":{
              "width":130,
              "height":240},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3687462e37ce4dcb8ab58862f5c1eb97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":640,
                  "y":85},
                "size":{
                  "width":130,
                  "height":240},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端流程/u40.png"}},
{
          "id":"b2a9c926b6bd427e941c06ac4bc954f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":830,
              "y":186},
            "size":{
              "width":160,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d1a881e8a5b48a786a79c2421bc8218",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":830,
                  "y":186},
                "size":{
                  "width":160,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"869d4844323a44748d4e247d56e77037",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":207},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4747d0a0cdd41f199f1c04a0d0bc6ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":207},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"7dc4635a67ea411699f05b1b760cba35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":496},
            "size":{
              "width":170,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f691c88c46b40eba138360599bf1872",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":496},
                "size":{
                  "width":170,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52773727b4684fc49a769d88890c994e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":520},
            "size":{
              "width":160,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/手机端流程/u48_end.png",
            "line~":"images/手机端流程/u48_line.png"}},
{
          "id":"71a1fab93c9d43e9bd3c97ae61084bde",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":600},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18ac39dec6594501b052475e1eaa2b43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":600},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端流程/u2.png"}},
{
          "id":"a5b1c9c69b764335b958b754cd4166d8",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":546},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"737c165e253d48fe9927f59d5b300c5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":546},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"c048d1cdc66344f29ac77f1c875d2ae0",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":630},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1413db1c92974b95bead68b84dd41b0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":630},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"81ad873287684a5e889b64c5ad7bb6de",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":700},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9390f47fb474bb993d3f8cd9b85a960",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":700},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端流程/u2.png"}},
{
          "id":"873ff2f5ec2944a78e3b2f8739eebd41",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":660},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee790981f68846af8742d22eda48463e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":660},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"e23e7d2118a842f8b8387bc97cbdd028",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":600},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b829174c99d4a5c89fdb646c790207c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":600},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端流程/u2.png"}},
{
          "id":"bdb029a45c9f4102982a9a25fee2c6a6",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":546},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"389fccba52f14f899a651cb4bedbd455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":546},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "f93912f3b51a413abd0547d6dae80be6":{
      "scriptId":"u0"},
    "1087a60ac4dd422ab05967d008743296":{
      "scriptId":"u1"},
    "b1fc1150bf534ea0af5343711ea2040e":{
      "scriptId":"u2"},
    "a51344354abe4dec92df16c78ef2d061":{
      "scriptId":"u3"},
    "97e3893972d34a81adc5bd200ce586bd":{
      "scriptId":"u4"},
    "41b222123486441892e5158e3a233515":{
      "scriptId":"u5"},
    "e1e03fc7864846709114978af79def40":{
      "scriptId":"u6"},
    "5ba52b6569ec44a786152a74ebeed67f":{
      "scriptId":"u7"},
    "f36a632386d6436d9f5b730bcf380ce3":{
      "scriptId":"u8"},
    "a012c092a5984387962f1946ffb38d65":{
      "scriptId":"u9"},
    "02340f92e9d9444a9f44103bde782e06":{
      "scriptId":"u10"},
    "b09ebe10c33f45dea955ad1c95479550":{
      "scriptId":"u11"},
    "4f2c05ed90614aa49c90316a014bc6ef":{
      "scriptId":"u12"},
    "65f840ee49a249a4a61b0b00b8afbe25":{
      "scriptId":"u13"},
    "030c722f46a243b8ad647a1c793e8d02":{
      "scriptId":"u14"},
    "dd641654360a4af785388f171e78357e":{
      "scriptId":"u15"},
    "c14e7f8cb764403a804b8a42d1092b26":{
      "scriptId":"u16"},
    "fc36d7f027b848bbb903d7e2a6456752":{
      "scriptId":"u17"},
    "c2d3e069e82c44229bfe91108631562c":{
      "scriptId":"u18"},
    "f6289b0280a04e8c9c67665ba1c26a2f":{
      "scriptId":"u19"},
    "b181e9dcd7c64f76adb5162cf122efad":{
      "scriptId":"u20"},
    "324a60aef2424c5093b9e99323d743ab":{
      "scriptId":"u21"},
    "37297567921f4f99a149d549937c6b6d":{
      "scriptId":"u22"},
    "a4af2713848d4c2c9c09f18bf7056a41":{
      "scriptId":"u23"},
    "18032c39dfdc4e7d8de0ebce250c75b8":{
      "scriptId":"u24"},
    "ab8664108e4643a0aeb8cb36eae19d3c":{
      "scriptId":"u25"},
    "7c0295ca42c54c80b78072af37ca915c":{
      "scriptId":"u26"},
    "c629c36400694da3a72c849769463f32":{
      "scriptId":"u27"},
    "de63e2a4d6a9461f96509959f433cd09":{
      "scriptId":"u28"},
    "0054969ddc114ab192128f12e493b138":{
      "scriptId":"u29"},
    "142a6c3b731a40b9a226a3701f46fb53":{
      "scriptId":"u30"},
    "126a7fe0d8a24db1820a0d1c0608b71c":{
      "scriptId":"u31"},
    "7e778cdb0a4247a6bda3bfbf1217f3d1":{
      "scriptId":"u32"},
    "7779b55b111e4f40bfabb708fd549658":{
      "scriptId":"u33"},
    "1e9389c0c06640f29da121e750b6bfc4":{
      "scriptId":"u34"},
    "636edd1d316f42788ed09205e08ef3d5":{
      "scriptId":"u35"},
    "8ef1cbb1b68744e7aabf86e9745cd1c7":{
      "scriptId":"u36"},
    "a15b3a5bffc74697ac2f62419a3630eb":{
      "scriptId":"u37"},
    "d78532aa58264db6b3443906ed2bdf88":{
      "scriptId":"u38"},
    "731552863e284d638caa8765b948c50c":{
      "scriptId":"u39"},
    "f6e4332fe6bb4370a96a42a250e20314":{
      "scriptId":"u40"},
    "3687462e37ce4dcb8ab58862f5c1eb97":{
      "scriptId":"u41"},
    "b2a9c926b6bd427e941c06ac4bc954f2":{
      "scriptId":"u42"},
    "3d1a881e8a5b48a786a79c2421bc8218":{
      "scriptId":"u43"},
    "869d4844323a44748d4e247d56e77037":{
      "scriptId":"u44"},
    "f4747d0a0cdd41f199f1c04a0d0bc6ea":{
      "scriptId":"u45"},
    "7dc4635a67ea411699f05b1b760cba35":{
      "scriptId":"u46"},
    "7f691c88c46b40eba138360599bf1872":{
      "scriptId":"u47"},
    "52773727b4684fc49a769d88890c994e":{
      "scriptId":"u48"},
    "71a1fab93c9d43e9bd3c97ae61084bde":{
      "scriptId":"u49"},
    "18ac39dec6594501b052475e1eaa2b43":{
      "scriptId":"u50"},
    "a5b1c9c69b764335b958b754cd4166d8":{
      "scriptId":"u51"},
    "737c165e253d48fe9927f59d5b300c5e":{
      "scriptId":"u52"},
    "c048d1cdc66344f29ac77f1c875d2ae0":{
      "scriptId":"u53"},
    "1413db1c92974b95bead68b84dd41b0d":{
      "scriptId":"u54"},
    "81ad873287684a5e889b64c5ad7bb6de":{
      "scriptId":"u55"},
    "c9390f47fb474bb993d3f8cd9b85a960":{
      "scriptId":"u56"},
    "873ff2f5ec2944a78e3b2f8739eebd41":{
      "scriptId":"u57"},
    "ee790981f68846af8742d22eda48463e":{
      "scriptId":"u58"},
    "e23e7d2118a842f8b8387bc97cbdd028":{
      "scriptId":"u59"},
    "5b829174c99d4a5c89fdb646c790207c":{
      "scriptId":"u60"},
    "bdb029a45c9f4102982a9a25fee2c6a6":{
      "scriptId":"u61"},
    "389fccba52f14f899a651cb4bedbd455":{
      "scriptId":"u62"}}});