$axure.loadCurrentPage({
  "url":"500.html",
  "generationDate":new Date(1404457234937.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"22aa8fc242234b90aba1138162e01325",
    "type":"Axure:Page",
    "name":"500",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4db091c7ead84d3ead8d4e4379e6b3d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":15},
            "size":{
              "width":320,
              "height":480},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df09309d5dad40efaf80c036b7e34282",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":15},
                "size":{
                  "width":320,
                  "height":480},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u28.png"}},
{
          "id":"8e7a0fc7f1984099a3dfc8148419d673",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":12,
              "y":15},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f46a20e88804019888b8528d073d05e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":12,
                  "y":15},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u8.png"}},
{
          "id":"b614cef2db1148d3b9fb024c05488f30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":42,
              "y":21},
            "size":{
              "width":29,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caef96e4db6e4d09a8ef2cfd42255059",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":42,
                  "y":21},
                "size":{
                  "width":29,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ebb0fe36c0a40ba8f6cf5190c630fbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":82,
              "y":27},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de90fbc05d5e4879bc0cc02ed04b280c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":27},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdff71e8498c484188e00ce59530826d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":118,
              "y":160},
            "size":{
              "width":145,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aca49ca3e9d43aba994de0f3afa1668",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":118,
                  "y":160},
                "size":{
                  "width":145,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b70744fc47a4675ad3b41a89eaac332",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":108,
              "y":186},
            "size":{
              "width":190,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca0327a7ace04e359f1d7741c52abce7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":186},
                "size":{
                  "width":190,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e901dbca6ec44159b3fe6f8c7175b763",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":66,
              "y":160},
            "size":{
              "width":32,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bc4c31811164ac0a80a1f48054d38a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":66,
                  "y":160},
                "size":{
                  "width":32,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4453cda540c949539927fbcc90b179d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":118,
              "y":235},
            "size":{
              "width":102,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6eccf4475ba4b61aa7fa21c723f16fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":118,
                  "y":235},
                "size":{
                  "width":102,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/500/u14.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4db091c7ead84d3ead8d4e4379e6b3d5":{
      "scriptId":"u0"},
    "df09309d5dad40efaf80c036b7e34282":{
      "scriptId":"u1"},
    "8e7a0fc7f1984099a3dfc8148419d673":{
      "scriptId":"u2"},
    "6f46a20e88804019888b8528d073d05e":{
      "scriptId":"u3"},
    "b614cef2db1148d3b9fb024c05488f30":{
      "scriptId":"u4"},
    "caef96e4db6e4d09a8ef2cfd42255059":{
      "scriptId":"u5"},
    "1ebb0fe36c0a40ba8f6cf5190c630fbd":{
      "scriptId":"u6"},
    "de90fbc05d5e4879bc0cc02ed04b280c":{
      "scriptId":"u7"},
    "fdff71e8498c484188e00ce59530826d":{
      "scriptId":"u8"},
    "0aca49ca3e9d43aba994de0f3afa1668":{
      "scriptId":"u9"},
    "0b70744fc47a4675ad3b41a89eaac332":{
      "scriptId":"u10"},
    "ca0327a7ace04e359f1d7741c52abce7":{
      "scriptId":"u11"},
    "e901dbca6ec44159b3fe6f8c7175b763":{
      "scriptId":"u12"},
    "6bc4c31811164ac0a80a1f48054d38a4":{
      "scriptId":"u13"},
    "4453cda540c949539927fbcc90b179d5":{
      "scriptId":"u14"},
    "b6eccf4475ba4b61aa7fa21c723f16fc":{
      "scriptId":"u15"}}});