$axure.loadCurrentPage({
  "url":"统计分析.html",
  "generationDate":new Date(1400556937298.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"baa01d7a3f074f4fb402d4af2f9e6d7d",
    "type":"Axure:Page",
    "name":"统计分析",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"38f4c4bbe87d40ea8270d259156308ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":20,
              "y":59},
            "size":{
              "width":145,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7db1d41eb9c84c8195837155761ad68b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":20,
                  "y":59},
                "size":{
                  "width":145,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdbdddc63b524acbae55314b24c7271f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":459,
              "y":550},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"962ac85591a44772a46244571e7015d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":139,
              "y":551},
            "size":{
              "width":70,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4866fff610c3474caa33d0c219dd1ab6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":139,
                  "y":551},
                "size":{
                  "width":70,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a35cbb0b2db407fba874453d234d4bc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":550},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2e82d89b0c084993a969508e186a0464",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":550},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4eab9e8896a94509b933bdfb974ed6a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":551},
            "size":{
              "width":40,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f45bc4bafc374a8ba0a15e6562288063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":551},
                "size":{
                  "width":40,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fac8bb3699f4b2ca6b8587caf1d1120",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":20,
              "y":550},
            "size":{
              "width":109,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd0317cacefe492f9753a2b168807da8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":20,
                  "y":550},
                "size":{
                  "width":109,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"561ab850f0414622ac41f80fa4daa31d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":585},
            "size":{
              "width":600,
              "height":300},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef9c443ef8224a48bdf30516e2c0d3d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":585},
                "size":{
                  "width":600,
                  "height":300},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计分析/u11.png"}},
{
          "id":"67f874745b0d4b16a30f8628c3499d2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"10",
            "location":{
              "x":20,
              "y":90},
            "size":{
              "width":225,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70f885bf197c42f79baf2815c38e0c8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"10",
                "location":{
                  "x":20,
                  "y":90},
                "size":{
                  "width":225,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计分析/u13.png"}},
{
          "id":"ca9c29d60a15468ab244bd6cfdadf940",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"10",
            "location":{
              "x":245,
              "y":90},
            "size":{
              "width":225,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f9cf36c2d1e41b38bcb5137dd450f0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"10",
                "location":{
                  "x":245,
                  "y":90},
                "size":{
                  "width":225,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计分析/u13.png"}},
{
          "id":"b26a8c1d84554bcbb701a3ef1201bf57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"10",
            "location":{
              "x":695,
              "y":90},
            "size":{
              "width":225,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be6f707d10184548b9fba170d0c6fcc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"10",
                "location":{
                  "x":695,
                  "y":90},
                "size":{
                  "width":225,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计分析/u13.png"}},
{
          "id":"0fb66bb5d95444149f66ac6c72dd5c42",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":20,
              "y":300},
            "size":{
              "width":145,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcb56b084d424b59a08783467c9963bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":20,
                  "y":300},
                "size":{
                  "width":145,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f9da9eed19545ccad80339c870e2afb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"10",
            "location":{
              "x":20,
              "y":330},
            "size":{
              "width":300,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"824df223a773444c82d3233ef9229b4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"10",
                "location":{
                  "x":20,
                  "y":330},
                "size":{
                  "width":300,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计分析/u21.png"}},
{
          "id":"261bb1886b004e89b8957f26b5104c65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"10",
            "location":{
              "x":320,
              "y":330},
            "size":{
              "width":300,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6d3b0b44824430e84558710f562b7b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"10",
                "location":{
                  "x":320,
                  "y":330},
                "size":{
                  "width":300,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计分析/u21.png"}},
{
          "id":"a9fd2c4641ab42a9a05b2191fbd9fbf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"10",
            "location":{
              "x":620,
              "y":330},
            "size":{
              "width":300,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cd9a423c6484b26a4ea50a1d81a7332",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"10",
                "location":{
                  "x":620,
                  "y":330},
                "size":{
                  "width":300,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计分析/u21.png"}},
{
          "id":"c3558baece86412a976a281e64d5627e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":84},
            "size":{
              "width":900,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/统计分析/u27_line.png"}},
{
          "id":"62c9188161c544dab893d2d8f2243a6e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":325},
            "size":{
              "width":900,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/统计分析/u27_line.png"}},
{
          "id":"1a660f21df0143a296da2399e48f59f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":750,
              "y":553},
            "size":{
              "width":170,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff4c830e2a0843e99505ddd732608912",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":750,
                  "y":553},
                "size":{
                  "width":170,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45337acda8a24f44bad458ab119d5b51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"10",
            "location":{
              "x":470,
              "y":90},
            "size":{
              "width":225,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6810c48f937a46ab90b226c08620cb60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"10",
                "location":{
                  "x":470,
                  "y":90},
                "size":{
                  "width":225,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计分析/u13.png"}},
{
          "id":"3f63cf3171dc4906a59d7a4f78257587",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":459,
              "y":900},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"db595d1368534e84b017bcb08e395a95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":139,
              "y":901},
            "size":{
              "width":70,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b5c741b62de48efaa5c07535ffec7b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":139,
                  "y":901},
                "size":{
                  "width":70,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e67e63c084c7466caa17f196a2578494",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":900},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8c4d5fd8dde0441f93afe7efd39c8932",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":900},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ee54b60e5f304137b680e0ad0082a730",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":901},
            "size":{
              "width":40,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ea90c82761040938a91e6419fb1e5ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":901},
                "size":{
                  "width":40,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8146c10eb63d473dab6954a9dbf44d65",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":20,
              "y":900},
            "size":{
              "width":109,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67222645c26a48f48a1263308d00dca2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":20,
                  "y":900},
                "size":{
                  "width":109,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcf9f92908ae4102b3c046fed313055b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":935},
            "size":{
              "width":600,
              "height":300},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1572e1e99f0f4ff48b7db86c3e711588",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":935},
                "size":{
                  "width":600,
                  "height":300},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计分析/u11.png"}},
{
          "id":"ec0a6334a67b49fabded61e122283695",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":580},
            "size":{
              "width":900,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/统计分析/u27_line.png"}},
{
          "id":"1635538be8d34255aa5589dbee2e05b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"10",
            "location":{
              "x":20,
              "y":935},
            "size":{
              "width":300,
              "height":300},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"866f560596aa4f30aef2c44ff50a1b43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"10",
                "location":{
                  "x":20,
                  "y":935},
                "size":{
                  "width":300,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计分析/u45.png"}},
{
          "id":"d725de4a0c224613b0f6a54f7b6f6bf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":102,
              "y":174},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8607f279bacd4ccc89174e54b5f9ec54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":102,
                  "y":174},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63e18a2f4937478cafa6d10085e098a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":328,
              "y":174},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b63fff95c98d41e5a04513b04e6d1797",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":328,
                  "y":174},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb5d070f953b44908a16700853b43cd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":552,
              "y":174},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7f8b85509574e9586541a60d6b993cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":552,
                  "y":174},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"697209690877438fb4c4ce0f83982143",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":778,
              "y":174},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c41cc55842764531a958927cc06adadc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":778,
                  "y":174},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"318184b270df4876827aaadc665a6fdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":330,
              "y":947},
            "size":{
              "width":100,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5950f18621de4ebbbd3f23cda9be8a48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":330,
                  "y":947},
                "size":{
                  "width":100,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8327c444a4c741c6b6ce996ea37bafa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":754,
              "y":420},
            "size":{
              "width":108,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1cb25758d0b4aaa833bd15d8db4943f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":754,
                  "y":420},
                "size":{
                  "width":108,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecf5b7019aae4c17a4b0b87eeacf1074",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":420},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bd0e310289941048dc6d87f24c2cce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":420},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6eea80f261414e3089a1981ae01821a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":420},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8a4eb9b973c4b938672c83f7f335834",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":420},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70ed215da5bb4abbb72e2d3677f6d4d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"10",
            "location":{
              "x":20,
              "y":585},
            "size":{
              "width":300,
              "height":300},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f0317073fa94d6c8c63a74fc1945e17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"10",
                "location":{
                  "x":20,
                  "y":585},
                "size":{
                  "width":300,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计分析/u45.png"}},
{
          "id":"b9a05691f3b249e491c81a9f3d3c4d83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":330,
              "y":590},
            "size":{
              "width":130,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6aad41571564d0fb5642cb19b2274e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":330,
                  "y":590},
                "size":{
                  "width":130,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff61eb6589064bfca1e8dea595ecd8df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":900,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c047f4ce32bd4f6a873800617a00c99e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":900,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "38f4c4bbe87d40ea8270d259156308ef":{
      "scriptId":"u0"},
    "7db1d41eb9c84c8195837155761ad68b":{
      "scriptId":"u1"},
    "fdbdddc63b524acbae55314b24c7271f":{
      "scriptId":"u2"},
    "962ac85591a44772a46244571e7015d4":{
      "scriptId":"u3"},
    "4866fff610c3474caa33d0c219dd1ab6":{
      "scriptId":"u4"},
    "7a35cbb0b2db407fba874453d234d4bc":{
      "scriptId":"u5"},
    "2e82d89b0c084993a969508e186a0464":{
      "scriptId":"u6"},
    "4eab9e8896a94509b933bdfb974ed6a2":{
      "scriptId":"u7"},
    "f45bc4bafc374a8ba0a15e6562288063":{
      "scriptId":"u8"},
    "1fac8bb3699f4b2ca6b8587caf1d1120":{
      "scriptId":"u9"},
    "dd0317cacefe492f9753a2b168807da8":{
      "scriptId":"u10"},
    "561ab850f0414622ac41f80fa4daa31d":{
      "scriptId":"u11"},
    "ef9c443ef8224a48bdf30516e2c0d3d3":{
      "scriptId":"u12"},
    "67f874745b0d4b16a30f8628c3499d2d":{
      "scriptId":"u13"},
    "70f885bf197c42f79baf2815c38e0c8b":{
      "scriptId":"u14"},
    "ca9c29d60a15468ab244bd6cfdadf940":{
      "scriptId":"u15"},
    "5f9cf36c2d1e41b38bcb5137dd450f0c":{
      "scriptId":"u16"},
    "b26a8c1d84554bcbb701a3ef1201bf57":{
      "scriptId":"u17"},
    "be6f707d10184548b9fba170d0c6fcc6":{
      "scriptId":"u18"},
    "0fb66bb5d95444149f66ac6c72dd5c42":{
      "scriptId":"u19"},
    "dcb56b084d424b59a08783467c9963bf":{
      "scriptId":"u20"},
    "2f9da9eed19545ccad80339c870e2afb":{
      "scriptId":"u21"},
    "824df223a773444c82d3233ef9229b4a":{
      "scriptId":"u22"},
    "261bb1886b004e89b8957f26b5104c65":{
      "scriptId":"u23"},
    "e6d3b0b44824430e84558710f562b7b8":{
      "scriptId":"u24"},
    "a9fd2c4641ab42a9a05b2191fbd9fbf4":{
      "scriptId":"u25"},
    "1cd9a423c6484b26a4ea50a1d81a7332":{
      "scriptId":"u26"},
    "c3558baece86412a976a281e64d5627e":{
      "scriptId":"u27"},
    "62c9188161c544dab893d2d8f2243a6e":{
      "scriptId":"u28"},
    "1a660f21df0143a296da2399e48f59f0":{
      "scriptId":"u29"},
    "ff4c830e2a0843e99505ddd732608912":{
      "scriptId":"u30"},
    "45337acda8a24f44bad458ab119d5b51":{
      "scriptId":"u31"},
    "6810c48f937a46ab90b226c08620cb60":{
      "scriptId":"u32"},
    "3f63cf3171dc4906a59d7a4f78257587":{
      "scriptId":"u33"},
    "db595d1368534e84b017bcb08e395a95":{
      "scriptId":"u34"},
    "0b5c741b62de48efaa5c07535ffec7b1":{
      "scriptId":"u35"},
    "e67e63c084c7466caa17f196a2578494":{
      "scriptId":"u36"},
    "8c4d5fd8dde0441f93afe7efd39c8932":{
      "scriptId":"u37"},
    "ee54b60e5f304137b680e0ad0082a730":{
      "scriptId":"u38"},
    "0ea90c82761040938a91e6419fb1e5ca":{
      "scriptId":"u39"},
    "8146c10eb63d473dab6954a9dbf44d65":{
      "scriptId":"u40"},
    "67222645c26a48f48a1263308d00dca2":{
      "scriptId":"u41"},
    "dcf9f92908ae4102b3c046fed313055b":{
      "scriptId":"u42"},
    "1572e1e99f0f4ff48b7db86c3e711588":{
      "scriptId":"u43"},
    "ec0a6334a67b49fabded61e122283695":{
      "scriptId":"u44"},
    "1635538be8d34255aa5589dbee2e05b8":{
      "scriptId":"u45"},
    "866f560596aa4f30aef2c44ff50a1b43":{
      "scriptId":"u46"},
    "d725de4a0c224613b0f6a54f7b6f6bf8":{
      "scriptId":"u47"},
    "8607f279bacd4ccc89174e54b5f9ec54":{
      "scriptId":"u48"},
    "63e18a2f4937478cafa6d10085e098a6":{
      "scriptId":"u49"},
    "b63fff95c98d41e5a04513b04e6d1797":{
      "scriptId":"u50"},
    "bb5d070f953b44908a16700853b43cd2":{
      "scriptId":"u51"},
    "a7f8b85509574e9586541a60d6b993cd":{
      "scriptId":"u52"},
    "697209690877438fb4c4ce0f83982143":{
      "scriptId":"u53"},
    "c41cc55842764531a958927cc06adadc":{
      "scriptId":"u54"},
    "318184b270df4876827aaadc665a6fdf":{
      "scriptId":"u55"},
    "5950f18621de4ebbbd3f23cda9be8a48":{
      "scriptId":"u56"},
    "8327c444a4c741c6b6ce996ea37bafa9":{
      "scriptId":"u57"},
    "d1cb25758d0b4aaa833bd15d8db4943f":{
      "scriptId":"u58"},
    "ecf5b7019aae4c17a4b0b87eeacf1074":{
      "scriptId":"u59"},
    "5bd0e310289941048dc6d87f24c2cce3":{
      "scriptId":"u60"},
    "6eea80f261414e3089a1981ae01821a9":{
      "scriptId":"u61"},
    "a8a4eb9b973c4b938672c83f7f335834":{
      "scriptId":"u62"},
    "70ed215da5bb4abbb72e2d3677f6d4d6":{
      "scriptId":"u63"},
    "7f0317073fa94d6c8c63a74fc1945e17":{
      "scriptId":"u64"},
    "b9a05691f3b249e491c81a9f3d3c4d83":{
      "scriptId":"u65"},
    "c6aad41571564d0fb5642cb19b2274e4":{
      "scriptId":"u66"},
    "ff61eb6589064bfca1e8dea595ecd8df":{
      "scriptId":"u67"},
    "c047f4ce32bd4f6a873800617a00c99e":{
      "scriptId":"u68"}}});