$axure.loadCurrentPage({
  "url":"关注引导.html",
  "generationDate":new Date(1404457227573.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9a8c08084de84e76b0a2fcbf129096d0",
    "type":"Axure:Page",
    "name":"关注引导",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3db2e08d4d664185b62603b0364a4b04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":470,
              "y":10},
            "size":{
              "width":320,
              "height":480},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ea6ff72387a4d4d8bd40d7b77f8d61f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":470,
                  "y":10},
                "size":{
                  "width":320,
                  "height":480},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u0.png"}},
{
          "id":"3c03cff608174c6abcbb2feb15c8d8b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":517,
              "y":450},
            "size":{
              "width":273,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64fbfa92be714d6e803006ef82720b67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":517,
                  "y":450},
                "size":{
                  "width":273,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u43.png"}},
{
          "id":"8980ed288cd642fda86dff82235d1996",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":470,
              "y":10},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce39d96f522e42af94c80eb1398f1d6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":470,
                  "y":10},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u4.png"}},
{
          "id":"770815513b3a4fb29fab3af3aeb87477",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":500,
              "y":16},
            "size":{
              "width":29,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47bba40e3acb4db699c84bfc288624b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":500,
                  "y":16},
                "size":{
                  "width":29,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u6.png"}},
{
          "id":"2a16324385254021b9cb5be9c434f02b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":79,
              "y":22},
            "size":{
              "width":200,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b314b9bf0c847fd8733f46cc380170b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":79,
                  "y":22},
                "size":{
                  "width":200,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u8.png"}},
{
          "id":"b20c17bdba0744b69a0d8651b8dbc4ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":470,
              "y":450},
            "size":{
              "width":48,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69d1543619f847cb818efdafa0d9e258",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":450},
                "size":{
                  "width":48,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u14.png"}},
{
          "id":"91332b4555264301983a78e051f3f39c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":759,
              "y":455},
            "size":{
              "width":25,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e3e56d2b9ff4820943a2fadc7aa7902",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":759,
                  "y":455},
                "size":{
                  "width":25,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5be677929b4644b58b282279c3bff932",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":529,
              "y":460},
            "size":{
              "width":17,
              "height":20},
            "rotation":"45",
            "textRotation":"45"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ae6c2aa4da9402aaa6efafb8a29225f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":529,
                  "y":460},
                "size":{
                  "width":17,
                  "height":20},
                "rotation":"45",
                "textRotation":"45"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12396c04d2b0490a9681900058f27743",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":548,
              "y":455},
            "size":{
              "width":207,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44df0e5060f2471f8a27606ea41886a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":548,
                  "y":455},
                "size":{
                  "width":207,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u51.png"}},
{
          "id":"4809aef025164591ae7a0abaa9aaa6b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":732,
              "y":460},
            "size":{
              "width":18,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57598f8211234c3591f1c08ea67c670d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":732,
                  "y":460},
                "size":{
                  "width":18,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab9a519467f541fd935d76e4047828eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":479,
              "y":280},
            "size":{
              "width":40,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcb1c1744e89467c822c2410bea4888c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":479,
                  "y":280},
                "size":{
                  "width":40,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u20.png"}},
{
          "id":"049d72766ae44f648557f649dd02978f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":580,
              "y":60},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2bb8b5794fb47159a22504cd3711d00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":580,
                  "y":60},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u57.png"}},
{
          "id":"3e6ebb72c6e846b3be63d1ef4a8adadd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "horizontalAlignment":"left",
            "paddingTop":"8",
            "paddingBottom":"0",
            "location":{
              "x":532,
              "y":280},
            "size":{
              "width":248,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c5b4e03b90a4b5699056296b718ee88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "horizontalAlignment":"left",
                "paddingTop":"8",
                "paddingBottom":"0",
                "location":{
                  "x":532,
                  "y":280},
                "size":{
                  "width":248,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u24.png"}},
{
          "id":"87673854212f4f319bf3aa1cb07b8ba8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":524,
              "y":290},
            "size":{
              "width":10,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":-1,
              "offsetY":0,
              "blurRadius":0,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37041448a11e467b9dc3c247974ee89d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":524,
                  "y":290},
                "size":{
                  "width":10,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":-1,
                  "offsetY":0,
                  "blurRadius":0,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u61.png"}},
{
          "id":"262beb9f63a3435d93f1eeec708c9774",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":480},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0af2b4cfd1f44ff83ac47e6305ae3cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":480},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u28.png"}},
{
          "id":"c0a0e071c6c543daa829986c179521db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e721890524d4d55a17e246a7ce3e1c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u4.png"}},
{
          "id":"8758e9542b9b44c29f21d516d597b1cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":40,
              "y":16},
            "size":{
              "width":29,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"950f80ef728b47fbaf60d5aecf52e645",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":40,
                  "y":16},
                "size":{
                  "width":29,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u6.png"}},
{
          "id":"92ca3d1d086148a1a3064baeac92ce63",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":79,
              "y":22},
            "size":{
              "width":200,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80a88cae263245c9bd531fb6008ff2fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":79,
                  "y":22},
                "size":{
                  "width":200,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u34.png"}},
{
          "id":"4fe5290dd39847d0acc13cf64c857909",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":76},
            "size":{
              "width":74,
              "height":74},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0ce07c1ce5443deb30bcad9ad228538",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":76},
                "size":{
                  "width":74,
                  "height":74},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u36.png"}},
{
          "id":"18a5af671a9d47768f3536e6de8bb482",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":110,
              "y":84},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"967696e7cfaa4e2986bfe8dffa196d8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":110,
                  "y":84},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4bdcb8f8b3f43edbd69a0f44574e790",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":110},
            "size":{
              "width":183,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"659a29c3dd2947ea8f0bff5a498af06e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":110},
                "size":{
                  "width":183,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"699a3cd735764fc99c73770a9b3db7f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":26,
              "y":180},
            "size":{
              "width":75,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e9f8b278f704667a0c082569e0a8da5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":26,
                  "y":180},
                "size":{
                  "width":75,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u42.png"}},
{
          "id":"5da41700ee764080b11cd222dedc683b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":26,
              "y":226},
            "size":{
              "width":75,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fca6e88ff6f14f2ebcff31fb92067fb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":26,
                  "y":226},
                "size":{
                  "width":75,
                  "height":54},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u44.png"}},
{
          "id":"d390777066974b988ed7f04b776973df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":111,
              "y":180},
            "size":{
              "width":209,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4da8871ddfc94c8a843617bbb865c0ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":111,
                  "y":180},
                "size":{
                  "width":209,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u46.png"}},
{
          "id":"e9abfcdcb4a44a09b3f9c0f1ca23a002",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":111,
              "y":226},
            "size":{
              "width":209,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a44b0e45244e0ab3ed7158fd5af8a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":111,
                  "y":226},
                "size":{
                  "width":209,
                  "height":54},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u48.png"}},
{
          "id":"f515b65a579d404885298b591506d265",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC00},
            "location":{
              "x":26,
              "y":296},
            "size":{
              "width":284,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea18be11f21b4a6b8e208f1efd395e2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC00},
                "location":{
                  "x":26,
                  "y":296},
                "size":{
                  "width":284,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u50.png"}},
{
          "id":"75982da9b4e647b988ebbdaafa4344a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":539,
              "y":22},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b1e1d23b6944a8cb70f18061f0b2160",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":539,
                  "y":22},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66d6c9bc169045a085971b3aaacb2c8d",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":320},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e206d86a0fc14793bff58996340c2e02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":320},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"980f9c13a6bd4b2a9986cef06284be73",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":369,
              "y":296},
            "size":{
              "width":71,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f96be7cdb94748558424163bf96d3d99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":369,
                  "y":296},
                "size":{
                  "width":71,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3db2e08d4d664185b62603b0364a4b04":{
      "scriptId":"u0"},
    "8ea6ff72387a4d4d8bd40d7b77f8d61f":{
      "scriptId":"u1"},
    "3c03cff608174c6abcbb2feb15c8d8b3":{
      "scriptId":"u2"},
    "64fbfa92be714d6e803006ef82720b67":{
      "scriptId":"u3"},
    "8980ed288cd642fda86dff82235d1996":{
      "scriptId":"u4"},
    "ce39d96f522e42af94c80eb1398f1d6e":{
      "scriptId":"u5"},
    "770815513b3a4fb29fab3af3aeb87477":{
      "scriptId":"u6"},
    "47bba40e3acb4db699c84bfc288624b4":{
      "scriptId":"u7"},
    "2a16324385254021b9cb5be9c434f02b":{
      "scriptId":"u8"},
    "9b314b9bf0c847fd8733f46cc380170b":{
      "scriptId":"u9"},
    "b20c17bdba0744b69a0d8651b8dbc4ea":{
      "scriptId":"u10"},
    "69d1543619f847cb818efdafa0d9e258":{
      "scriptId":"u11"},
    "91332b4555264301983a78e051f3f39c":{
      "scriptId":"u12"},
    "3e3e56d2b9ff4820943a2fadc7aa7902":{
      "scriptId":"u13"},
    "5be677929b4644b58b282279c3bff932":{
      "scriptId":"u14"},
    "6ae6c2aa4da9402aaa6efafb8a29225f":{
      "scriptId":"u15"},
    "12396c04d2b0490a9681900058f27743":{
      "scriptId":"u16"},
    "44df0e5060f2471f8a27606ea41886a4":{
      "scriptId":"u17"},
    "4809aef025164591ae7a0abaa9aaa6b4":{
      "scriptId":"u18"},
    "57598f8211234c3591f1c08ea67c670d":{
      "scriptId":"u19"},
    "ab9a519467f541fd935d76e4047828eb":{
      "scriptId":"u20"},
    "fcb1c1744e89467c822c2410bea4888c":{
      "scriptId":"u21"},
    "049d72766ae44f648557f649dd02978f":{
      "scriptId":"u22"},
    "e2bb8b5794fb47159a22504cd3711d00":{
      "scriptId":"u23"},
    "3e6ebb72c6e846b3be63d1ef4a8adadd":{
      "scriptId":"u24"},
    "8c5b4e03b90a4b5699056296b718ee88":{
      "scriptId":"u25"},
    "87673854212f4f319bf3aa1cb07b8ba8":{
      "scriptId":"u26"},
    "37041448a11e467b9dc3c247974ee89d":{
      "scriptId":"u27"},
    "262beb9f63a3435d93f1eeec708c9774":{
      "scriptId":"u28"},
    "b0af2b4cfd1f44ff83ac47e6305ae3cc":{
      "scriptId":"u29"},
    "c0a0e071c6c543daa829986c179521db":{
      "scriptId":"u30"},
    "6e721890524d4d55a17e246a7ce3e1c5":{
      "scriptId":"u31"},
    "8758e9542b9b44c29f21d516d597b1cc":{
      "scriptId":"u32"},
    "950f80ef728b47fbaf60d5aecf52e645":{
      "scriptId":"u33"},
    "92ca3d1d086148a1a3064baeac92ce63":{
      "scriptId":"u34"},
    "80a88cae263245c9bd531fb6008ff2fe":{
      "scriptId":"u35"},
    "4fe5290dd39847d0acc13cf64c857909":{
      "scriptId":"u36"},
    "f0ce07c1ce5443deb30bcad9ad228538":{
      "scriptId":"u37"},
    "18a5af671a9d47768f3536e6de8bb482":{
      "scriptId":"u38"},
    "967696e7cfaa4e2986bfe8dffa196d8c":{
      "scriptId":"u39"},
    "f4bdcb8f8b3f43edbd69a0f44574e790":{
      "scriptId":"u40"},
    "659a29c3dd2947ea8f0bff5a498af06e":{
      "scriptId":"u41"},
    "699a3cd735764fc99c73770a9b3db7f4":{
      "scriptId":"u42"},
    "2e9f8b278f704667a0c082569e0a8da5":{
      "scriptId":"u43"},
    "5da41700ee764080b11cd222dedc683b":{
      "scriptId":"u44"},
    "fca6e88ff6f14f2ebcff31fb92067fb6":{
      "scriptId":"u45"},
    "d390777066974b988ed7f04b776973df":{
      "scriptId":"u46"},
    "4da8871ddfc94c8a843617bbb865c0ea":{
      "scriptId":"u47"},
    "e9abfcdcb4a44a09b3f9c0f1ca23a002":{
      "scriptId":"u48"},
    "e1a44b0e45244e0ab3ed7158fd5af8a0":{
      "scriptId":"u49"},
    "f515b65a579d404885298b591506d265":{
      "scriptId":"u50"},
    "ea18be11f21b4a6b8e208f1efd395e2e":{
      "scriptId":"u51"},
    "75982da9b4e647b988ebbdaafa4344a2":{
      "scriptId":"u52"},
    "1b1e1d23b6944a8cb70f18061f0b2160":{
      "scriptId":"u53"},
    "66d6c9bc169045a085971b3aaacb2c8d":{
      "scriptId":"u54"},
    "e206d86a0fc14793bff58996340c2e02":{
      "scriptId":"u55"},
    "980f9c13a6bd4b2a9986cef06284be73":{
      "scriptId":"u56"},
    "f96be7cdb94748558424163bf96d3d99":{
      "scriptId":"u57"}}});