$axure.loadCurrentPage({
  "url":"添加关注.html",
  "generationDate":new Date(1402913060978.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a419f2e3a55f4e4497811cb381195248",
    "type":"Axure:Page",
    "name":"添加关注",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"515249eb08af48f1bbf0111491e4e60d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":480},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e638a9df9eb84d20ba74416d0fe0d910",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":480},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u0.png"}},
{
          "id":"c7e7c98ca9eb4d528827951d3883fbb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c656167d0a94c26a35d579419d5ec7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u8.png"}},
{
          "id":"4aa134bfb72c46f5bdcc25f7b7e566a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":40,
              "y":16},
            "size":{
              "width":29,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6762daf744f64bc7b07072fefbf77f4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":40,
                  "y":16},
                "size":{
                  "width":29,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea83aa4b1fdf42f08fa516c6d462b5cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":79,
              "y":22},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"316827f648a6478084d4cf17fb3323d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":79,
                  "y":22},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2ff2f45f71c4f0c874412526b4dcce8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":76},
            "size":{
              "width":74,
              "height":74},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbe8e2a21af24a86a490431804c2384a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":76},
                "size":{
                  "width":74,
                  "height":74},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加关注/u8.png"}},
{
          "id":"bb15f68063a74967b4305c8696d25b1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":110,
              "y":84},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccbaac6fd175404cadc326f4cd7469f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":110,
                  "y":84},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27b2168e169f4baabefb43550ac61384",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":110},
            "size":{
              "width":183,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ee0d1b37d484ae5a02ddc6f275da6da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":110},
                "size":{
                  "width":183,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbb0f840891a4b62946ad5037629513d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":26,
              "y":180},
            "size":{
              "width":75,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22895184034e4c8b8f4aa8501639b321",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":26,
                  "y":180},
                "size":{
                  "width":75,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加关注/u14.png"}},
{
          "id":"fcba38f4bef34de98dc0c9721cfe3b1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":26,
              "y":226},
            "size":{
              "width":75,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"121cb0c1ee094274a873beb095c02d75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":26,
                  "y":226},
                "size":{
                  "width":75,
                  "height":54},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加关注/u16.png"}},
{
          "id":"056d8c7e83b34d47b280da56599e4994",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":111,
              "y":180},
            "size":{
              "width":209,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba3e60adeb5c44459fd92c99543217d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":111,
                  "y":180},
                "size":{
                  "width":209,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加关注/u18.png"}},
{
          "id":"8981860129c74a8cb46f9b09c4258e1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":111,
              "y":226},
            "size":{
              "width":209,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10e3c3f52fcc4dbc91417eccfaf9fabd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":111,
                  "y":226},
                "size":{
                  "width":209,
                  "height":54},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加关注/u20.png"}},
{
          "id":"ef9030a6bb894e9fbcb550a668ac8d7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC00},
            "location":{
              "x":26,
              "y":296},
            "size":{
              "width":284,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab7541b769ac400ba77d0e27f9ad3eac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC00},
                "location":{
                  "x":26,
                  "y":296},
                "size":{
                  "width":284,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加关注/u22.png"}},
{
          "id":"08f84c5594f4444c9628ad651d93f89f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":360,
              "y":120},
            "size":{
              "width":162,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"731250ce5a564c41882b486c8899b911",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":360,
                  "y":120},
                "size":{
                  "width":162,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u24.png"}},
{
          "id":"ff7de8c8f6584112b25bfd90a74f1ab4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":360,
              "y":60},
            "size":{
              "width":162,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2f26ef73fb64f4bb3ee5bcc07bf5b6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":360,
                  "y":60},
                "size":{
                  "width":162,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "515249eb08af48f1bbf0111491e4e60d":{
      "scriptId":"u0"},
    "e638a9df9eb84d20ba74416d0fe0d910":{
      "scriptId":"u1"},
    "c7e7c98ca9eb4d528827951d3883fbb0":{
      "scriptId":"u2"},
    "2c656167d0a94c26a35d579419d5ec7a":{
      "scriptId":"u3"},
    "4aa134bfb72c46f5bdcc25f7b7e566a6":{
      "scriptId":"u4"},
    "6762daf744f64bc7b07072fefbf77f4c":{
      "scriptId":"u5"},
    "ea83aa4b1fdf42f08fa516c6d462b5cd":{
      "scriptId":"u6"},
    "316827f648a6478084d4cf17fb3323d4":{
      "scriptId":"u7"},
    "b2ff2f45f71c4f0c874412526b4dcce8":{
      "scriptId":"u8"},
    "cbe8e2a21af24a86a490431804c2384a":{
      "scriptId":"u9"},
    "bb15f68063a74967b4305c8696d25b1c":{
      "scriptId":"u10"},
    "ccbaac6fd175404cadc326f4cd7469f5":{
      "scriptId":"u11"},
    "27b2168e169f4baabefb43550ac61384":{
      "scriptId":"u12"},
    "2ee0d1b37d484ae5a02ddc6f275da6da":{
      "scriptId":"u13"},
    "fbb0f840891a4b62946ad5037629513d":{
      "scriptId":"u14"},
    "22895184034e4c8b8f4aa8501639b321":{
      "scriptId":"u15"},
    "fcba38f4bef34de98dc0c9721cfe3b1f":{
      "scriptId":"u16"},
    "121cb0c1ee094274a873beb095c02d75":{
      "scriptId":"u17"},
    "056d8c7e83b34d47b280da56599e4994":{
      "scriptId":"u18"},
    "ba3e60adeb5c44459fd92c99543217d3":{
      "scriptId":"u19"},
    "8981860129c74a8cb46f9b09c4258e1f":{
      "scriptId":"u20"},
    "10e3c3f52fcc4dbc91417eccfaf9fabd":{
      "scriptId":"u21"},
    "ef9030a6bb894e9fbcb550a668ac8d7e":{
      "scriptId":"u22"},
    "ab7541b769ac400ba77d0e27f9ad3eac":{
      "scriptId":"u23"},
    "08f84c5594f4444c9628ad651d93f89f":{
      "scriptId":"u24"},
    "731250ce5a564c41882b486c8899b911":{
      "scriptId":"u25"},
    "ff7de8c8f6584112b25bfd90a74f1ab4":{
      "scriptId":"u26"},
    "d2f26ef73fb64f4bb3ee5bcc07bf5b6f":{
      "scriptId":"u27"}}});