$axure.loadCurrentPage({
  "url":"规则说明.html",
  "generationDate":new Date(1400556881685.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0432380d094844d1ba2fd8e380bf2965",
    "type":"Axure:Page",
    "name":"规则说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8a55a13c7d244467ad993928f618ccf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":70},
            "size":{
              "width":50,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b1042c1737b468881c85361838722e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":70},
                "size":{
                  "width":50,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u0.png"}},
{
          "id":"833c3eb446bc4a6f993c30d16d1e1afb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":70,
              "y":70},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7df288b1badd498f838068cf09ba1b98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":70,
                  "y":70},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u2.png"}},
{
          "id":"78eb98f9a9534e86a5045dcd9038c811",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":150,
              "y":70},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"070ab1a4763f48fcb304d1f4db9cbf6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":150,
                  "y":70},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u2.png"}},
{
          "id":"ca5fe7dff73c411eb0270806cfc6ecd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":70},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddde41326de547f2bcdcd4a1d20eb0a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":70},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u2.png"}},
{
          "id":"f7cca8e578f14a93ab4a0c2a419c2258",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":310,
              "y":70},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb1c820e6ea04c32a7b4035b4a6b8876",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":310,
                  "y":70},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u2.png"}},
{
          "id":"9fea412db3794a288c785044df72d648",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":44},
            "size":{
              "width":160,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b557f0881fcf400ea94d47ba80e2a4dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":44},
                "size":{
                  "width":160,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df6831fa2fa24f74a9d0d2484deca488",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":120},
            "size":{
              "width":50,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b61fa14600f847959a3304e6f7811d74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":120},
                "size":{
                  "width":50,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u12.png"}},
{
          "id":"9948f6cb27544713a3684fd1359e7158",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":120},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b26cb74646b46b8a5f1c79d267c5303",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":120},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u14.png"}},
{
          "id":"6e889ebc16234c6ba352842cc352bd6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":150,
              "y":120},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91606ae36d9a4abb82a55dc192097a3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":150,
                  "y":120},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u2.png"}},
{
          "id":"93cc93c067b4457bbb43a5d119669939",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":120},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"825c572596244a6f8759a13831e79171",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":120},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u2.png"}},
{
          "id":"065632d7948f4435ba6315cf0d8ed47e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":310,
              "y":120},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1c5a42ab3aa419ab4f29bd2a6210890",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":310,
                  "y":120},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u2.png"}},
{
          "id":"8b6982191b1b415181cd6bd7479f5994",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":125},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb98ffe6660d4dbdbafb6c2583e51d49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":125},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u22.png"}},
{
          "id":"52f430f455844c93a5c019ed4c2de3ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":170},
            "size":{
              "width":50,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec9f42b5d62a45efbfea49a7546bdd53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":170},
                "size":{
                  "width":50,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u12.png"}},
{
          "id":"50338747effd44c2a45062b245ac4f0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":170},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31a0ad51ba4b45ad8f55e02b9129dc53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":170},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u14.png"}},
{
          "id":"bdb4e3a40772457fbe262a08858ca4c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":150,
              "y":170},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c636f20e95e040f9a9939f2234b4e06f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":150,
                  "y":170},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u2.png"}},
{
          "id":"489e57c4430946cd9c4cd2b9151116dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":170},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7261e961ff6f44a7bae8fd2fc6c60f8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":170},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u2.png"}},
{
          "id":"a09ec2a8db55450ba3483ba7b427bfbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":310,
              "y":170},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e658236bfd494d5f9f22f60f96dabbd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":310,
                  "y":170},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u2.png"}},
{
          "id":"94469d5b860d4e8195bec646f424684c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":175},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3deb44b712c432e917ccbda6a05130e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":175},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/规则说明/u34.png"}},
{
          "id":"cd1d1169316342a4b76330354647aa61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":20,
              "y":281},
            "size":{
              "width":70,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0415e611f5b4d45a4d4e65a4403ec89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":20,
                  "y":281},
                "size":{
                  "width":70,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a95a7e202d27414d900b4e8937678a28",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":280},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b7fed823759a4b62aa2e1f2f2015fd8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":20,
              "y":316},
            "size":{
              "width":70,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"334f04087c1340e4924628fc1d9cf5c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":20,
                  "y":316},
                "size":{
                  "width":70,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a6eba0528ac40c28e2abe617fe10140",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":315},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c4fa9de7d83643b9ba207d82304f067b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":241},
            "size":{
              "width":160,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"413897dadec543e3bda5c17b3ee1801f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":241},
                "size":{
                  "width":160,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f03c6b2d632442ac95c451eb9e48499f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":350,
              "y":284},
            "size":{
              "width":130,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fb2f9f07a32405aa890d0f70d222ead",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":350,
                  "y":284},
                "size":{
                  "width":130,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e97abeaf187245a6b2e5cb4c59278128",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":350,
              "y":314},
            "size":{
              "width":130,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a645a2d245a4e46868fe7777da23ec6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":350,
                  "y":314},
                "size":{
                  "width":130,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1168e71a9fcb4e8da8eb7289e9fee34a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":430,
              "y":75},
            "size":{
              "width":130,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0d1afc8f56c43bfa6bb674adbf8de66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":430,
                  "y":75},
                "size":{
                  "width":130,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4793648699564d1c81ffded4e7cfbe4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":430,
              "y":125},
            "size":{
              "width":160,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04464a723ee04e4cbbf592f9f454f76b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":430,
                  "y":125},
                "size":{
                  "width":160,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89daa9e2e3094d469b1dc23e44853cb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":430,
              "y":175},
            "size":{
              "width":200,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25d09486a6594cee8d4bea013f4ff711",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":430,
                  "y":175},
                "size":{
                  "width":200,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8a55a13c7d244467ad993928f618ccf4":{
      "scriptId":"u0"},
    "8b1042c1737b468881c85361838722e1":{
      "scriptId":"u1"},
    "833c3eb446bc4a6f993c30d16d1e1afb":{
      "scriptId":"u2"},
    "7df288b1badd498f838068cf09ba1b98":{
      "scriptId":"u3"},
    "78eb98f9a9534e86a5045dcd9038c811":{
      "scriptId":"u4"},
    "070ab1a4763f48fcb304d1f4db9cbf6f":{
      "scriptId":"u5"},
    "ca5fe7dff73c411eb0270806cfc6ecd1":{
      "scriptId":"u6"},
    "ddde41326de547f2bcdcd4a1d20eb0a6":{
      "scriptId":"u7"},
    "f7cca8e578f14a93ab4a0c2a419c2258":{
      "scriptId":"u8"},
    "cb1c820e6ea04c32a7b4035b4a6b8876":{
      "scriptId":"u9"},
    "9fea412db3794a288c785044df72d648":{
      "scriptId":"u10"},
    "b557f0881fcf400ea94d47ba80e2a4dc":{
      "scriptId":"u11"},
    "df6831fa2fa24f74a9d0d2484deca488":{
      "scriptId":"u12"},
    "b61fa14600f847959a3304e6f7811d74":{
      "scriptId":"u13"},
    "9948f6cb27544713a3684fd1359e7158":{
      "scriptId":"u14"},
    "6b26cb74646b46b8a5f1c79d267c5303":{
      "scriptId":"u15"},
    "6e889ebc16234c6ba352842cc352bd6c":{
      "scriptId":"u16"},
    "91606ae36d9a4abb82a55dc192097a3c":{
      "scriptId":"u17"},
    "93cc93c067b4457bbb43a5d119669939":{
      "scriptId":"u18"},
    "825c572596244a6f8759a13831e79171":{
      "scriptId":"u19"},
    "065632d7948f4435ba6315cf0d8ed47e":{
      "scriptId":"u20"},
    "b1c5a42ab3aa419ab4f29bd2a6210890":{
      "scriptId":"u21"},
    "8b6982191b1b415181cd6bd7479f5994":{
      "scriptId":"u22"},
    "cb98ffe6660d4dbdbafb6c2583e51d49":{
      "scriptId":"u23"},
    "52f430f455844c93a5c019ed4c2de3ac":{
      "scriptId":"u24"},
    "ec9f42b5d62a45efbfea49a7546bdd53":{
      "scriptId":"u25"},
    "50338747effd44c2a45062b245ac4f0b":{
      "scriptId":"u26"},
    "31a0ad51ba4b45ad8f55e02b9129dc53":{
      "scriptId":"u27"},
    "bdb4e3a40772457fbe262a08858ca4c7":{
      "scriptId":"u28"},
    "c636f20e95e040f9a9939f2234b4e06f":{
      "scriptId":"u29"},
    "489e57c4430946cd9c4cd2b9151116dc":{
      "scriptId":"u30"},
    "7261e961ff6f44a7bae8fd2fc6c60f8f":{
      "scriptId":"u31"},
    "a09ec2a8db55450ba3483ba7b427bfbc":{
      "scriptId":"u32"},
    "e658236bfd494d5f9f22f60f96dabbd0":{
      "scriptId":"u33"},
    "94469d5b860d4e8195bec646f424684c":{
      "scriptId":"u34"},
    "a3deb44b712c432e917ccbda6a05130e":{
      "scriptId":"u35"},
    "cd1d1169316342a4b76330354647aa61":{
      "scriptId":"u36"},
    "e0415e611f5b4d45a4d4e65a4403ec89":{
      "scriptId":"u37"},
    "a95a7e202d27414d900b4e8937678a28":{
      "scriptId":"u38"},
    "b7fed823759a4b62aa2e1f2f2015fd8e":{
      "scriptId":"u39"},
    "334f04087c1340e4924628fc1d9cf5c7":{
      "scriptId":"u40"},
    "8a6eba0528ac40c28e2abe617fe10140":{
      "scriptId":"u41"},
    "c4fa9de7d83643b9ba207d82304f067b":{
      "scriptId":"u42"},
    "413897dadec543e3bda5c17b3ee1801f":{
      "scriptId":"u43"},
    "f03c6b2d632442ac95c451eb9e48499f":{
      "scriptId":"u44"},
    "9fb2f9f07a32405aa890d0f70d222ead":{
      "scriptId":"u45"},
    "e97abeaf187245a6b2e5cb4c59278128":{
      "scriptId":"u46"},
    "8a645a2d245a4e46868fe7777da23ec6":{
      "scriptId":"u47"},
    "1168e71a9fcb4e8da8eb7289e9fee34a":{
      "scriptId":"u48"},
    "d0d1afc8f56c43bfa6bb674adbf8de66":{
      "scriptId":"u49"},
    "4793648699564d1c81ffded4e7cfbe4d":{
      "scriptId":"u50"},
    "04464a723ee04e4cbbf592f9f454f76b":{
      "scriptId":"u51"},
    "89daa9e2e3094d469b1dc23e44853cb4":{
      "scriptId":"u52"},
    "25d09486a6594cee8d4bea013f4ff711":{
      "scriptId":"u53"}}});