$axure.loadCurrentPage({
  "url":"活动详情.html",
  "generationDate":new Date(1404457236031.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"292d71ca307745dbbd7f4cda4e74c4ff",
    "type":"Axure:Page",
    "name":"活动详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fe1398978f8d4f3aa6861064dfab3c94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":109,
              "y":42},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c08381563e0454e94c86f0580c6ec8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":42},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76084e437a6e46f4b8f8e93b1a36f31d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":320,
              "height":1280},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e53f7f3da97e46a7a7eead905efaff97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":320,
                  "height":1280},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u2.png"}},
{
          "id":"9b8cbd842b3c41c6b1279db1349ba7d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b66eb774c1124f6ca9969f320dd26a5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u8.png"}},
{
          "id":"dabea0ef1a594beda1955abf864f0bb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":70,
              "y":36},
            "size":{
              "width":29,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21e11ce11aca4a3096c638ea65453310",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":70,
                  "y":36},
                "size":{
                  "width":29,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45c7672adae74f44abdb89e252030ed1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":109,
              "y":42},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03c3abfd8ede416a8c5e68dd71de99f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":42},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c469156ffd854f519c301c476d4b20ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":81,
              "y":371},
            "size":{
              "width":280,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a62aca01c9446b5ac91158a458fb3c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":81,
                  "y":371},
                "size":{
                  "width":280,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/参加活动/u28.png"}},
{
          "id":"bcd3ec2591cf41439bd9e02a8711503c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":66,
              "y":394},
            "size":{
              "width":10,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6d9ce3d32d240478ca76c80ec8567be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":66,
                  "y":394},
                "size":{
                  "width":10,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于人信汇/u12.png"}},
{
          "id":"6a4d92f376a2439bb4ffcbbf6dfcee35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":82,
              "y":394},
            "size":{
              "width":120,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32a8bb09e0924296b3b9109ffbddb043",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":82,
                  "y":394},
                "size":{
                  "width":120,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/参加活动/u32.png"}},
{
          "id":"d73654af5d27486086064829ea217c0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":65,
              "y":464},
            "size":{
              "width":140,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e89872feb094199890657993929bd91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":65,
                  "y":464},
                "size":{
                  "width":140,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20a224bb03d4455b81f4883da0020724",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"48px",
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":66,
              "y":300},
            "size":{
              "width":49,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f639ba5240fd4ee1aeba6ac5f1dc12a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"48px",
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":66,
                  "y":300},
                "size":{
                  "width":49,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61fdfd9b1eac4aeda8ab5648b4611f4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":76,
              "y":316},
            "size":{
              "width":40,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3307481379434a418c289eebe451bb74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":76,
                  "y":316},
                "size":{
                  "width":40,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"025376fce2ce4479a332af7fc5d72576",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":281},
            "size":{
              "width":291,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/参加活动/u40_line.png"}},
{
          "id":"279e913a254e4ef2ba82658286d416ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":60,
              "y":541},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cae3f95949e48bbb355b4bc67483395",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":60,
                  "y":541},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8475ee8c74384602a78dbe521e4f20f6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":351},
            "size":{
              "width":291,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/参加活动/u40_line.png"}},
{
          "id":"b21c6133cc744410b1cc3ff10b5ea578",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":65,
              "y":416},
            "size":{
              "width":160,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd1c384fea9e4f7b8a828c65da63dc7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":65,
                  "y":416},
                "size":{
                  "width":160,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/参加活动/u44.png"}},
{
          "id":"5692a89562624403a5401abf24cd1e64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":64,
              "y":371},
            "size":{
              "width":15,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8adaad680d3f4f80a185b03078e0989c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":64,
                  "y":371},
                "size":{
                  "width":15,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3952467858d4095ad75523a9723ca66",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":126,
              "y":305},
            "size":{
              "width":214,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b1d6b681a364fe599f1e28167365ed3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":126,
                  "y":305},
                "size":{
                  "width":214,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f21a8bb02db465096c9a08cafca6f11",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":80},
            "size":{
              "width":300,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05d14c96556a45c6ab62a82508a2fed4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":80},
                "size":{
                  "width":300,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/参加活动/u50.jpg"}},
{
          "id":"cd06a41b87354102badf013f2c417727",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCC6666},
            "location":{
              "x":40,
              "y":489},
            "size":{
              "width":320,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8e95b5605b04292adee8c5bf719990f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC6666},
                "location":{
                  "x":40,
                  "y":489},
                "size":{
                  "width":320,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/参加活动/u52.png"}},
{
          "id":"13f605a50ad341a892b84c0693c9a073",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":760},
            "size":{
              "width":270,
              "height":208}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26c0d10117a24915b31c02c77da1c6fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":760},
                "size":{
                  "width":270,
                  "height":208}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8dc9cb0c0bd344448d9d45bff9c72ec8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":1140},
            "size":{
              "width":260,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdb8980666b24797931e6333d8b6d425",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":1140},
                "size":{
                  "width":260,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1acf323e23e645be9c51b5f0b1a24836",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":65,
              "y":440},
            "size":{
              "width":178,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"510c12b8cf974c18b9852ae29c0f955e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":65,
                  "y":440},
                "size":{
                  "width":178,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/参加活动/u58.png"}},
{
          "id":"6b4b2c1878f845ffab22df2e645f3e0d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":68.5,
              "y":983},
            "size":{
              "width":265,
              "height":147}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f249aba32c5b42848496718b6affe68d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":68.5,
                  "y":983},
                "size":{
                  "width":265,
                  "height":147}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u42.jpg"}},
{
          "id":"092b44e255844ecfaf09442ec1fbde4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC0000,
              "opacity":1},
            "location":{
              "x":70,
              "y":567},
            "size":{
              "width":262,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a24d5a3e51e74865b947d7026f69843a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":567},
                "size":{
                  "width":262,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd26ee44581848eeaec6033eb48b38d5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":598},
            "size":{
              "width":262,
              "height":171}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86f4903a27794166b4ca84c8c46a44b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":598},
                "size":{
                  "width":262,
                  "height":171}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u46.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "fe1398978f8d4f3aa6861064dfab3c94":{
      "scriptId":"u0"},
    "9c08381563e0454e94c86f0580c6ec8f":{
      "scriptId":"u1"},
    "76084e437a6e46f4b8f8e93b1a36f31d":{
      "scriptId":"u2"},
    "e53f7f3da97e46a7a7eead905efaff97":{
      "scriptId":"u3"},
    "9b8cbd842b3c41c6b1279db1349ba7d2":{
      "scriptId":"u4"},
    "b66eb774c1124f6ca9969f320dd26a5b":{
      "scriptId":"u5"},
    "dabea0ef1a594beda1955abf864f0bb7":{
      "scriptId":"u6"},
    "21e11ce11aca4a3096c638ea65453310":{
      "scriptId":"u7"},
    "45c7672adae74f44abdb89e252030ed1":{
      "scriptId":"u8"},
    "03c3abfd8ede416a8c5e68dd71de99f4":{
      "scriptId":"u9"},
    "c469156ffd854f519c301c476d4b20ed":{
      "scriptId":"u10"},
    "5a62aca01c9446b5ac91158a458fb3c7":{
      "scriptId":"u11"},
    "bcd3ec2591cf41439bd9e02a8711503c":{
      "scriptId":"u12"},
    "d6d9ce3d32d240478ca76c80ec8567be":{
      "scriptId":"u13"},
    "6a4d92f376a2439bb4ffcbbf6dfcee35":{
      "scriptId":"u14"},
    "32a8bb09e0924296b3b9109ffbddb043":{
      "scriptId":"u15"},
    "d73654af5d27486086064829ea217c0b":{
      "scriptId":"u16"},
    "6e89872feb094199890657993929bd91":{
      "scriptId":"u17"},
    "20a224bb03d4455b81f4883da0020724":{
      "scriptId":"u18"},
    "f639ba5240fd4ee1aeba6ac5f1dc12a2":{
      "scriptId":"u19"},
    "61fdfd9b1eac4aeda8ab5648b4611f4f":{
      "scriptId":"u20"},
    "3307481379434a418c289eebe451bb74":{
      "scriptId":"u21"},
    "025376fce2ce4479a332af7fc5d72576":{
      "scriptId":"u22"},
    "279e913a254e4ef2ba82658286d416ca":{
      "scriptId":"u23"},
    "7cae3f95949e48bbb355b4bc67483395":{
      "scriptId":"u24"},
    "8475ee8c74384602a78dbe521e4f20f6":{
      "scriptId":"u25"},
    "b21c6133cc744410b1cc3ff10b5ea578":{
      "scriptId":"u26"},
    "bd1c384fea9e4f7b8a828c65da63dc7d":{
      "scriptId":"u27"},
    "5692a89562624403a5401abf24cd1e64":{
      "scriptId":"u28"},
    "8adaad680d3f4f80a185b03078e0989c":{
      "scriptId":"u29"},
    "a3952467858d4095ad75523a9723ca66":{
      "scriptId":"u30"},
    "7b1d6b681a364fe599f1e28167365ed3":{
      "scriptId":"u31"},
    "3f21a8bb02db465096c9a08cafca6f11":{
      "scriptId":"u32"},
    "05d14c96556a45c6ab62a82508a2fed4":{
      "scriptId":"u33"},
    "cd06a41b87354102badf013f2c417727":{
      "scriptId":"u34"},
    "a8e95b5605b04292adee8c5bf719990f":{
      "scriptId":"u35"},
    "13f605a50ad341a892b84c0693c9a073":{
      "scriptId":"u36"},
    "26c0d10117a24915b31c02c77da1c6fc":{
      "scriptId":"u37"},
    "8dc9cb0c0bd344448d9d45bff9c72ec8":{
      "scriptId":"u38"},
    "cdb8980666b24797931e6333d8b6d425":{
      "scriptId":"u39"},
    "1acf323e23e645be9c51b5f0b1a24836":{
      "scriptId":"u40"},
    "510c12b8cf974c18b9852ae29c0f955e":{
      "scriptId":"u41"},
    "6b4b2c1878f845ffab22df2e645f3e0d":{
      "scriptId":"u42"},
    "f249aba32c5b42848496718b6affe68d":{
      "scriptId":"u43"},
    "092b44e255844ecfaf09442ec1fbde4e":{
      "scriptId":"u44"},
    "a24d5a3e51e74865b947d7026f69843a":{
      "scriptId":"u45"},
    "dd26ee44581848eeaec6033eb48b38d5":{
      "scriptId":"u46"},
    "86f4903a27794166b4ca84c8c46a44b5":{
      "scriptId":"u47"}}});