$axure.loadCurrentPage({
  "url":"我的优惠券.html",
  "generationDate":new Date(1404457234848.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7d4f0d02a9b045d188614c651d33d807",
    "type":"Axure:Page",
    "name":"我的优惠券",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e2b8ba88470f4956ac1bb5b792fa4623",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":24,
              "y":14},
            "size":{
              "width":320,
              "height":480},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfa8cef557cd4d61a04eec1e9e12eb2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":24,
                  "y":14},
                "size":{
                  "width":320,
                  "height":480},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找美食/u195.png"}},
{
          "id":"4547f4b0148f45f1a5d177053d99f63f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":34,
              "y":139},
            "size":{
              "width":300,
              "height":164},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c4161621a6f41e6acb748b7600b2c52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":34,
                  "y":139},
                "size":{
                  "width":300,
                  "height":164},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的优惠券/u2.png"}},
{
          "id":"081cb81c37ec4ee6963d98b8a20dc196",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":113},
            "size":{
              "width":300,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c20a9caf164d4d4e8bbb5ddc6319df3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":113},
                "size":{
                  "width":300,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的优惠券/u4.jpg"}},
{
          "id":"46f6f74f0e0f44c6a9d82c3fa7f969e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":24,
              "y":14},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49925409e4a742f6ad57628f3a51119e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":24,
                  "y":14},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u8.png"}},
{
          "id":"6608c2d92332431ba460011b40090900",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":92,
              "y":26},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3028f8c545354ef0908255d3e8de6082",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":26},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3eabf12d2529445ca12084ac59273b7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":70,
              "y":454},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f22f23120ea4a25a262fb94ad2210af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":70,
                  "y":454},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u2.png"}},
{
          "id":"028b57baee944c28a1b7496c84167dbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":162,
              "y":454},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5a576623399462e9cd0020cb0aa4994",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":162,
                  "y":454},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u2.png"}},
{
          "id":"fd71a0da3aa040faaeea22640b8e254c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":252,
              "y":454},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74e84265c7f94f6096d20d12029f0535",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":252,
                  "y":454},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u2.png"}},
{
          "id":"c2c106d84dde4788b4cb76c1db405da6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":134,
              "y":64},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f03bbac4eaa45d68effec3d5d4f50d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":134,
                  "y":64},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u57.png"}},
{
          "id":"32e282c49f5841a090bd13c7d6662266",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":252,
              "y":414},
            "size":{
              "width":93,
              "height":40},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac664bd733794732bd6d04dc931e6854",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":252,
                  "y":414},
                "size":{
                  "width":93,
                  "height":40},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的优惠券/u18.png"}},
{
          "id":"33e0c54f6dcf4400b2dc859b4e282e98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":34,
              "y":263},
            "size":{
              "width":300,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4eb056f48a9946db911c036760c310a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":34,
                  "y":263},
                "size":{
                  "width":300,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的优惠券/u20.png"}},
{
          "id":"0be95b329f5c47218ad12dae8e8a45a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":44,
              "y":279},
            "size":{
              "width":140,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9dd99bb8eb1449e8ec29ff37f8c1d8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":44,
                  "y":279},
                "size":{
                  "width":140,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d07e88da0fb4e9ca77a4d2a11d1906c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xCC333333},
            "location":{
              "x":34,
              "y":203},
            "size":{
              "width":300,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb2ad48270474a1b89f00dd0b4d8f952",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xCC333333},
                "location":{
                  "x":34,
                  "y":203},
                "size":{
                  "width":300,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的优惠券/u24.png"}},
{
          "id":"096aa9d86fd94b93a309a0850666d099",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":44,
              "y":209},
            "size":{
              "width":190,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cc608109b634aa7a7c90c46c96109d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":209},
                "size":{
                  "width":190,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e60da44bcbc7461a811ab4323510743b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":44,
              "y":228},
            "size":{
              "width":215,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69a14054eeb74a3aa460b6805cdb59dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":228},
                "size":{
                  "width":215,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea1a1151a3784840b255885e988bc83b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":267},
            "size":{
              "width":40,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a606349572a847a4a5c0d04e7d4f6d1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":288,
                  "y":267},
                "size":{
                  "width":40,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的优惠券/u30.png"}},
{
          "id":"1faf14c31af747cbb7378f215adfed61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":34,
              "y":308},
            "size":{
              "width":300,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14cd2b78fb8c4210bbcf3cca92023e75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":34,
                  "y":308},
                "size":{
                  "width":300,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的优惠券/u20.png"}},
{
          "id":"34c5511eeddb43b38f9c0563b190443d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":44,
              "y":324},
            "size":{
              "width":140,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e536753463941d5933cda3ff33d921d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":44,
                  "y":324},
                "size":{
                  "width":140,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b51fb5f266041fa83961bb53434d272",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":312},
            "size":{
              "width":40,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0410889ab584974aedfe07019e3ec10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":288,
                  "y":312},
                "size":{
                  "width":40,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的优惠券/u30.png"}},
{
          "id":"a742f5764c2f430c80e7a08f5f1044fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":34,
              "y":353},
            "size":{
              "width":300,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36db1c4ce6f342bdbfbbe2800537e141",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":34,
                  "y":353},
                "size":{
                  "width":300,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的优惠券/u20.png"}},
{
          "id":"4fdbd47387cd4030aab4998f7569193a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":44,
              "y":369},
            "size":{
              "width":140,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7f4381a04604f438e7863378f5f9994",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":44,
                  "y":369},
                "size":{
                  "width":140,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8bc896d55b84e4babf9756b90001e28",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":374},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab5f82d49b9745839f5931afff1997fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":374},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"63e6de5dc7c34584b4344cbe8e4068ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":34,
              "y":514},
            "size":{
              "width":294,
              "height":156}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f30bac2d7b54eea88027719133a2124",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":514},
                "size":{
                  "width":294,
                  "height":156}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f2d0e2089eb4e14afec4755ca7f2ad0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":590,
              "y":18},
            "size":{
              "width":320,
              "height":692},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48992a4ec7b640afbbd124b7792bc716",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":590,
                  "y":18},
                "size":{
                  "width":320,
                  "height":692},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的优惠券/u46.png"}},
{
          "id":"befc3664a5d548c49b3afe74b047a089",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":590,
              "y":18},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00a9b89baf8a4a2cb23bacd90a14080e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":590,
                  "y":18},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u8.png"}},
{
          "id":"baddd42b21e640579be50ec7c9875cd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":620,
              "y":24},
            "size":{
              "width":29,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1666e7eea8464bc5a73230da3a1120f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":620,
                  "y":24},
                "size":{
                  "width":29,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34d028dd12d84984bb432039bd61ef5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":659,
              "y":30},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e938d59104b447c9b835e5b9e38e1105",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":659,
                  "y":30},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67a9905c708f4a4eb173269157147e6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":590,
              "y":58},
            "size":{
              "width":320,
              "height":64},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7eb8eaf271c43669be1ad643865c555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":590,
                  "y":58},
                "size":{
                  "width":320,
                  "height":64},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的活动/u119.png"}},
{
          "id":"d7fc8fb2d49c449898f74538d22fe058",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":132},
            "size":{
              "width":300,
              "height":178},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14b3633280b14e78b7d0f1e8471388b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":132},
                "size":{
                  "width":300,
                  "height":178},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找品牌/u233.png"}},
{
          "id":"b5bf400fb1b246babfbe876f1768cabb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":321},
            "size":{
              "width":300,
              "height":178},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e602d05691b463880537e0fbf2c919c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":321},
                "size":{
                  "width":300,
                  "height":178},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找品牌/u233.png"}},
{
          "id":"f04af6d4c0894cd391ccec3bc9da9938",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":980,
              "y":18},
            "size":{
              "width":320,
              "height":540},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b47f908b70b8497bac5766a451c21ea0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":980,
                  "y":18},
                "size":{
                  "width":320,
                  "height":540},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的活动/u2.png"}},
{
          "id":"1bbcaca68ae140e68f80ab3d4c497839",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":980,
              "y":18},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23b2f375bc8a45efa83930fcac1be79c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":980,
                  "y":18},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u8.png"}},
{
          "id":"2ac52e382e3840b2a0f2fd88eb6fad9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":1010,
              "y":24},
            "size":{
              "width":29,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7e1c5b867ad4e05b029f75de6938fa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":1010,
                  "y":24},
                "size":{
                  "width":29,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2aa845d60df34b038798a3caa1ab3042",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1049,
              "y":30},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4897610825cf4187849efd828078c29b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1049,
                  "y":30},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33882e80d3124f54bc9d4bbdc5b180dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":980,
              "y":58},
            "size":{
              "width":320,
              "height":64},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"170282a7285b4152858920fb539add7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":980,
                  "y":58},
                "size":{
                  "width":320,
                  "height":64},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的活动/u119.png"}},
{
          "id":"99fdf5f844354135b4ac9db5398be60d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":1048,
              "y":250},
            "size":{
              "width":181,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3bf0a06b5344494a5162c6bb082fb8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":1048,
                  "y":250},
                "size":{
                  "width":181,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58899dc7e2f0401fb81731638a85e606",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":1052,
              "y":298},
            "size":{
              "width":172,
              "height":40},
            "cornerRadiusTopLeft":"46"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8933f447ef574549ae6d85ebf695066e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":1052,
                  "y":298},
                "size":{
                  "width":172,
                  "height":40},
                "cornerRadiusTopLeft":"46"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的活动/u123.png"}},
{
          "id":"049bac56fb7548d68d1cd8fd7bb2c935",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":517},
            "size":{
              "width":300,
              "height":178},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dbc8b0de83449409bf65fead528bebf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":517},
                "size":{
                  "width":300,
                  "height":178},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找品牌/u233.png"}},
{
          "id":"b2ecc239226a4d26aacb3e5e74a1cb0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "paddingTop":"5",
            "paddingBottom":"5",
            "location":{
              "x":796,
              "y":68},
            "size":{
              "width":104,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"670ed0b5f4324575a1d59184cc343a42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "paddingTop":"5",
                "paddingBottom":"5",
                "location":{
                  "x":796,
                  "y":68},
                "size":{
                  "width":104,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的会员卡/u104.png"}},
{
          "id":"c5d5c4bc7fc74dfc9f321d174ee2e202",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "paddingTop":"5",
            "paddingBottom":"5",
            "location":{
              "x":796,
              "y":108},
            "size":{
              "width":104,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef3501a54ee44fcb88a3d373778f7847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "paddingTop":"5",
                "paddingBottom":"5",
                "location":{
                  "x":796,
                  "y":108},
                "size":{
                  "width":104,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的会员卡/u104.png"}},
{
          "id":"be31411a997348e696284e6e131451be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "paddingTop":"5",
            "paddingBottom":"5",
            "location":{
              "x":796,
              "y":148},
            "size":{
              "width":104,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7aff747e021419b9def19a2954ee2c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "paddingTop":"5",
                "paddingBottom":"5",
                "location":{
                  "x":796,
                  "y":148},
                "size":{
                  "width":104,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的会员卡/u104.png"}},
{
          "id":"d26cd0fc98464168bcacf8e30b6fe267",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":830,
              "y":320},
            "size":{
              "width":68,
              "height":67},
            "rotation":"0",
            "textRotation":"45",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ae1af720e2d4a1c84f88584938920b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":830,
                  "y":320},
                "size":{
                  "width":68,
                  "height":67},
                "rotation":"0",
                "textRotation":"45",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的优惠券/u82.png"}},
{
          "id":"1e5287a396e84cc39770662725d64d44",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":898,
              "y":300},
            "size":{
              "width":18,
              "height":19},
            "rotation":"0",
            "textRotation":"45",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"347489dae815460fb16cb7e744c64ceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":898,
                  "y":300},
                "size":{
                  "width":18,
                  "height":19},
                "rotation":"0",
                "textRotation":"45",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的优惠券/u84.png"}},
{
          "id":"d6586596d83848d5b8ebe741509c7d93",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":833,
              "y":517},
            "size":{
              "width":67,
              "height":67},
            "rotation":"0",
            "textRotation":"45",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2187b1f7c7ed4572997fa1ae1261cf55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":833,
                  "y":517},
                "size":{
                  "width":67,
                  "height":67},
                "rotation":"0",
                "textRotation":"45",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的优惠券/u86.png"}},
{
          "id":"14e654d19b5f4a1a89b325c25b95f675",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":897,
              "y":300},
            "size":{
              "width":19,
              "height":19},
            "rotation":"0",
            "textRotation":"45",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3f8c9d3aaa04636ba96345e63a7ddf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":897,
                  "y":300},
                "size":{
                  "width":19,
                  "height":19},
                "rotation":"0",
                "textRotation":"45",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的优惠券/u88.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e2b8ba88470f4956ac1bb5b792fa4623":{
      "scriptId":"u0"},
    "dfa8cef557cd4d61a04eec1e9e12eb2e":{
      "scriptId":"u1"},
    "4547f4b0148f45f1a5d177053d99f63f":{
      "scriptId":"u2"},
    "6c4161621a6f41e6acb748b7600b2c52":{
      "scriptId":"u3"},
    "081cb81c37ec4ee6963d98b8a20dc196":{
      "scriptId":"u4"},
    "c20a9caf164d4d4e8bbb5ddc6319df3c":{
      "scriptId":"u5"},
    "46f6f74f0e0f44c6a9d82c3fa7f969e0":{
      "scriptId":"u6"},
    "49925409e4a742f6ad57628f3a51119e":{
      "scriptId":"u7"},
    "6608c2d92332431ba460011b40090900":{
      "scriptId":"u8"},
    "3028f8c545354ef0908255d3e8de6082":{
      "scriptId":"u9"},
    "3eabf12d2529445ca12084ac59273b7c":{
      "scriptId":"u10"},
    "9f22f23120ea4a25a262fb94ad2210af":{
      "scriptId":"u11"},
    "028b57baee944c28a1b7496c84167dbe":{
      "scriptId":"u12"},
    "f5a576623399462e9cd0020cb0aa4994":{
      "scriptId":"u13"},
    "fd71a0da3aa040faaeea22640b8e254c":{
      "scriptId":"u14"},
    "74e84265c7f94f6096d20d12029f0535":{
      "scriptId":"u15"},
    "c2c106d84dde4788b4cb76c1db405da6":{
      "scriptId":"u16"},
    "0f03bbac4eaa45d68effec3d5d4f50d5":{
      "scriptId":"u17"},
    "32e282c49f5841a090bd13c7d6662266":{
      "scriptId":"u18"},
    "ac664bd733794732bd6d04dc931e6854":{
      "scriptId":"u19"},
    "33e0c54f6dcf4400b2dc859b4e282e98":{
      "scriptId":"u20"},
    "4eb056f48a9946db911c036760c310a6":{
      "scriptId":"u21"},
    "0be95b329f5c47218ad12dae8e8a45a6":{
      "scriptId":"u22"},
    "c9dd99bb8eb1449e8ec29ff37f8c1d8c":{
      "scriptId":"u23"},
    "8d07e88da0fb4e9ca77a4d2a11d1906c":{
      "scriptId":"u24"},
    "fb2ad48270474a1b89f00dd0b4d8f952":{
      "scriptId":"u25"},
    "096aa9d86fd94b93a309a0850666d099":{
      "scriptId":"u26"},
    "0cc608109b634aa7a7c90c46c96109d0":{
      "scriptId":"u27"},
    "e60da44bcbc7461a811ab4323510743b":{
      "scriptId":"u28"},
    "69a14054eeb74a3aa460b6805cdb59dc":{
      "scriptId":"u29"},
    "ea1a1151a3784840b255885e988bc83b":{
      "scriptId":"u30"},
    "a606349572a847a4a5c0d04e7d4f6d1e":{
      "scriptId":"u31"},
    "1faf14c31af747cbb7378f215adfed61":{
      "scriptId":"u32"},
    "14cd2b78fb8c4210bbcf3cca92023e75":{
      "scriptId":"u33"},
    "34c5511eeddb43b38f9c0563b190443d":{
      "scriptId":"u34"},
    "7e536753463941d5933cda3ff33d921d":{
      "scriptId":"u35"},
    "4b51fb5f266041fa83961bb53434d272":{
      "scriptId":"u36"},
    "b0410889ab584974aedfe07019e3ec10":{
      "scriptId":"u37"},
    "a742f5764c2f430c80e7a08f5f1044fb":{
      "scriptId":"u38"},
    "36db1c4ce6f342bdbfbbe2800537e141":{
      "scriptId":"u39"},
    "4fdbd47387cd4030aab4998f7569193a":{
      "scriptId":"u40"},
    "e7f4381a04604f438e7863378f5f9994":{
      "scriptId":"u41"},
    "b8bc896d55b84e4babf9756b90001e28":{
      "scriptId":"u42"},
    "ab5f82d49b9745839f5931afff1997fe":{
      "scriptId":"u43"},
    "63e6de5dc7c34584b4344cbe8e4068ca":{
      "scriptId":"u44"},
    "3f30bac2d7b54eea88027719133a2124":{
      "scriptId":"u45"},
    "9f2d0e2089eb4e14afec4755ca7f2ad0":{
      "scriptId":"u46"},
    "48992a4ec7b640afbbd124b7792bc716":{
      "scriptId":"u47"},
    "befc3664a5d548c49b3afe74b047a089":{
      "scriptId":"u48"},
    "00a9b89baf8a4a2cb23bacd90a14080e":{
      "scriptId":"u49"},
    "baddd42b21e640579be50ec7c9875cd1":{
      "scriptId":"u50"},
    "1666e7eea8464bc5a73230da3a1120f5":{
      "scriptId":"u51"},
    "34d028dd12d84984bb432039bd61ef5f":{
      "scriptId":"u52"},
    "e938d59104b447c9b835e5b9e38e1105":{
      "scriptId":"u53"},
    "67a9905c708f4a4eb173269157147e6d":{
      "scriptId":"u54"},
    "e7eb8eaf271c43669be1ad643865c555":{
      "scriptId":"u55"},
    "d7fc8fb2d49c449898f74538d22fe058":{
      "scriptId":"u56"},
    "14b3633280b14e78b7d0f1e8471388b7":{
      "scriptId":"u57"},
    "b5bf400fb1b246babfbe876f1768cabb":{
      "scriptId":"u58"},
    "9e602d05691b463880537e0fbf2c919c":{
      "scriptId":"u59"},
    "f04af6d4c0894cd391ccec3bc9da9938":{
      "scriptId":"u60"},
    "b47f908b70b8497bac5766a451c21ea0":{
      "scriptId":"u61"},
    "1bbcaca68ae140e68f80ab3d4c497839":{
      "scriptId":"u62"},
    "23b2f375bc8a45efa83930fcac1be79c":{
      "scriptId":"u63"},
    "2ac52e382e3840b2a0f2fd88eb6fad9c":{
      "scriptId":"u64"},
    "f7e1c5b867ad4e05b029f75de6938fa1":{
      "scriptId":"u65"},
    "2aa845d60df34b038798a3caa1ab3042":{
      "scriptId":"u66"},
    "4897610825cf4187849efd828078c29b":{
      "scriptId":"u67"},
    "33882e80d3124f54bc9d4bbdc5b180dc":{
      "scriptId":"u68"},
    "170282a7285b4152858920fb539add7d":{
      "scriptId":"u69"},
    "99fdf5f844354135b4ac9db5398be60d":{
      "scriptId":"u70"},
    "c3bf0a06b5344494a5162c6bb082fb8d":{
      "scriptId":"u71"},
    "58899dc7e2f0401fb81731638a85e606":{
      "scriptId":"u72"},
    "8933f447ef574549ae6d85ebf695066e":{
      "scriptId":"u73"},
    "049bac56fb7548d68d1cd8fd7bb2c935":{
      "scriptId":"u74"},
    "3dbc8b0de83449409bf65fead528bebf":{
      "scriptId":"u75"},
    "b2ecc239226a4d26aacb3e5e74a1cb0c":{
      "scriptId":"u76"},
    "670ed0b5f4324575a1d59184cc343a42":{
      "scriptId":"u77"},
    "c5d5c4bc7fc74dfc9f321d174ee2e202":{
      "scriptId":"u78"},
    "ef3501a54ee44fcb88a3d373778f7847":{
      "scriptId":"u79"},
    "be31411a997348e696284e6e131451be":{
      "scriptId":"u80"},
    "f7aff747e021419b9def19a2954ee2c2":{
      "scriptId":"u81"},
    "d26cd0fc98464168bcacf8e30b6fe267":{
      "scriptId":"u82"},
    "1ae1af720e2d4a1c84f88584938920b0":{
      "scriptId":"u83"},
    "1e5287a396e84cc39770662725d64d44":{
      "scriptId":"u84"},
    "347489dae815460fb16cb7e744c64ceb":{
      "scriptId":"u85"},
    "d6586596d83848d5b8ebe741509c7d93":{
      "scriptId":"u86"},
    "2187b1f7c7ed4572997fa1ae1261cf55":{
      "scriptId":"u87"},
    "14e654d19b5f4a1a89b325c25b95f675":{
      "scriptId":"u88"},
    "d3f8c9d3aaa04636ba96345e63a7ddf0":{
      "scriptId":"u89"}}});