$axure.loadCurrentPage({
  "url":"_____wi-fi_portal_.html",
  "generationDate":new Date(1397643459609.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"256a9835d89e43d6b9135ce775e8e092",
    "type":"Axure:Page",
    "name":"最终方案：Wi-Fi Portal页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"603664463f034668b21daceaee2bb697",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1160,
              "y":93},
            "size":{
              "width":287,
              "height":474}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91567603475f4629a78c48192eeb6050",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1160,
                  "y":93},
                "size":{
                  "width":287,
                  "height":474}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u0.png"}},
{
          "id":"beb9e64e381b4a0a8f7024f05c7f9626",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000066},
            "location":{
              "x":1163,
              "y":116},
            "size":{
              "width":280,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b10431d6e90c4a85a9eb608b47250964",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000066},
                "location":{
                  "x":1163,
                  "y":116},
                "size":{
                  "width":280,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u2.png"}},
{
          "id":"9dd8637a6df0496581a1906b0bb96f67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":1176,
              "y":157},
            "size":{
              "width":254,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b571c190ef06447c90b3279617aa9b7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":1176,
                  "y":157},
                "size":{
                  "width":254,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b183ff77491042a9afaeea97905c0edc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"0px",
            "location":{
              "x":1176,
              "y":197},
            "size":{
              "width":254,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d1a65b0395b4957a561d8d00da5a3f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"0px",
                "location":{
                  "x":1176,
                  "y":197},
                "size":{
                  "width":254,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6be129443f44be99ef1370b62d39f45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":93},
            "size":{
              "width":287,
              "height":474}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb02a69361fe4cf58ad27a38437f9263",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":93},
                "size":{
                  "width":287,
                  "height":474}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u0.png"}},
{
          "id":"99d60e55858e4aaab7ea092eb79fa22b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "lineSpacing":"28px",
            "location":{
              "x":40,
              "y":156},
            "size":{
              "width":287,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dddd5e6462b24770b9d8f487809b274b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "lineSpacing":"28px",
                "location":{
                  "x":40,
                  "y":156},
                "size":{
                  "width":287,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fc8e287a3cb470bafdf9e1f88cec94e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":213},
            "size":{
              "width":120,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d628de09c79147ee9eab2850c1d2e8b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":213},
                "size":{
                  "width":120,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u12.jpg"}},
{
          "id":"9fa594d7e90742faabdd9526fbdd523a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006666,
              "opacity":1},
            "location":{
              "x":57,
              "y":333},
            "size":{
              "width":250,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efdaccd487744cffa29398d1c6323167",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006666,
                  "opacity":1},
                "location":{
                  "x":57,
                  "y":333},
                "size":{
                  "width":250,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6a9b3762f19447ba95d8622462135a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":367},
            "size":{
              "width":250,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"580b090d2fc24089af6a5bc8ce8a5bf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":57,
                  "y":367},
                "size":{
                  "width":250,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce8308ae0fba4d78b6523f65e088574a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000066},
            "location":{
              "x":43,
              "y":116},
            "size":{
              "width":280,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"439b2059a9674c23b089b72378c6416f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000066},
                "location":{
                  "x":43,
                  "y":116},
                "size":{
                  "width":280,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u2.png"}},
{
          "id":"82b6cfb3e25f40eca7c8cfafea8c368f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":353},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"091f796896e04157bc3552c786a4f7bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":353},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00FF00}},
              "adaptiveStyles":{
}}]},
{
          "id":"a1ad7db4d7694dbe98b1ee2b8adc2b39",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":799,
              "y":93},
            "size":{
              "width":287,
              "height":474}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ec7690ece124f459de99612519682e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":799,
                  "y":93},
                "size":{
                  "width":287,
                  "height":474}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u0.png"}},
{
          "id":"4547d17b50324d79990a485082ee543f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000066},
            "location":{
              "x":802,
              "y":116},
            "size":{
              "width":280,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"736e7cc2fa3845308d1bffafb4bccd7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000066},
                "location":{
                  "x":802,
                  "y":116},
                "size":{
                  "width":280,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u2.png"}},
{
          "id":"25580c6d9594408fac36fd4866d8c813",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":816,
              "y":449},
            "size":{
              "width":254,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009999},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"877b72e195da4beda7299e225e8454d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":816,
                  "y":449},
                "size":{
                  "width":254,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u26.png"}},
{
          "id":"3f1a4b241d89425ca61b66945bf1da33",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":816,
              "y":424},
            "size":{
              "width":254,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e220f71f39984aefbf269ab2496c1bfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":816,
                  "y":424},
                "size":{
                  "width":254,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"ebb209367bbb4e6ba09c1f9431281512",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":815,
              "y":533},
            "size":{
              "width":254,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0c6509db6984b768d5daf64b6726c3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":815,
                  "y":533},
                "size":{
                  "width":254,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"889e04c996e74131b1e4d8b0b7647127",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":802,
              "y":521},
            "size":{
              "width":280,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/_____wi-fi_portal_/u32_line.png"}},
{
          "id":"e7f140239e2f40b5912e1cdbea739440",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":165},
            "size":{
              "width":142,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23a352c2378d4f45ad2e61605237d766",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":840,
                  "y":165},
                "size":{
                  "width":142,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u33.png"}},
{
          "id":"fa8cb1b5ae9942c495c2705e29f50ad4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":992,
              "y":163},
            "size":{
              "width":50,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02bec6e3905a4b49b6da9128b4c0d278",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":992,
                  "y":163},
                "size":{
                  "width":50,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u35.png"}},
{
          "id":"798418eaa2cf4e8a94e510074321e253",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":89},
            "size":{
              "width":287,
              "height":474}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8dfe2bfb0ce4070b6984c58a17a22fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":89},
                "size":{
                  "width":287,
                  "height":474}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u0.png"}},
{
          "id":"871da1649d6d47058ed391ce8936fe17",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000066},
            "location":{
              "x":413,
              "y":112},
            "size":{
              "width":280,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da07ada3c5654fb3b88db2a81e42f6cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000066},
                "location":{
                  "x":413,
                  "y":112},
                "size":{
                  "width":280,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u2.png"}},
{
          "id":"34f8ef881688451daa7d1802e7b4d821",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":467,
              "y":239},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"c412a98cb4664d02b83eab900023952e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "location":{
              "x":427,
              "y":289},
            "size":{
              "width":254,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1868d518d4d0470bb168fae7f7b9d7e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "location":{
                  "x":427,
                  "y":289},
                "size":{
                  "width":254,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u42.png"}},
{
          "id":"385d94591fb947fdb7f62700143aabdf",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":467,
              "y":339},
            "size":{
              "width":214,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"ff23deeb426d4b68b69b6e8f3e07950b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":427,
              "y":414},
            "size":{
              "width":254,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009999},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab12da660d0a4b81949645197cb32541",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":427,
                  "y":414},
                "size":{
                  "width":254,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u26.png"}},
{
          "id":"5c7a0a98d07645b185764d849f0f2177",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":427,
              "y":389},
            "size":{
              "width":254,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5ce5b30d78048adbd4390815fe0ebdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":427,
                  "y":389},
                "size":{
                  "width":254,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"6ed74cbf5dea48ff9e10f982c22eabde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":426,
              "y":529},
            "size":{
              "width":254,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"687449f439d1439c8d43075709967962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":426,
                  "y":529},
                "size":{
                  "width":254,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a2e4b5339b0482d97027ff1f5ac2e8a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":413,
              "y":517},
            "size":{
              "width":280,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/_____wi-fi_portal_/u32_line.png"}},
{
          "id":"bccf99ce3b9f47b288a3625b43ea2181",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":427,
              "y":239},
            "size":{
              "width":40,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5acfadcf9d0946fa8e75bbce09a441ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":427,
                  "y":239},
                "size":{
                  "width":40,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u52.png"}},
{
          "id":"ffc17172973a42fb8e677ab7b48f96c8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":437,
              "y":249},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25290d1cffb544a696c601c71271c420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":437,
                  "y":249},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u54.png"}},
{
          "id":"94c17319432148129cb0a4526ba7dff3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":451,
              "y":161},
            "size":{
              "width":142,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38f9b087b9564122ad8de5bfa94877fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":451,
                  "y":161},
                "size":{
                  "width":142,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u33.png"}},
{
          "id":"bdafaea436294341a7a69ec93686745b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":603,
              "y":159},
            "size":{
              "width":50,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e360e3c9d1784f51968cc03d0c20391d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":603,
                  "y":159},
                "size":{
                  "width":50,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u35.png"}},
{
          "id":"66922bc455a3483eb5520e855b5e48d8",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":838,
              "y":62},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22e95481e417435cb8068d8e8608459e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":838,
                  "y":62},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00FF00}},
              "adaptiveStyles":{
}}]},
{
          "id":"2a215ebfcbbd40f0b959cccbdc0ab49d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":427,
              "y":339},
            "size":{
              "width":40,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aed545319624f9ab2c5bbc2af49d805",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":427,
                  "y":339},
                "size":{
                  "width":40,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u52.png"}},
{
          "id":"693ef534fdf54bad9eaa04eb6d2ee2e2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":438,
              "y":349},
            "size":{
              "width":18,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e7ffe4c788b4feaad94c6f1bf10daec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":438,
                  "y":349},
                "size":{
                  "width":18,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u64.png"}},
{
          "id":"93f7ca9ca04246fbbb6d846fa12339d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":815,
              "y":223},
            "size":{
              "width":255,
              "height":191}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc8257e582a6497695a39704bfdb7c83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":815,
                  "y":223},
                "size":{
                  "width":255,
                  "height":191}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_____wi-fi_portal_/u66.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "603664463f034668b21daceaee2bb697":{
      "scriptId":"u0"},
    "91567603475f4629a78c48192eeb6050":{
      "scriptId":"u1"},
    "beb9e64e381b4a0a8f7024f05c7f9626":{
      "scriptId":"u2"},
    "b10431d6e90c4a85a9eb608b47250964":{
      "scriptId":"u3"},
    "9dd8637a6df0496581a1906b0bb96f67":{
      "scriptId":"u4"},
    "b571c190ef06447c90b3279617aa9b7a":{
      "scriptId":"u5"},
    "b183ff77491042a9afaeea97905c0edc":{
      "scriptId":"u6"},
    "9d1a65b0395b4957a561d8d00da5a3f5":{
      "scriptId":"u7"},
    "a6be129443f44be99ef1370b62d39f45":{
      "scriptId":"u8"},
    "eb02a69361fe4cf58ad27a38437f9263":{
      "scriptId":"u9"},
    "99d60e55858e4aaab7ea092eb79fa22b":{
      "scriptId":"u10"},
    "dddd5e6462b24770b9d8f487809b274b":{
      "scriptId":"u11"},
    "6fc8e287a3cb470bafdf9e1f88cec94e":{
      "scriptId":"u12"},
    "d628de09c79147ee9eab2850c1d2e8b8":{
      "scriptId":"u13"},
    "9fa594d7e90742faabdd9526fbdd523a":{
      "scriptId":"u14"},
    "efdaccd487744cffa29398d1c6323167":{
      "scriptId":"u15"},
    "c6a9b3762f19447ba95d8622462135a2":{
      "scriptId":"u16"},
    "580b090d2fc24089af6a5bc8ce8a5bf1":{
      "scriptId":"u17"},
    "ce8308ae0fba4d78b6523f65e088574a":{
      "scriptId":"u18"},
    "439b2059a9674c23b089b72378c6416f":{
      "scriptId":"u19"},
    "82b6cfb3e25f40eca7c8cfafea8c368f":{
      "scriptId":"u20"},
    "091f796896e04157bc3552c786a4f7bf":{
      "scriptId":"u21"},
    "a1ad7db4d7694dbe98b1ee2b8adc2b39":{
      "scriptId":"u22"},
    "4ec7690ece124f459de99612519682e6":{
      "scriptId":"u23"},
    "4547d17b50324d79990a485082ee543f":{
      "scriptId":"u24"},
    "736e7cc2fa3845308d1bffafb4bccd7f":{
      "scriptId":"u25"},
    "25580c6d9594408fac36fd4866d8c813":{
      "scriptId":"u26"},
    "877b72e195da4beda7299e225e8454d5":{
      "scriptId":"u27"},
    "3f1a4b241d89425ca61b66945bf1da33":{
      "scriptId":"u28"},
    "e220f71f39984aefbf269ab2496c1bfa":{
      "scriptId":"u29"},
    "ebb209367bbb4e6ba09c1f9431281512":{
      "scriptId":"u30"},
    "c0c6509db6984b768d5daf64b6726c3e":{
      "scriptId":"u31"},
    "889e04c996e74131b1e4d8b0b7647127":{
      "scriptId":"u32"},
    "e7f140239e2f40b5912e1cdbea739440":{
      "scriptId":"u33"},
    "23a352c2378d4f45ad2e61605237d766":{
      "scriptId":"u34"},
    "fa8cb1b5ae9942c495c2705e29f50ad4":{
      "scriptId":"u35"},
    "02bec6e3905a4b49b6da9128b4c0d278":{
      "scriptId":"u36"},
    "798418eaa2cf4e8a94e510074321e253":{
      "scriptId":"u37"},
    "d8dfe2bfb0ce4070b6984c58a17a22fc":{
      "scriptId":"u38"},
    "871da1649d6d47058ed391ce8936fe17":{
      "scriptId":"u39"},
    "da07ada3c5654fb3b88db2a81e42f6cb":{
      "scriptId":"u40"},
    "34f8ef881688451daa7d1802e7b4d821":{
      "scriptId":"u41"},
    "c412a98cb4664d02b83eab900023952e":{
      "scriptId":"u42"},
    "1868d518d4d0470bb168fae7f7b9d7e5":{
      "scriptId":"u43"},
    "385d94591fb947fdb7f62700143aabdf":{
      "scriptId":"u44"},
    "ff23deeb426d4b68b69b6e8f3e07950b":{
      "scriptId":"u45"},
    "ab12da660d0a4b81949645197cb32541":{
      "scriptId":"u46"},
    "5c7a0a98d07645b185764d849f0f2177":{
      "scriptId":"u47"},
    "b5ce5b30d78048adbd4390815fe0ebdb":{
      "scriptId":"u48"},
    "6ed74cbf5dea48ff9e10f982c22eabde":{
      "scriptId":"u49"},
    "687449f439d1439c8d43075709967962":{
      "scriptId":"u50"},
    "0a2e4b5339b0482d97027ff1f5ac2e8a":{
      "scriptId":"u51"},
    "bccf99ce3b9f47b288a3625b43ea2181":{
      "scriptId":"u52"},
    "5acfadcf9d0946fa8e75bbce09a441ea":{
      "scriptId":"u53"},
    "ffc17172973a42fb8e677ab7b48f96c8":{
      "scriptId":"u54"},
    "25290d1cffb544a696c601c71271c420":{
      "scriptId":"u55"},
    "94c17319432148129cb0a4526ba7dff3":{
      "scriptId":"u56"},
    "38f9b087b9564122ad8de5bfa94877fd":{
      "scriptId":"u57"},
    "bdafaea436294341a7a69ec93686745b":{
      "scriptId":"u58"},
    "e360e3c9d1784f51968cc03d0c20391d":{
      "scriptId":"u59"},
    "66922bc455a3483eb5520e855b5e48d8":{
      "scriptId":"u60"},
    "22e95481e417435cb8068d8e8608459e":{
      "scriptId":"u61"},
    "2a215ebfcbbd40f0b959cccbdc0ab49d":{
      "scriptId":"u62"},
    "7aed545319624f9ab2c5bbc2af49d805":{
      "scriptId":"u63"},
    "693ef534fdf54bad9eaa04eb6d2ee2e2":{
      "scriptId":"u64"},
    "7e7ffe4c788b4feaad94c6f1bf10daec":{
      "scriptId":"u65"},
    "93f7ca9ca04246fbbb6d846fa12339d7":{
      "scriptId":"u66"},
    "cc8257e582a6497695a39704bfdb7c83":{
      "scriptId":"u67"}}});