$axure.loadCurrentPage({
  "url":"我的活动.html",
  "generationDate":new Date(1404457234503.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"53621444950d4584a72a48a79f43f8f5",
    "type":"Axure:Page",
    "name":"我的活动",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9f8f8611f26340c2b43b8d0ea5452f24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"36px",
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":208,
              "y":610},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eab06a5111e84d2380981df380c43981",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"36px",
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":208,
                  "y":610},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37afffa5c4c64c94beec527f97e2f40a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":390,
              "y":80},
            "size":{
              "width":320,
              "height":540},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"754b2a722f1b437b820071e21fdcc55f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":390,
                  "y":80},
                "size":{
                  "width":320,
                  "height":540},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的活动/u2.png"}},
{
          "id":"a1e76f79c3a64174b77d059f06c6233d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":390,
              "y":80},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed556a9b8c544d27a6616b0134a4a2b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":390,
                  "y":80},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u8.png"}},
{
          "id":"9436ca2d46b04836847a3b118fb0ff6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":420,
              "y":86},
            "size":{
              "width":29,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68da7693fd6249cab031b2d1f45302b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":420,
                  "y":86},
                "size":{
                  "width":29,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70138184e80346a4852ba687a68ffb97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":459,
              "y":92},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5844a4b1181543218c73c82d9233530b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":459,
                  "y":92},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b34da5236874187b4034408fce46c94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":396,
              "y":204},
            "size":{
              "width":300,
              "height":196}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ecc62f04ff945aca6557a6f17668895",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":396,
                  "y":204},
                "size":{
                  "width":300,
                  "height":196}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找美食/u320.png"}},
{
          "id":"ad414f7efbdf4b7a9d1f7ed4bdb6cc5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":396,
              "y":204},
            "size":{
              "width":300,
              "height":80},
            "cornerRadiusTopLeft":"8",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":1,
              "blurRadius":0,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbeb55ecf58745e7b9e0e6cc1c15d924",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":396,
                  "y":204},
                "size":{
                  "width":300,
                  "height":80},
                "cornerRadiusTopLeft":"8",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":1,
                  "blurRadius":0,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找品牌/u254.png"}},
{
          "id":"b7c6f24bf63348fa9b42decdca16a568",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":466,
              "y":300},
            "size":{
              "width":214,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8844bbc820f46e1821456252b54c58f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":466,
                  "y":300},
                "size":{
                  "width":214,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25d66c79f6ab45989dbaf76578f01a44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"48px",
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":408,
              "y":292},
            "size":{
              "width":49,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"086a3d0aa21c4d81989f5cb475e362c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"48px",
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":408,
                  "y":292},
                "size":{
                  "width":49,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c77072ca391d460a829694502656ee5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":416,
              "y":307},
            "size":{
              "width":40,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c36a652c8f243938eb01e14c645686f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":416,
                  "y":307},
                "size":{
                  "width":40,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b124a75c0a964d23b2b59a81220ee8b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":424,
              "y":351},
            "size":{
              "width":280,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fabb5408c754202a0f1570ad6cc132a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":424,
                  "y":351},
                "size":{
                  "width":280,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"467b472d9414421f8465d5a1f64c9a20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":410,
              "y":374},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bce9240ef65b40be96494fb7527e48d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":410,
                  "y":374},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8c153a95f7f4ac9ac5a9ba010c00743",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":424,
              "y":374},
            "size":{
              "width":120,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b45573e06eac42c3aaf23a7cbfbf89c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":424,
                  "y":374},
                "size":{
                  "width":120,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e8a44f87bf246d8b0179ff833b6f121",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":408,
              "y":351},
            "size":{
              "width":15,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff5beba1b3304eb39da1338a9bb8f925",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":408,
                  "y":351},
                "size":{
                  "width":15,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c722239e861047f292c8f0cbcdee5b5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":398,
              "y":124},
            "size":{
              "width":300,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c448fc12bfb14f55a2317e4538bdb16a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":398,
                  "y":124},
                "size":{
                  "width":300,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8c796501512404384eed3dc8262e450",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":184},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/找美食/u21_line.png"}},
{
          "id":"eca2bddb762349b08ed4d999ef7c3bd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":396,
              "y":410},
            "size":{
              "width":300,
              "height":196}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41de6783a96a4db1ad292467d465ed87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":396,
                  "y":410},
                "size":{
                  "width":300,
                  "height":196}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找美食/u320.png"}},
{
          "id":"69dfbe6666a34abf9810ee68c5db08d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":396,
              "y":410},
            "size":{
              "width":300,
              "height":80},
            "cornerRadiusTopLeft":"8",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":1,
              "blurRadius":0,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53f22fcff07d41919171650a5fd3493c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":396,
                  "y":410},
                "size":{
                  "width":300,
                  "height":80},
                "cornerRadiusTopLeft":"8",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":1,
                  "blurRadius":0,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找品牌/u254.png"}},
{
          "id":"9af1a35b9fcf4abdb79c4d554ea99931",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":466,
              "y":506},
            "size":{
              "width":214,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ec811de9f084bc8b74b9bb66f8c0eb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":466,
                  "y":506},
                "size":{
                  "width":214,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10a7adc5455e4ba08f92a19b8cffd8f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"48px",
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":408,
              "y":498},
            "size":{
              "width":49,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dca63b4a73949988a5da0625fcb7cdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"48px",
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":408,
                  "y":498},
                "size":{
                  "width":49,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"410b35fd98f54d2c9672bbe93c4d2d62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":416,
              "y":513},
            "size":{
              "width":40,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aeefbed045c4a9883d76704ef376e46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":416,
                  "y":513},
                "size":{
                  "width":40,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28c956632c4241a98f58790d72cd1c02",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":424,
              "y":557},
            "size":{
              "width":280,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb1ba2fd38a54c48b9c50b86513c50b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":424,
                  "y":557},
                "size":{
                  "width":280,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"643690f73d7046688e53396f544b9a7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":410,
              "y":580},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c187ef209fd41d2ac0ef32eab6b4255",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":410,
                  "y":580},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d9f26adbddc4154b09d0fb950031458",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":424,
              "y":580},
            "size":{
              "width":120,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5605aaf872141bdb43c5207c0300fe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":424,
                  "y":580},
                "size":{
                  "width":120,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8ad0a13a7264e828fb38d1e75e02d86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":408,
              "y":557},
            "size":{
              "width":15,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d411f5062e4f4c5da6389c74e5780e9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":408,
                  "y":557},
                "size":{
                  "width":15,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ff1235ef0444dd38c7cd4c70d3e5ec7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":22.5,
              "y":21.25},
            "size":{
              "width":320,
              "height":480},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a778152c18624849ab713b751b4b9ccf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22.5,
                  "y":21.25},
                "size":{
                  "width":320,
                  "height":480},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u28.png"}},
{
          "id":"cbd61ccc447a451fb07b8cb401040bde",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":22,
              "y":21},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7e160752d06441ca7fb2d2aab99da05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":22,
                  "y":21},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u8.png"}},
{
          "id":"6765341aae524171a6946ddbbeb8e93f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":52,
              "y":27},
            "size":{
              "width":29,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad90d7128feb452794eb40498ed2b92e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":52,
                  "y":27},
                "size":{
                  "width":29,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b588dec41f764a68951236d75569692a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":92,
              "y":33},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d48a128cba8e4513a7f85ca8051bc43c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":33},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"374cef02a0b2420a8179c24c89a04c3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "paddingTop":"8",
            "paddingBottom":"8",
            "location":{
              "x":32.5,
              "y":221.25},
            "size":{
              "width":300,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1815472dd6f54120bebcf44d27ae401f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "paddingTop":"8",
                "paddingBottom":"8",
                "location":{
                  "x":32.5,
                  "y":221.25},
                "size":{
                  "width":300,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/参加活动/u178.png"}},
{
          "id":"16300da142c1404da7b78a020baabb7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":32.5,
              "y":95.25},
            "size":{
              "width":300,
              "height":126},
            "cornerRadiusTopLeft":"8",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":1,
              "blurRadius":0,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ee83441104140c0ac3f104fbdc7ed07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":32.5,
                  "y":95.25},
                "size":{
                  "width":300,
                  "height":126},
                "cornerRadiusTopLeft":"8",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":1,
                  "blurRadius":0,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的活动/u59.png"}},
{
          "id":"29085c33b4534467b554098f2c3877bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x7F000000},
            "paddingTop":"8",
            "paddingBottom":"8",
            "location":{
              "x":32.5,
              "y":181.25},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b12bfe2e85104ac8b90a4256672e6e16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x7F000000},
                "paddingTop":"8",
                "paddingBottom":"8",
                "location":{
                  "x":32.5,
                  "y":181.25},
                "size":{
                  "width":300,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/参加活动/u182.png"}},
{
          "id":"491c652043244f6993e264bbe7e2b1c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":267.5,
              "y":231.25},
            "size":{
              "width":55,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f1ec3d4dc114d22964fba71612bb5b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":267.5,
                  "y":231.25},
                "size":{
                  "width":55,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的活动/u63.png"}},
{
          "id":"4b9a95dec2034c13a04ddf1d23b4c51f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":69.5,
              "y":461.25},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"501a99e52f6c4486b78a1058bd61f2f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":69.5,
                  "y":461.25},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u2.png"}},
{
          "id":"adecd6de8fbc49fc85d0a7982dd4d8f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":160.5,
              "y":461.25},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ae661eef62c4ff7bdb1328292038c6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":160.5,
                  "y":461.25},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u2.png"}},
{
          "id":"ca9984f6cc4e4faea629f369a20995d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":250.5,
              "y":461.25},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11e391e807fb4c8db7da97737c4292b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":250.5,
                  "y":461.25},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u2.png"}},
{
          "id":"3310d1741e4f49ccb1512275df9780c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":22.5,
              "y":461.25},
            "size":{
              "width":48,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea3a7fcc06964fc9bcd9f4a9d16689de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":22.5,
                  "y":461.25},
                "size":{
                  "width":48,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u14.png"}},
{
          "id":"a85a78cbebd24144a4508ff5f30b2762",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "paddingTop":"8",
            "paddingBottom":"8",
            "location":{
              "x":32.5,
              "y":290.25},
            "size":{
              "width":300,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d24fc22c3954411498cbfcb40a8aff96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "paddingTop":"8",
                "paddingBottom":"8",
                "location":{
                  "x":32.5,
                  "y":290.25},
                "size":{
                  "width":300,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/参加活动/u178.png"}},
{
          "id":"86fbaa26cd274c749cecb970414cabf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":267.5,
              "y":300.25},
            "size":{
              "width":55,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7cdea4bc82247b48d863a1b31275ee3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":267.5,
                  "y":300.25},
                "size":{
                  "width":55,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的活动/u63.png"}},
{
          "id":"f7bbeae5359e41da87797f7c6df5de26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "paddingTop":"8",
            "paddingBottom":"8",
            "location":{
              "x":32.5,
              "y":359.25},
            "size":{
              "width":300,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af0873310e164dcf8271a1a9ba03cdfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "paddingTop":"8",
                "paddingBottom":"8",
                "location":{
                  "x":32.5,
                  "y":359.25},
                "size":{
                  "width":300,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的活动/u77.png"}},
{
          "id":"b24adb56e1b644d89c7e9f677c7f9d81",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":250,
              "y":421},
            "size":{
              "width":92,
              "height":40},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea73f73197554ffb9345085cfb78dc5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":250,
                  "y":421},
                "size":{
                  "width":92,
                  "height":40},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u26.png"}},
{
          "id":"af88e8f0d9ae4d3487840f71ded1dbbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":35,
              "y":520},
            "size":{
              "width":294,
              "height":156}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"556fce79cdd44bdba4913d91dc70a0fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":520},
                "size":{
                  "width":294,
                  "height":156}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c38ea100c344fadb5b5e849ac5736ab",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":380},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"273e3d23f9f046c7a66177ee300774b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":380},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"548bcb466d6247b383b4e6949cf3f0ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":32,
              "y":686},
            "size":{
              "width":320,
              "height":480},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7db01d861c18453696bdc9593d8bfebf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":32,
                  "y":686},
                "size":{
                  "width":320,
                  "height":480},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u0.png"}},
{
          "id":"90c5cf03aca34414ab6123d723125e08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "horizontalAlignment":"left",
            "paddingTop":"8",
            "paddingBottom":"0",
            "location":{
              "x":42,
              "y":820},
            "size":{
              "width":300,
              "height":236},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c950c1467c045d6a7d06063df930507",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "horizontalAlignment":"left",
                "paddingTop":"8",
                "paddingBottom":"0",
                "location":{
                  "x":42,
                  "y":820},
                "size":{
                  "width":300,
                  "height":236},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的活动/u87.png"}},
{
          "id":"41e4be635ca14704a66c612e1f0db1e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":260,
              "y":1086},
            "size":{
              "width":93,
              "height":40},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a94e62275e94ad3a4922d3e6fb74c70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":260,
                  "y":1086},
                "size":{
                  "width":93,
                  "height":40},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u30.png"}},
{
          "id":"c72005ab964d47a09d45251ca5f81b26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":32,
              "y":686},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f94d3329d5d64767a62045bbf6d4e7cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":32,
                  "y":686},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u8.png"}},
{
          "id":"d285af7c44c54d09bd0f0312c63dc599",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":62,
              "y":692},
            "size":{
              "width":29,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0e16bc9e88c4b0f98eb4ecd34756461",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":62,
                  "y":692},
                "size":{
                  "width":29,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62a7d43a89704511b0f2c338fca5b47c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":101,
              "y":698},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f458e7a21fb741d19cc576cbc41b7c88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":101,
                  "y":698},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f9a4e375592408995cc4127394d07de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":78,
              "y":1126},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68e7e0d4cc1b4bb9a893590e449acfb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":78,
                  "y":1126},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u2.png"}},
{
          "id":"18ac01664d8d4b379b2e663b3f5f46a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":170,
              "y":1126},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc5ac96598df439cb5474892b4423f4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":170,
                  "y":1126},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u2.png"}},
{
          "id":"b3493207e81e49e0834c1eec92e7be1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":260,
              "y":1126},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51ec575eb3834baab9625170a1ef9305",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":260,
                  "y":1126},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u2.png"}},
{
          "id":"30bd851487504bbd9b9f6cecdd8fee5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":32,
              "y":1126},
            "size":{
              "width":48,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcfe1c4d14394d64b7cec9733c29479b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":32,
                  "y":1126},
                "size":{
                  "width":48,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u14.png"}},
{
          "id":"4e58001c84f0484da5390a7741f61a42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":260,
              "y":1086},
            "size":{
              "width":93,
              "height":40},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fcf478761c54c95a8e7aa5e350d3fd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":260,
                  "y":1086},
                "size":{
                  "width":93,
                  "height":40},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u30.png"}},
{
          "id":"29cb59c4deb4402fab50144dc1159eb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "paddingTop":"5",
            "paddingBottom":"5",
            "location":{
              "x":592,
              "y":133},
            "size":{
              "width":104,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb593eb2831448d080e8c03728aff727",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "paddingTop":"5",
                "paddingBottom":"5",
                "location":{
                  "x":592,
                  "y":133},
                "size":{
                  "width":104,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的会员卡/u104.png"}},
{
          "id":"a68c6f9557aa4d3a9387fc6ef94db0ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "paddingTop":"5",
            "paddingBottom":"5",
            "location":{
              "x":592,
              "y":173},
            "size":{
              "width":104,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1abcc63c33c45b7aa4c9db7bddf4c03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "paddingTop":"5",
                "paddingBottom":"5",
                "location":{
                  "x":592,
                  "y":173},
                "size":{
                  "width":104,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的会员卡/u104.png"}},
{
          "id":"2019283ac12f41e391ab89c1dc745695",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":780,
              "y":80},
            "size":{
              "width":320,
              "height":540},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d41b74256e1f48d091184d91df7b1c61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":780,
                  "y":80},
                "size":{
                  "width":320,
                  "height":540},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的活动/u2.png"}},
{
          "id":"78a7d72af9e64f2cb02165f758fd66af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":780,
              "y":80},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38b7fd70c7ee436db9a15cb5dc019cb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":780,
                  "y":80},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u8.png"}},
{
          "id":"79bc2b12b15341d6aff08367ea14d755",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":810,
              "y":86},
            "size":{
              "width":29,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8119a54c93e242c79f94dcef54f39685",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":810,
                  "y":86},
                "size":{
                  "width":29,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e293bb85652d426a8aacb2e576fb23bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":849,
              "y":92},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99d02b45572e4a2fab96a0a1b3c35e74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":849,
                  "y":92},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e6d3e33816a4255aee201add3275289",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":780,
              "y":120},
            "size":{
              "width":320,
              "height":64},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3583e1c6959c419e9c0dcde1a1d67480",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":780,
                  "y":120},
                "size":{
                  "width":320,
                  "height":64},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的活动/u119.png"}},
{
          "id":"c0b35f563fa640ea8965fa7cde5ac1e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":848,
              "y":312},
            "size":{
              "width":201,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21ab5d87dd02423ba69b12ddb96b9fc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":848,
                  "y":312},
                "size":{
                  "width":201,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b1d6044f1b34d0a865110bb0a0cc77d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":852,
              "y":360},
            "size":{
              "width":172,
              "height":40},
            "cornerRadiusTopLeft":"44"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40aa09cffa344a3899b575cd0d8e6080",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":852,
                  "y":360},
                "size":{
                  "width":172,
                  "height":40},
                "cornerRadiusTopLeft":"44"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的活动/u123.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9f8f8611f26340c2b43b8d0ea5452f24":{
      "scriptId":"u0"},
    "eab06a5111e84d2380981df380c43981":{
      "scriptId":"u1"},
    "37afffa5c4c64c94beec527f97e2f40a":{
      "scriptId":"u2"},
    "754b2a722f1b437b820071e21fdcc55f":{
      "scriptId":"u3"},
    "a1e76f79c3a64174b77d059f06c6233d":{
      "scriptId":"u4"},
    "ed556a9b8c544d27a6616b0134a4a2b6":{
      "scriptId":"u5"},
    "9436ca2d46b04836847a3b118fb0ff6a":{
      "scriptId":"u6"},
    "68da7693fd6249cab031b2d1f45302b2":{
      "scriptId":"u7"},
    "70138184e80346a4852ba687a68ffb97":{
      "scriptId":"u8"},
    "5844a4b1181543218c73c82d9233530b":{
      "scriptId":"u9"},
    "6b34da5236874187b4034408fce46c94":{
      "scriptId":"u10"},
    "4ecc62f04ff945aca6557a6f17668895":{
      "scriptId":"u11"},
    "ad414f7efbdf4b7a9d1f7ed4bdb6cc5d":{
      "scriptId":"u12"},
    "bbeb55ecf58745e7b9e0e6cc1c15d924":{
      "scriptId":"u13"},
    "b7c6f24bf63348fa9b42decdca16a568":{
      "scriptId":"u14"},
    "c8844bbc820f46e1821456252b54c58f":{
      "scriptId":"u15"},
    "25d66c79f6ab45989dbaf76578f01a44":{
      "scriptId":"u16"},
    "086a3d0aa21c4d81989f5cb475e362c2":{
      "scriptId":"u17"},
    "c77072ca391d460a829694502656ee5e":{
      "scriptId":"u18"},
    "9c36a652c8f243938eb01e14c645686f":{
      "scriptId":"u19"},
    "b124a75c0a964d23b2b59a81220ee8b1":{
      "scriptId":"u20"},
    "3fabb5408c754202a0f1570ad6cc132a":{
      "scriptId":"u21"},
    "467b472d9414421f8465d5a1f64c9a20":{
      "scriptId":"u22"},
    "bce9240ef65b40be96494fb7527e48d1":{
      "scriptId":"u23"},
    "a8c153a95f7f4ac9ac5a9ba010c00743":{
      "scriptId":"u24"},
    "b45573e06eac42c3aaf23a7cbfbf89c1":{
      "scriptId":"u25"},
    "4e8a44f87bf246d8b0179ff833b6f121":{
      "scriptId":"u26"},
    "ff5beba1b3304eb39da1338a9bb8f925":{
      "scriptId":"u27"},
    "c722239e861047f292c8f0cbcdee5b5f":{
      "scriptId":"u28"},
    "c448fc12bfb14f55a2317e4538bdb16a":{
      "scriptId":"u29"},
    "e8c796501512404384eed3dc8262e450":{
      "scriptId":"u30"},
    "eca2bddb762349b08ed4d999ef7c3bd2":{
      "scriptId":"u31"},
    "41de6783a96a4db1ad292467d465ed87":{
      "scriptId":"u32"},
    "69dfbe6666a34abf9810ee68c5db08d4":{
      "scriptId":"u33"},
    "53f22fcff07d41919171650a5fd3493c":{
      "scriptId":"u34"},
    "9af1a35b9fcf4abdb79c4d554ea99931":{
      "scriptId":"u35"},
    "6ec811de9f084bc8b74b9bb66f8c0eb9":{
      "scriptId":"u36"},
    "10a7adc5455e4ba08f92a19b8cffd8f9":{
      "scriptId":"u37"},
    "0dca63b4a73949988a5da0625fcb7cdd":{
      "scriptId":"u38"},
    "410b35fd98f54d2c9672bbe93c4d2d62":{
      "scriptId":"u39"},
    "6aeefbed045c4a9883d76704ef376e46":{
      "scriptId":"u40"},
    "28c956632c4241a98f58790d72cd1c02":{
      "scriptId":"u41"},
    "fb1ba2fd38a54c48b9c50b86513c50b7":{
      "scriptId":"u42"},
    "643690f73d7046688e53396f544b9a7d":{
      "scriptId":"u43"},
    "0c187ef209fd41d2ac0ef32eab6b4255":{
      "scriptId":"u44"},
    "9d9f26adbddc4154b09d0fb950031458":{
      "scriptId":"u45"},
    "b5605aaf872141bdb43c5207c0300fe9":{
      "scriptId":"u46"},
    "b8ad0a13a7264e828fb38d1e75e02d86":{
      "scriptId":"u47"},
    "d411f5062e4f4c5da6389c74e5780e9d":{
      "scriptId":"u48"},
    "5ff1235ef0444dd38c7cd4c70d3e5ec7":{
      "scriptId":"u49"},
    "a778152c18624849ab713b751b4b9ccf":{
      "scriptId":"u50"},
    "cbd61ccc447a451fb07b8cb401040bde":{
      "scriptId":"u51"},
    "d7e160752d06441ca7fb2d2aab99da05":{
      "scriptId":"u52"},
    "6765341aae524171a6946ddbbeb8e93f":{
      "scriptId":"u53"},
    "ad90d7128feb452794eb40498ed2b92e":{
      "scriptId":"u54"},
    "b588dec41f764a68951236d75569692a":{
      "scriptId":"u55"},
    "d48a128cba8e4513a7f85ca8051bc43c":{
      "scriptId":"u56"},
    "374cef02a0b2420a8179c24c89a04c3e":{
      "scriptId":"u57"},
    "1815472dd6f54120bebcf44d27ae401f":{
      "scriptId":"u58"},
    "16300da142c1404da7b78a020baabb7c":{
      "scriptId":"u59"},
    "9ee83441104140c0ac3f104fbdc7ed07":{
      "scriptId":"u60"},
    "29085c33b4534467b554098f2c3877bb":{
      "scriptId":"u61"},
    "b12bfe2e85104ac8b90a4256672e6e16":{
      "scriptId":"u62"},
    "491c652043244f6993e264bbe7e2b1c6":{
      "scriptId":"u63"},
    "3f1ec3d4dc114d22964fba71612bb5b7":{
      "scriptId":"u64"},
    "4b9a95dec2034c13a04ddf1d23b4c51f":{
      "scriptId":"u65"},
    "501a99e52f6c4486b78a1058bd61f2f1":{
      "scriptId":"u66"},
    "adecd6de8fbc49fc85d0a7982dd4d8f6":{
      "scriptId":"u67"},
    "3ae661eef62c4ff7bdb1328292038c6e":{
      "scriptId":"u68"},
    "ca9984f6cc4e4faea629f369a20995d8":{
      "scriptId":"u69"},
    "11e391e807fb4c8db7da97737c4292b8":{
      "scriptId":"u70"},
    "3310d1741e4f49ccb1512275df9780c6":{
      "scriptId":"u71"},
    "ea3a7fcc06964fc9bcd9f4a9d16689de":{
      "scriptId":"u72"},
    "a85a78cbebd24144a4508ff5f30b2762":{
      "scriptId":"u73"},
    "d24fc22c3954411498cbfcb40a8aff96":{
      "scriptId":"u74"},
    "86fbaa26cd274c749cecb970414cabf9":{
      "scriptId":"u75"},
    "c7cdea4bc82247b48d863a1b31275ee3":{
      "scriptId":"u76"},
    "f7bbeae5359e41da87797f7c6df5de26":{
      "scriptId":"u77"},
    "af0873310e164dcf8271a1a9ba03cdfd":{
      "scriptId":"u78"},
    "b24adb56e1b644d89c7e9f677c7f9d81":{
      "scriptId":"u79"},
    "ea73f73197554ffb9345085cfb78dc5c":{
      "scriptId":"u80"},
    "af88e8f0d9ae4d3487840f71ded1dbbf":{
      "scriptId":"u81"},
    "556fce79cdd44bdba4913d91dc70a0fa":{
      "scriptId":"u82"},
    "5c38ea100c344fadb5b5e849ac5736ab":{
      "scriptId":"u83"},
    "273e3d23f9f046c7a66177ee300774b0":{
      "scriptId":"u84"},
    "548bcb466d6247b383b4e6949cf3f0ca":{
      "scriptId":"u85"},
    "7db01d861c18453696bdc9593d8bfebf":{
      "scriptId":"u86"},
    "90c5cf03aca34414ab6123d723125e08":{
      "scriptId":"u87"},
    "7c950c1467c045d6a7d06063df930507":{
      "scriptId":"u88"},
    "41e4be635ca14704a66c612e1f0db1e7":{
      "scriptId":"u89"},
    "2a94e62275e94ad3a4922d3e6fb74c70":{
      "scriptId":"u90"},
    "c72005ab964d47a09d45251ca5f81b26":{
      "scriptId":"u91"},
    "f94d3329d5d64767a62045bbf6d4e7cb":{
      "scriptId":"u92"},
    "d285af7c44c54d09bd0f0312c63dc599":{
      "scriptId":"u93"},
    "e0e16bc9e88c4b0f98eb4ecd34756461":{
      "scriptId":"u94"},
    "62a7d43a89704511b0f2c338fca5b47c":{
      "scriptId":"u95"},
    "f458e7a21fb741d19cc576cbc41b7c88":{
      "scriptId":"u96"},
    "8f9a4e375592408995cc4127394d07de":{
      "scriptId":"u97"},
    "68e7e0d4cc1b4bb9a893590e449acfb1":{
      "scriptId":"u98"},
    "18ac01664d8d4b379b2e663b3f5f46a4":{
      "scriptId":"u99"},
    "cc5ac96598df439cb5474892b4423f4c":{
      "scriptId":"u100"},
    "b3493207e81e49e0834c1eec92e7be1a":{
      "scriptId":"u101"},
    "51ec575eb3834baab9625170a1ef9305":{
      "scriptId":"u102"},
    "30bd851487504bbd9b9f6cecdd8fee5e":{
      "scriptId":"u103"},
    "bcfe1c4d14394d64b7cec9733c29479b":{
      "scriptId":"u104"},
    "4e58001c84f0484da5390a7741f61a42":{
      "scriptId":"u105"},
    "9fcf478761c54c95a8e7aa5e350d3fd5":{
      "scriptId":"u106"},
    "29cb59c4deb4402fab50144dc1159eb1":{
      "scriptId":"u107"},
    "cb593eb2831448d080e8c03728aff727":{
      "scriptId":"u108"},
    "a68c6f9557aa4d3a9387fc6ef94db0ab":{
      "scriptId":"u109"},
    "d1abcc63c33c45b7aa4c9db7bddf4c03":{
      "scriptId":"u110"},
    "2019283ac12f41e391ab89c1dc745695":{
      "scriptId":"u111"},
    "d41b74256e1f48d091184d91df7b1c61":{
      "scriptId":"u112"},
    "78a7d72af9e64f2cb02165f758fd66af":{
      "scriptId":"u113"},
    "38b7fd70c7ee436db9a15cb5dc019cb4":{
      "scriptId":"u114"},
    "79bc2b12b15341d6aff08367ea14d755":{
      "scriptId":"u115"},
    "8119a54c93e242c79f94dcef54f39685":{
      "scriptId":"u116"},
    "e293bb85652d426a8aacb2e576fb23bb":{
      "scriptId":"u117"},
    "99d02b45572e4a2fab96a0a1b3c35e74":{
      "scriptId":"u118"},
    "4e6d3e33816a4255aee201add3275289":{
      "scriptId":"u119"},
    "3583e1c6959c419e9c0dcde1a1d67480":{
      "scriptId":"u120"},
    "c0b35f563fa640ea8965fa7cde5ac1e5":{
      "scriptId":"u121"},
    "21ab5d87dd02423ba69b12ddb96b9fc6":{
      "scriptId":"u122"},
    "8b1d6044f1b34d0a865110bb0a0cc77d":{
      "scriptId":"u123"},
    "40aa09cffa344a3899b575cd0d8e6080":{
      "scriptId":"u124"}}});