$axure.loadCurrentPage({
  "url":"会员卡.html",
  "generationDate":new Date(1403514130710.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"59e718270cf94befac5d64547dd793fb",
    "type":"Axure:Page",
    "name":"会员卡",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ff4ed46090d14fab9d6bcd53c5bf826c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":2045,
              "height":1660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8adacd1eeb7a435ab2660a03504e2854",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":2045,
                  "height":1660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u0.png"}},
{
          "id":"9f6187175c194fb4af3fb99aadae74e1",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"902107210c5945488296965504331c2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"ea4aef809ba64166b5261e3a25001f31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":1660},
            "size":{
              "width":108,
              "height":102}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f542926c64943c98fda567a5cfcab97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":1660},
                "size":{
                  "width":108,
                  "height":102}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u4.png"}},
{
          "id":"7ed3a28f0d3344cf866792020f123004",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":222,
              "y":1660},
            "size":{
              "width":108,
              "height":102}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a85baa02548433ea3c85f1b967411ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":222,
                  "y":1660},
                "size":{
                  "width":108,
                  "height":102}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u4.png"}},
{
          "id":"f41a23fe03a34dee95dca8dfa7a4ca37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":159,
              "y":1690},
            "size":{
              "width":41,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d1837b2e27d44c0b313eafabe00d64e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":159,
                  "y":1690},
                "size":{
                  "width":41,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u8.png"}},
{
          "id":"c951e1a6e02d4659adb9c3e6ed0f8d8f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":230,
              "y":1680},
            "size":{
              "width":40,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6c66e5d7abd461cbef2890889ac6ff4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":1680},
                "size":{
                  "width":40,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u10.png"}},
{
          "id":"732ff6ffaec04ac090689ec7027dc54e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":1762},
            "size":{
              "width":320,
              "height":477}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b91d3f554684a599418870897c0e180",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":1762},
                "size":{
                  "width":320,
                  "height":477}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u12.png"}},
{
          "id":"a188c01c506a41d7beada54a9cab3040",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":50,
              "y":1916},
            "size":{
              "width":120,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"362e32ff9ae74aa08bc9709e42f3630f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":1916},
                "size":{
                  "width":120,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u14.png"}},
{
          "id":"ecbde0915f8b47daba11df4ee18559d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":50,
              "y":1966},
            "size":{
              "width":120,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56ff4cee7ece461784a13a3d62592aa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":1966},
                "size":{
                  "width":120,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u16.png"}},
{
          "id":"fbdcf2a9c8794c308cd5825ea278e3bf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":50,
              "y":2017},
            "size":{
              "width":120,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee52b8bde372429282b917854b83d777",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":2017},
                "size":{
                  "width":120,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u18.png"}},
{
          "id":"816afb8cd3b04d51b31584b3ccb5ba73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":1724},
            "size":{
              "width":40,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec246c2b209a449990a548d308f5e44f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":1724},
                "size":{
                  "width":40,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u20.png"}},
{
          "id":"36c427b48c8848f3ac0ad7c9bb0bc622",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":1755},
            "size":{
              "width":27,
              "height":8},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80a2e95fa4d24754aa396a2e00d69dd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":1755},
                "size":{
                  "width":27,
                  "height":8},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u22.png"}},
{
          "id":"50961ae5f789466781197a2223723dcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":119,
              "y":2130},
            "size":{
              "width":120,
              "height":108},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8baa29f278348bcabc5268b7d97f794",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":119,
                  "y":2130},
                "size":{
                  "width":120,
                  "height":108},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u24.png"}},
{
          "id":"ebbcce0bcf3e491995a6ee5721489ec2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":770,
              "y":80},
            "size":{
              "width":20,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d018c81d64946ba9e0a1869c42f5e7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":770,
                  "y":80},
                "size":{
                  "width":20,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u26.png"}},
{
          "id":"ac6c2fefabc34c9d89b5c80c89e198e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1140,
              "y":80},
            "size":{
              "width":20,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1565aa13faef49eaa625df9e4e9883be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1140,
                  "y":80},
                "size":{
                  "width":20,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u26.png"}},
{
          "id":"660f72909fd64530980d4e1258496ae6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1500,
              "y":80},
            "size":{
              "width":20,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32c6706acf954699947fe34bc55d9c34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1500,
                  "y":80},
                "size":{
                  "width":20,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u30.png"}},
{
          "id":"925803c88a2148d8ab2bfe930cd5b0b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1500,
              "y":580},
            "size":{
              "width":20,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6487a74c4dca41e491d3064164e0126e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1500,
                  "y":580},
                "size":{
                  "width":20,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u26.png"}},
{
          "id":"ce1c554931c04294a069aed72e3af795",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1140,
              "y":580},
            "size":{
              "width":20,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e56325e6ad894102aee486e6e9e13bd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1140,
                  "y":580},
                "size":{
                  "width":20,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u26.png"}},
{
          "id":"3e2be34697ce40c6964d1eb705da32e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":770,
              "y":580},
            "size":{
              "width":20,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddaaea17e11845c59665fbf22b7879c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":770,
                  "y":580},
                "size":{
                  "width":20,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u26.png"}},
{
          "id":"c1d1e86b89824ec8a749f07f8c3e9ff2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":400,
              "y":570},
            "size":{
              "width":20,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdfba55c453b4e1d850ab910b2c33294",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":400,
                  "y":570},
                "size":{
                  "width":20,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u26.png"}},
{
          "id":"c0730944f707461486e30f983325ccd4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":40,
              "y":1810},
            "size":{
              "width":110,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5684921d67ec445a9e2498a18fbc2e2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":1810},
                "size":{
                  "width":110,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u40.png"}},
{
          "id":"02c5b6e4ed0940ec9047d9717d55e715",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1482,
              "y":30},
            "size":{
              "width":328,
              "height":483}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49cf56704d6a49bba8f8aa61610d48ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1482,
                  "y":30},
                "size":{
                  "width":328,
                  "height":483}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员卡/u42.jpg"}},
{
          "id":"92fec5cdd1f04ac5a6b25eb7f524fb3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":1820,
              "y":120},
            "size":{
              "width":161,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc5e75dd82524f6c98779f71764d9534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":1820,
                  "y":120},
                "size":{
                  "width":161,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ff4ed46090d14fab9d6bcd53c5bf826c":{
      "scriptId":"u0"},
    "8adacd1eeb7a435ab2660a03504e2854":{
      "scriptId":"u1"},
    "9f6187175c194fb4af3fb99aadae74e1":{
      "scriptId":"u2"},
    "902107210c5945488296965504331c2d":{
      "scriptId":"u3"},
    "ea4aef809ba64166b5261e3a25001f31":{
      "scriptId":"u4"},
    "1f542926c64943c98fda567a5cfcab97":{
      "scriptId":"u5"},
    "7ed3a28f0d3344cf866792020f123004":{
      "scriptId":"u6"},
    "3a85baa02548433ea3c85f1b967411ad":{
      "scriptId":"u7"},
    "f41a23fe03a34dee95dca8dfa7a4ca37":{
      "scriptId":"u8"},
    "0d1837b2e27d44c0b313eafabe00d64e":{
      "scriptId":"u9"},
    "c951e1a6e02d4659adb9c3e6ed0f8d8f":{
      "scriptId":"u10"},
    "c6c66e5d7abd461cbef2890889ac6ff4":{
      "scriptId":"u11"},
    "732ff6ffaec04ac090689ec7027dc54e":{
      "scriptId":"u12"},
    "1b91d3f554684a599418870897c0e180":{
      "scriptId":"u13"},
    "a188c01c506a41d7beada54a9cab3040":{
      "scriptId":"u14"},
    "362e32ff9ae74aa08bc9709e42f3630f":{
      "scriptId":"u15"},
    "ecbde0915f8b47daba11df4ee18559d6":{
      "scriptId":"u16"},
    "56ff4cee7ece461784a13a3d62592aa1":{
      "scriptId":"u17"},
    "fbdcf2a9c8794c308cd5825ea278e3bf":{
      "scriptId":"u18"},
    "ee52b8bde372429282b917854b83d777":{
      "scriptId":"u19"},
    "816afb8cd3b04d51b31584b3ccb5ba73":{
      "scriptId":"u20"},
    "ec246c2b209a449990a548d308f5e44f":{
      "scriptId":"u21"},
    "36c427b48c8848f3ac0ad7c9bb0bc622":{
      "scriptId":"u22"},
    "80a2e95fa4d24754aa396a2e00d69dd8":{
      "scriptId":"u23"},
    "50961ae5f789466781197a2223723dcd":{
      "scriptId":"u24"},
    "a8baa29f278348bcabc5268b7d97f794":{
      "scriptId":"u25"},
    "ebbcce0bcf3e491995a6ee5721489ec2":{
      "scriptId":"u26"},
    "8d018c81d64946ba9e0a1869c42f5e7a":{
      "scriptId":"u27"},
    "ac6c2fefabc34c9d89b5c80c89e198e7":{
      "scriptId":"u28"},
    "1565aa13faef49eaa625df9e4e9883be":{
      "scriptId":"u29"},
    "660f72909fd64530980d4e1258496ae6":{
      "scriptId":"u30"},
    "32c6706acf954699947fe34bc55d9c34":{
      "scriptId":"u31"},
    "925803c88a2148d8ab2bfe930cd5b0b9":{
      "scriptId":"u32"},
    "6487a74c4dca41e491d3064164e0126e":{
      "scriptId":"u33"},
    "ce1c554931c04294a069aed72e3af795":{
      "scriptId":"u34"},
    "e56325e6ad894102aee486e6e9e13bd2":{
      "scriptId":"u35"},
    "3e2be34697ce40c6964d1eb705da32e4":{
      "scriptId":"u36"},
    "ddaaea17e11845c59665fbf22b7879c8":{
      "scriptId":"u37"},
    "c1d1e86b89824ec8a749f07f8c3e9ff2":{
      "scriptId":"u38"},
    "fdfba55c453b4e1d850ab910b2c33294":{
      "scriptId":"u39"},
    "c0730944f707461486e30f983325ccd4":{
      "scriptId":"u40"},
    "5684921d67ec445a9e2498a18fbc2e2d":{
      "scriptId":"u41"},
    "02c5b6e4ed0940ec9047d9717d55e715":{
      "scriptId":"u42"},
    "49cf56704d6a49bba8f8aa61610d48ca":{
      "scriptId":"u43"},
    "92fec5cdd1f04ac5a6b25eb7f524fb3c":{
      "scriptId":"u44"},
    "bc5e75dd82524f6c98779f71764d9534":{
      "scriptId":"u45"}}});