$axure.loadCurrentPage({
  "url":"登陆流程.html",
  "generationDate":new Date(1397446834287.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e0d754389d284a8db8e6370139db01f2",
    "type":"Axure:Page",
    "name":"登陆流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"34d4b90fa2f142948e47607262891230",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":230},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a8af364f7b449e39a4d1b2923402eff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":230},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆流程/u0.png"}},
{
          "id":"feecdea9f8934b8bab346c7e9ebe51d4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":320},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f98baae23db74d31ad3e01c0caca4351",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":320},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆流程/u2.png"}},
{
          "id":"47949fcf621446de94d78a2a4d6740a1",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":60},
            "size":{
              "width":50,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bdccea61f9f4e04a80a0e44a4e8a02b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":60},
                "size":{
                  "width":50,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆流程/u4.png"}},
{
          "id":"5a6cb161c9734df3a043a39a11ed307e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":270},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC66FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50cfd6985ef940f196da9929d5654aef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":270},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC66FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"d9887f1f3208475192b3611b1cc889e2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":400},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4dca3932a314e55a3380a69baddec74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":400},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆流程/u0.png"}},
{
          "id":"329d88f4df804a0eba02a5a9679b1e40",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":340},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10c6feb5fa434c0faffe3f29a4413e65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":340},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"5806a6fd98d44ca0917fb7694be13d46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":540,
              "y":320},
            "size":{
              "width":200,
              "height":40},
            "cornerRadiusTopLeft":"74"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"711486d4e8d44285a728ea7cd1c7c0cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":540,
                  "y":320},
                "size":{
                  "width":200,
                  "height":40},
                "cornerRadiusTopLeft":"74"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆流程/u12.png"}},
{
          "id":"8caac69081ce4ddd8ef657fb4abcb754",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":360},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC66FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"195956d994cd4cc8ac1c3fe153517998",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":360},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC66FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"a61e2c8691254402a9430c15e28918f6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":400},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08fe0bfa1e52425599b646b12b1e40ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":400},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆流程/u0.png"}},
{
          "id":"8cd1c4781dca4ec2ba5f46d37a241fde",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":360},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC66FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"552c4d60f3fe4ce39fd782b2db75881a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":360},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC66FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"f062a36064c043f5a2d282795c243d55",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":420},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3da86120cc7444e8a86ca32633fb39d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":420},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"baff2a2c5f9045b4a24ade6b7dd79e52",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":400},
            "size":{
              "width":200,
              "height":40},
            "cornerRadiusTopLeft":"74"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af65c17d2641403bb3381f5ea49c3e79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":400},
                "size":{
                  "width":200,
                  "height":40},
                "cornerRadiusTopLeft":"74"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆流程/u12.png"}},
{
          "id":"8a4f9cca99c04b719c2a4f7284c58b85",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":340},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC66FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee78b1d7bd644772b6e5fb059ee452b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":340},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC66FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"ffd13311cfde47faa51b8746d9cec68f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":200},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC66FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d99ee729c864921836cb617e8d3119c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":145,
                  "y":200},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC66FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"754851f48da84042a4129a90c8a92a61",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":490},
            "size":{
              "width":110,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acb88cfea9a34ed0a65b7f4ac8dca07b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":490},
                "size":{
                  "width":110,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆流程/u28.png"}},
{
          "id":"ce6fb14461d5420788972a7874c2000c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":440},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC66FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a6d0490cde04ffe9c6909185d939af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":440},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC66FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"3f96fbfb46d94a5f8b27a86bb6b5dd8f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":440},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC66FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a0966cfc8b34665a08d4b01a471f24b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":440},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC66FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"421be24bc8e84579ab690e82fa3b3006",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":12},
            "size":{
              "width":240,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9e06ca0617a4f7085c2c500a8b8a4a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":12},
                "size":{
                  "width":240,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0be5bf58d8949a99282365328fab00f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":160},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fb81776c40c473c9f0a178f9365f25a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":160},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆流程/u0.png"}},
{
          "id":"913a781952094a5da4cda65713f74c09",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":160},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed8b2a306f2648e49107b91f331052c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":225,
                  "y":160},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆流程/u0.png"}},
{
          "id":"849f0299b19d470488a57c5d42f73054",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":200},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC66FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9781677a6d31406ebf2db51fa5ff6794",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":275,
                  "y":200},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC66FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"0ef4eaea12134fddae5829237ca3a418",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":120},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC66FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fbc45be979542f3bb5cb5ca481e2d97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":120},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC66FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"dda6f4f365c74efba49070a89b01ffd4",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":120},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC66FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"880ea0f6df8f45dd8aa479905607aaf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":120},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC66FF}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "34d4b90fa2f142948e47607262891230":{
      "scriptId":"u0"},
    "5a8af364f7b449e39a4d1b2923402eff":{
      "scriptId":"u1"},
    "feecdea9f8934b8bab346c7e9ebe51d4":{
      "scriptId":"u2"},
    "f98baae23db74d31ad3e01c0caca4351":{
      "scriptId":"u3"},
    "47949fcf621446de94d78a2a4d6740a1":{
      "scriptId":"u4"},
    "9bdccea61f9f4e04a80a0e44a4e8a02b":{
      "scriptId":"u5"},
    "5a6cb161c9734df3a043a39a11ed307e":{
      "scriptId":"u6"},
    "50cfd6985ef940f196da9929d5654aef":{
      "scriptId":"u7"},
    "d9887f1f3208475192b3611b1cc889e2":{
      "scriptId":"u8"},
    "b4dca3932a314e55a3380a69baddec74":{
      "scriptId":"u9"},
    "329d88f4df804a0eba02a5a9679b1e40":{
      "scriptId":"u10"},
    "10c6feb5fa434c0faffe3f29a4413e65":{
      "scriptId":"u11"},
    "5806a6fd98d44ca0917fb7694be13d46":{
      "scriptId":"u12"},
    "711486d4e8d44285a728ea7cd1c7c0cb":{
      "scriptId":"u13"},
    "8caac69081ce4ddd8ef657fb4abcb754":{
      "scriptId":"u14"},
    "195956d994cd4cc8ac1c3fe153517998":{
      "scriptId":"u15"},
    "a61e2c8691254402a9430c15e28918f6":{
      "scriptId":"u16"},
    "08fe0bfa1e52425599b646b12b1e40ac":{
      "scriptId":"u17"},
    "8cd1c4781dca4ec2ba5f46d37a241fde":{
      "scriptId":"u18"},
    "552c4d60f3fe4ce39fd782b2db75881a":{
      "scriptId":"u19"},
    "f062a36064c043f5a2d282795c243d55":{
      "scriptId":"u20"},
    "3da86120cc7444e8a86ca32633fb39d2":{
      "scriptId":"u21"},
    "baff2a2c5f9045b4a24ade6b7dd79e52":{
      "scriptId":"u22"},
    "af65c17d2641403bb3381f5ea49c3e79":{
      "scriptId":"u23"},
    "8a4f9cca99c04b719c2a4f7284c58b85":{
      "scriptId":"u24"},
    "ee78b1d7bd644772b6e5fb059ee452b4":{
      "scriptId":"u25"},
    "ffd13311cfde47faa51b8746d9cec68f":{
      "scriptId":"u26"},
    "8d99ee729c864921836cb617e8d3119c":{
      "scriptId":"u27"},
    "754851f48da84042a4129a90c8a92a61":{
      "scriptId":"u28"},
    "acb88cfea9a34ed0a65b7f4ac8dca07b":{
      "scriptId":"u29"},
    "ce6fb14461d5420788972a7874c2000c":{
      "scriptId":"u30"},
    "7a6d0490cde04ffe9c6909185d939af4":{
      "scriptId":"u31"},
    "3f96fbfb46d94a5f8b27a86bb6b5dd8f":{
      "scriptId":"u32"},
    "8a0966cfc8b34665a08d4b01a471f24b":{
      "scriptId":"u33"},
    "421be24bc8e84579ab690e82fa3b3006":{
      "scriptId":"u34"},
    "a9e06ca0617a4f7085c2c500a8b8a4a3":{
      "scriptId":"u35"},
    "c0be5bf58d8949a99282365328fab00f":{
      "scriptId":"u36"},
    "8fb81776c40c473c9f0a178f9365f25a":{
      "scriptId":"u37"},
    "913a781952094a5da4cda65713f74c09":{
      "scriptId":"u38"},
    "ed8b2a306f2648e49107b91f331052c2":{
      "scriptId":"u39"},
    "849f0299b19d470488a57c5d42f73054":{
      "scriptId":"u40"},
    "9781677a6d31406ebf2db51fa5ff6794":{
      "scriptId":"u41"},
    "0ef4eaea12134fddae5829237ca3a418":{
      "scriptId":"u42"},
    "1fbc45be979542f3bb5cb5ca481e2d97":{
      "scriptId":"u43"},
    "dda6f4f365c74efba49070a89b01ffd4":{
      "scriptId":"u44"},
    "880ea0f6df8f45dd8aa479905607aaf3":{
      "scriptId":"u45"}}});