$axure.loadCurrentPage({
  "url":"登陆成功（分享注册）.html",
  "generationDate":new Date(1404796804581.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b61a191e79c9496d92f73218ec0c1b0b",
    "type":"Axure:Page",
    "name":"登陆成功（分享注册）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"707a469566ec4b7cb7486a2abbaa484c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":310,
              "height":550},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEEEFF1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71cc299f32af4de1895b659170befe6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":310,
                  "height":550},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEEEFF1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首界面/u0.jpg"}},
{
          "id":"38e66acf03ed4e5080a3cce2fcbe974b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":74},
            "size":{
              "width":309,
              "height":440},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEEEFF1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98236af7d69d4f63ad1487a0b83eced8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":74},
                "size":{
                  "width":309,
                  "height":440},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEEEFF1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆成功（分享注册）/u2.png"}},
{
          "id":"afd30ddc9fa044228886217a507f3d9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1156,
              "y":24},
            "size":{
              "width":564,
              "height":356}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1ffe0b4892f4bd09d9b064046515894",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1156,
                  "y":24},
                "size":{
                  "width":564,
                  "height":356}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆成功（分享注册）/u4.png"}},
{
          "id":"580deac0c92e42bf8b7df7ddc570c8cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"28px",
            "location":{
              "x":25,
              "y":369},
            "size":{
              "width":300,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"778ff50921754fc7829ba8d59668e83b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"28px",
                "location":{
                  "x":25,
                  "y":369},
                "size":{
                  "width":300,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91e9646c5e27463882b46bbc5ffd624d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":129},
            "size":{
              "width":290,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4422c4a848584061b72b77cfa4198d3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":129},
                "size":{
                  "width":290,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆成功（分享注册）/u8.png"}},
{
          "id":"b22295c8cb2245bdb857ae3e3d56f374",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF33CCFF},
            "location":{
              "x":112.000007629395,
              "y":460},
            "size":{
              "width":126,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33CCFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"586f76a93c8243c1b4f255e43df6002b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33CCFF},
                "location":{
                  "x":112.000007629395,
                  "y":460},
                "size":{
                  "width":126,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF33CCFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆成功（分享注册）/u10.png"}},
{
          "id":"dc8eed70c52a4715909c1a9dc91741ae",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":324},
            "size":{
              "width":180,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/登陆成功（分享注册）/u12_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登陆成功（分享注册）/u12_line.png"}},
{
          "id":"8611aae71e704778b2fe5435de649c6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":460,
              "y":309},
            "size":{
              "width":136,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f75fbc68ba1244e082c1082c0b1d1668",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":460,
                  "y":309},
                "size":{
                  "width":136,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26df72c21fd84c71902d4efab6ced938",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"0px",
            "location":{
              "x":75,
              "y":90},
            "size":{
              "width":200,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f806db30eba54fc0841b101e3cb6cf8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"0px",
                "location":{
                  "x":75,
                  "y":90},
                "size":{
                  "width":200,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8816ecafdd1e46ccbe1a546f87c744c4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":112},
            "size":{
              "width":290,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登陆成功（分享注册）/u17_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "707a469566ec4b7cb7486a2abbaa484c":{
      "scriptId":"u0"},
    "71cc299f32af4de1895b659170befe6b":{
      "scriptId":"u1"},
    "38e66acf03ed4e5080a3cce2fcbe974b":{
      "scriptId":"u2"},
    "98236af7d69d4f63ad1487a0b83eced8":{
      "scriptId":"u3"},
    "afd30ddc9fa044228886217a507f3d9c":{
      "scriptId":"u4"},
    "c1ffe0b4892f4bd09d9b064046515894":{
      "scriptId":"u5"},
    "580deac0c92e42bf8b7df7ddc570c8cf":{
      "scriptId":"u6"},
    "778ff50921754fc7829ba8d59668e83b":{
      "scriptId":"u7"},
    "91e9646c5e27463882b46bbc5ffd624d":{
      "scriptId":"u8"},
    "4422c4a848584061b72b77cfa4198d3a":{
      "scriptId":"u9"},
    "b22295c8cb2245bdb857ae3e3d56f374":{
      "scriptId":"u10"},
    "586f76a93c8243c1b4f255e43df6002b":{
      "scriptId":"u11"},
    "dc8eed70c52a4715909c1a9dc91741ae":{
      "scriptId":"u12"},
    "8611aae71e704778b2fe5435de649c6a":{
      "scriptId":"u13"},
    "f75fbc68ba1244e082c1082c0b1d1668":{
      "scriptId":"u14"},
    "26df72c21fd84c71902d4efab6ced938":{
      "scriptId":"u15"},
    "f806db30eba54fc0841b101e3cb6cf8f":{
      "scriptId":"u16"},
    "8816ecafdd1e46ccbe1a546f87c744c4":{
      "scriptId":"u17"}}});