$axure.loadCurrentPage({
  "url":"wifi__.html",
  "generationDate":new Date(1404796803814.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a33a9412bf02420eb79845a3ccff8975",
    "type":"Axure:Page",
    "name":"WiFi链接",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c4647e249e5743b0b252757c7638a0d3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":27},
            "size":{
              "width":310,
              "height":550}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e77de0726d3c418b9867695bda152a51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":27},
                "size":{
                  "width":310,
                  "height":550}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wifi__/u0.jpg"}},
{
          "id":"486ce54af00048dd99ec220127315824",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":98,
              "y":169},
            "size":{
              "width":142,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e906a6c441041aa83e949fe371847ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":98,
                  "y":169},
                "size":{
                  "width":142,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wifi__/u2.png"}},
{
          "id":"e5307d3d76d84e5489a46383741a72b0",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":169},
            "size":{
              "width":142,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首界面",
                      "target":{
                        "targetType":"page",
                        "url":"首界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "c4647e249e5743b0b252757c7638a0d3":{
      "scriptId":"u0"},
    "e77de0726d3c418b9867695bda152a51":{
      "scriptId":"u1"},
    "486ce54af00048dd99ec220127315824":{
      "scriptId":"u2"},
    "2e906a6c441041aa83e949fe371847ba":{
      "scriptId":"u3"},
    "e5307d3d76d84e5489a46383741a72b0":{
      "scriptId":"u4"}}});