$axure.loadCurrentPage({
  "url":"短信发送.html",
  "generationDate":new Date(1401876150968.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f88f2ad88f5b4c2cba9f1e91abd3af69",
    "type":"Axure:Page",
    "name":"短信发送",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4758b95fccf1446fbbb3b8d3b881f460",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":11,
              "y":610},
            "size":{
              "width":750,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99c66a7fb1e6446599a7f94a0d42a7fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":11,
                  "y":610},
                "size":{
                  "width":750,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u0.png"}},
{
          "id":"68cf1bce5bb340c88826990c01ec87c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":860,
              "y":147},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59306c38fb1c473eaa8096fd44bd78b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":860,
                  "y":147},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00f0b0743fd544b2aeb9a869bdc89518",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":20,
              "y":50},
            "size":{
              "width":210,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"688613effaf8465f9d248405f799e7ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":20,
                  "y":50},
                "size":{
                  "width":210,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e5961eac0654533b2a94851a10b16c4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":75},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/短信发送/u6_line.png"}},
{
          "id":"1a664f182536468dbdcfa9f92f01148b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":1090,
              "y":147},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1a9a0765f434df8836f870e25a05c1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1090,
                  "y":147},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"61bc31587b4948a8824c01a5c1207067",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":147},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e5e6a165416470fa24eb2a8baec54eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":950,
                  "y":147},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7042df8d7a6346edba5f3eac0e163b8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":860,
              "y":197},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dfdffc2f9214a9fbecd98e731cd0d13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":860,
                  "y":197},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3564fe12515346babe88f93772ff7859",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":950,
              "y":197},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5673c415908b4d2886460fb40a81e56e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":950,
                  "y":197},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c22717c1152149e7b72f9918e706094b",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":1090,
              "y":197},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7703abd7f5f743609d7892e1bcd3aa49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1090,
                  "y":197},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"37ed4492e33a44b48947c6b2b196b4cc",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":1230,
              "y":197},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e1245ee029d422f98567d6adcedba32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1230,
                  "y":197},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"84dc7dc4b9b941fca25f0eb29da37c7f",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":1370,
              "y":197},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08b25320241b4ef7b16c51882f02f4bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1370,
                  "y":197},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b43439b38267437aa459ec4d881d9631",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":1510,
              "y":197},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e402a171341e4ce58e8038638ab146c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1510,
                  "y":197},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"17cd7986f65446219f91dd1e10626b9c",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":247},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cd549ac59044ad8b99e28c1ed2677f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":950,
                  "y":247},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b2088337c207420ea2c9664c2c230cea",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":1090,
              "y":247},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"761b431c50a54b938650c1ddecaf222f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1090,
                  "y":247},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"16c71af9d8b449dba746d6a914808afa",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":1230,
              "y":247},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaae5605cdaa46579f1686971397a2b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1230,
                  "y":247},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"46c95f96aa9d48e6a7a9150b348e3d23",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":1370,
              "y":247},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e607faa113a44ceaae355bf6221e7080",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1370,
                  "y":247},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"58ad4efd8514428783aab3c98d686397",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":1510,
              "y":247},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14f843c96aaf41e4a3f689ba2df85661",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1510,
                  "y":247},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7fcfb7e732c9406bb3a8e47cc387241d",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":297},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b2a04b1db814ee38f617962d3f0c8cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":950,
                  "y":297},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"04296c96e56143deb3a69b11393587e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":30,
              "y":144},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2f97989e29e48d192bdb8b1d1eb570a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":30,
                  "y":144},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a648211af5ab4e4fb82d2d040d9d80d6",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":144},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a743798f80a478fb5721605bfa54013",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":144},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"eaf6fbe122b1458d994711942d750e98",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":144},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba581ace6e504c26b438a14f0aad417d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":144},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d027c4cbd2504a49a7689f953acc0c18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":30,
              "y":194},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"470856b98ea94aa58e0eb3226d3ca643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":30,
                  "y":194},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc77478001714e67958e2e94c882c165",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":188},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"46c16c43d04f4587a188b80ac146fe5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":30,
              "y":244},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8e11ac5461f4183a41dd818d293cf57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":30,
                  "y":244},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f9b810d04f44fad97ecbd2e6e375ec2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":235},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"da29740c41d8458d87e7f1c17c9b3856",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":235},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ea2bf679e58c45b5b18e72328e341c72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":350,
              "y":244},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9afc1cf0daae41dc8f2528900367fbaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":350,
                  "y":244},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f72d5244282a452aa947e24845788ced",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":30,
              "y":574},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"694be3e7f9364fda98d9123a962e4190",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":30,
                  "y":574},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae7dd3da28504a7d8f81afc79d34ddba",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":574},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0976c6a20b146b5b028cca83733a32f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":574},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4b3c2c9866ec4c56a34b32fdbc771ddf",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":574},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7efb6a29c4c749e685580ec3cc278df0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":574},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e400e0c8bdcc4ed9ac170db1e4729202",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":30,
              "y":634},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b867f51f586f4a9fac445d3c99ed7299",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":30,
                  "y":634},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c74dc046ad0416f85722f68985695de",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":625},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"95ec07b86f514a339c442fb45bfa92f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":320,
              "y":634},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf45057fe307410380a4040256039971",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":634},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc8e6750dae6406f8b8cff98180bc61e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":30,
              "y":430},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6310b8c02c2419dafcd76bbf2bb7d48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":30,
                  "y":430},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"526aa923c4554e8db197ebe542052081",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":430},
            "size":{
              "width":400,
              "height":100}},
          "adaptiveStyles":{
}},
{
          "id":"26c9a1d27579478fa2fe753f8aff9ec6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":120,
              "y":530},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99550083a79a4421a05f733885d9e7c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":530},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2af05c44fc4c4f2aa455144b2206a010",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":724},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b57acd5d49ad4af9b0450a2fd9134bfe",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":1230,
              "y":138},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2d76ccd4059a4f169076dcd470ce1d3b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1430,
              "y":141},
            "size":{
              "width":24,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5054dc37925406d9076a9115d30f24a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1430,
                  "y":141},
                "size":{
                  "width":24,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u68.png"}},
{
          "id":"d9ca37460e994b63ac52186cb54f9c45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":860},
            "size":{
              "width":340,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65c06adbd14f41d9979dd3076aa13674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":860},
                "size":{
                  "width":340,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u70.png"}},
{
          "id":"33054adfb9e04d1b89a8ff84040ee541",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":30,
              "y":1060},
            "size":{
              "width":70,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a1e63a94c914280a85101e818108a47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":30,
                  "y":1060},
                "size":{
                  "width":70,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1a130f66581414f9a89e3e3a652c6d9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":1060},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b1300693aaec484eb09dcf99e16d739b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":1060},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"497cd9c9e3294a8dbac0cedb00688d4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":170,
              "y":895},
            "size":{
              "width":240,
              "height":140},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"860badeffc6f433192ad3537a932fcd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":170,
                  "y":895},
                "size":{
                  "width":240,
                  "height":140},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u76.png"}},
{
          "id":"633e0c30a622493184c902a4976bac09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":215,
              "y":932},
            "size":{
              "width":150,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6562d92a8dc840f0ac624afb6f395368",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":215,
                  "y":932},
                "size":{
                  "width":150,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0377285a82a49e3ba431a28eccb5d8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":1170},
            "size":{
              "width":340,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e050193fd12b47e6a44f719f9b01e452",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":1170},
                "size":{
                  "width":340,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u70.png"}},
{
          "id":"bc3044396679450bb80ae1fd163c715e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":175,
              "y":1212},
            "size":{
              "width":250,
              "height":165},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2421f3ec2a6430dbc3d81184e9f7dad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":175,
                  "y":1212},
                "size":{
                  "width":250,
                  "height":165},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u82.png"}},
{
          "id":"396eabf77e6f4d039e8e595040687a60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":1168},
            "size":{
              "width":340,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c71fd9726874656854125d50deb8210",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":1168},
                "size":{
                  "width":340,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u70.png"}},
{
          "id":"cb2211fbefce46cba9a93e739363413d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":600,
              "y":1203},
            "size":{
              "width":240,
              "height":140},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9a1eef12c474cc4a3a98cd9fc78a6b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":600,
                  "y":1203},
                "size":{
                  "width":240,
                  "height":140},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u76.png"}},
{
          "id":"c5eead21bffc4b16976385c567fda7cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "location":{
              "x":610,
              "y":1237},
            "size":{
              "width":210,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c43830fd6374ae1b622045ac1eb405d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "location":{
                  "x":610,
                  "y":1237},
                "size":{
                  "width":210,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c57a78d1ce8f4fe2b10fd6913cdfce37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "location":{
              "x":195,
              "y":1246},
            "size":{
              "width":210,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4163a435d41b46c0bed63c85f7985aa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "location":{
                  "x":195,
                  "y":1246},
                "size":{
                  "width":210,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b8a54eb429842fdab4d055ad53cc323",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":872,
              "y":1148},
            "size":{
              "width":48,
              "height":48},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffcb24681fe64df9b92e22eb4790b993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":872,
                  "y":1148},
                "size":{
                  "width":48,
                  "height":48},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u92.png"}},
{
          "id":"4ac793ad4ed94cf98c4df38934260bbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":875,
              "y":1151},
            "size":{
              "width":42,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8bc4a78a7154fa08664a8934602d50e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":875,
                  "y":1151},
                "size":{
                  "width":42,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u94.png"}},
{
          "id":"7eb7f18abee141a789e233c66bdf2334",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":1150},
            "size":{
              "width":48,
              "height":48},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a22dc573bbb4a5ca2c625d9a2c20d18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":1150},
                "size":{
                  "width":48,
                  "height":48},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u92.png"}},
{
          "id":"47af1b1f1db84b99a14c3d84f612e8e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":445,
              "y":1153},
            "size":{
              "width":42,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40af036674834a86bdda8a04cda901ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":445,
                  "y":1153},
                "size":{
                  "width":42,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u94.png"}},
{
          "id":"a18b6c56d5bb43dcb1fe646178710989",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":30,
              "y":360},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3633be8af26d43398e79fe6f5563dd4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":30,
                  "y":360},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef77f7d70a5c435482103780d9ee7167",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":354},
            "size":{
              "width":110,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"7e2cd5ae7560477c80f8590362375127",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":130},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f95ad133e9242219f26477e405c7b28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":130},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"85da388ae8e8413ab46008706e6d7be3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1000,
              "y":90},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"360c0a4c3e3144aab7a277b4812d1827",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1000,
                  "y":90},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15aae8ed559c4fef8d020632b6947888",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":120,
              "y":210},
            "size":{
              "width":220,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5a57104c7474517a0e916953332afd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":210},
                "size":{
                  "width":220,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70e4e90eedda43329e5fb4592457c8c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":120,
              "y":260},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4505e7b0922f4d5a8b062820976764b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":260},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57310c21727b47a79dc56a4fe430a6cf",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":1210,
              "y":147},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5238d977a3584455bd4c1814dab9003c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1210,
                  "y":147},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6ca1141e73d742588ae89a6dae505c1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":1636,
              "y":144},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a08f99cbdd54d59988c6dcd2c0bc442",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":1636,
                  "y":144},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3460ea67c596415090bb1a4b30f535fe",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":1726,
              "y":144},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8b7d88350a6472eaf3e2c87915d2b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1726,
                  "y":144},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"fdc507b5cab943b78a11011342cd01da",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":1866,
              "y":144},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92f7f5c8b9ad4115898b3d2cd12beb9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1866,
                  "y":144},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0d0522f994134000a6a56c663b2cdb3e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":2006,
              "y":135},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5ee5f612cbb44b4b967591c839fa6f6a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2206,
              "y":138},
            "size":{
              "width":24,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e7829554b3f49328c0dfb0149dc7f10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2206,
                  "y":138},
                "size":{
                  "width":24,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u68.png"}},
{
          "id":"5956cf7adacb4c68969bfe353ca97b2e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":1986,
              "y":144},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ff622d3c9d84a3f958b131051c43d41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1986,
                  "y":144},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"2079d44b35db4f20ad4e1e45b4d1701e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":30,
              "y":303},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c1c23b462a74001ac13764e296d1be5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":30,
                  "y":303},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"049d7b689a5a4849a474079c0eaef5de",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":294},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8f7d8d8f7e9c4cf0bada4b3071788f43",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":294},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9cff79d4d8b148fb9a43d2960a10f420",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":350,
              "y":303},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c63467c871b41ff9ad5277f6ae1e3a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":350,
                  "y":303},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b40b041ecff24a80ab43335f3b2d741b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":120,
              "y":319},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbd67799e0eb4b14961f3ba92730725a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":319},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b33e2bbb9f784f14a79643db9ddf9831",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":396,
              "y":135},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ad82b8a04eec49899b596c2936d0a1eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":596,
              "y":138},
            "size":{
              "width":24,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c728b147d9684b008350ff143b272a80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":596,
                  "y":138},
                "size":{
                  "width":24,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u68.png"}},
{
          "id":"bd8675b6e74043b0bfe35fda5a8f49eb",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":376,
              "y":144},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b054328b1af4654986d92456df7444c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":376,
                  "y":144},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6e3c72923a414735906f290d38b07e30",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":836},
            "size":{
              "width":48,
              "height":48},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ef1ceec34e94592820552a605fe6058",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":836},
                "size":{
                  "width":48,
                  "height":48},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u92.png"}},
{
          "id":"fb1226424a714156a6d6debd79ca5e85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":445,
              "y":839},
            "size":{
              "width":42,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"775190b0b202484b8957df20d6e1508a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":445,
                  "y":839},
                "size":{
                  "width":42,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短信发送/u94.png"}},
{
          "id":"2705aef1d48f4030864f34145f5643bd",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":760},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61d3679b6c4047faae903ddf9178b798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":760},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "4758b95fccf1446fbbb3b8d3b881f460":{
      "scriptId":"u0"},
    "99c66a7fb1e6446599a7f94a0d42a7fd":{
      "scriptId":"u1"},
    "68cf1bce5bb340c88826990c01ec87c4":{
      "scriptId":"u2"},
    "59306c38fb1c473eaa8096fd44bd78b0":{
      "scriptId":"u3"},
    "00f0b0743fd544b2aeb9a869bdc89518":{
      "scriptId":"u4"},
    "688613effaf8465f9d248405f799e7ef":{
      "scriptId":"u5"},
    "2e5961eac0654533b2a94851a10b16c4":{
      "scriptId":"u6"},
    "1a664f182536468dbdcfa9f92f01148b":{
      "scriptId":"u7"},
    "d1a9a0765f434df8836f870e25a05c1d":{
      "scriptId":"u8"},
    "61bc31587b4948a8824c01a5c1207067":{
      "scriptId":"u9"},
    "8e5e6a165416470fa24eb2a8baec54eb":{
      "scriptId":"u10"},
    "7042df8d7a6346edba5f3eac0e163b8a":{
      "scriptId":"u11"},
    "1dfdffc2f9214a9fbecd98e731cd0d13":{
      "scriptId":"u12"},
    "3564fe12515346babe88f93772ff7859":{
      "scriptId":"u13"},
    "5673c415908b4d2886460fb40a81e56e":{
      "scriptId":"u14"},
    "c22717c1152149e7b72f9918e706094b":{
      "scriptId":"u15"},
    "7703abd7f5f743609d7892e1bcd3aa49":{
      "scriptId":"u16"},
    "37ed4492e33a44b48947c6b2b196b4cc":{
      "scriptId":"u17"},
    "3e1245ee029d422f98567d6adcedba32":{
      "scriptId":"u18"},
    "84dc7dc4b9b941fca25f0eb29da37c7f":{
      "scriptId":"u19"},
    "08b25320241b4ef7b16c51882f02f4bd":{
      "scriptId":"u20"},
    "b43439b38267437aa459ec4d881d9631":{
      "scriptId":"u21"},
    "e402a171341e4ce58e8038638ab146c8":{
      "scriptId":"u22"},
    "17cd7986f65446219f91dd1e10626b9c":{
      "scriptId":"u23"},
    "5cd549ac59044ad8b99e28c1ed2677f3":{
      "scriptId":"u24"},
    "b2088337c207420ea2c9664c2c230cea":{
      "scriptId":"u25"},
    "761b431c50a54b938650c1ddecaf222f":{
      "scriptId":"u26"},
    "16c71af9d8b449dba746d6a914808afa":{
      "scriptId":"u27"},
    "aaae5605cdaa46579f1686971397a2b1":{
      "scriptId":"u28"},
    "46c95f96aa9d48e6a7a9150b348e3d23":{
      "scriptId":"u29"},
    "e607faa113a44ceaae355bf6221e7080":{
      "scriptId":"u30"},
    "58ad4efd8514428783aab3c98d686397":{
      "scriptId":"u31"},
    "14f843c96aaf41e4a3f689ba2df85661":{
      "scriptId":"u32"},
    "7fcfb7e732c9406bb3a8e47cc387241d":{
      "scriptId":"u33"},
    "2b2a04b1db814ee38f617962d3f0c8cc":{
      "scriptId":"u34"},
    "04296c96e56143deb3a69b11393587e3":{
      "scriptId":"u35"},
    "c2f97989e29e48d192bdb8b1d1eb570a":{
      "scriptId":"u36"},
    "a648211af5ab4e4fb82d2d040d9d80d6":{
      "scriptId":"u37"},
    "9a743798f80a478fb5721605bfa54013":{
      "scriptId":"u38"},
    "eaf6fbe122b1458d994711942d750e98":{
      "scriptId":"u39"},
    "ba581ace6e504c26b438a14f0aad417d":{
      "scriptId":"u40"},
    "d027c4cbd2504a49a7689f953acc0c18":{
      "scriptId":"u41"},
    "470856b98ea94aa58e0eb3226d3ca643":{
      "scriptId":"u42"},
    "fc77478001714e67958e2e94c882c165":{
      "scriptId":"u43"},
    "46c16c43d04f4587a188b80ac146fe5a":{
      "scriptId":"u44"},
    "c8e11ac5461f4183a41dd818d293cf57":{
      "scriptId":"u45"},
    "1f9b810d04f44fad97ecbd2e6e375ec2":{
      "scriptId":"u46"},
    "da29740c41d8458d87e7f1c17c9b3856":{
      "scriptId":"u47"},
    "ea2bf679e58c45b5b18e72328e341c72":{
      "scriptId":"u48"},
    "9afc1cf0daae41dc8f2528900367fbaf":{
      "scriptId":"u49"},
    "f72d5244282a452aa947e24845788ced":{
      "scriptId":"u50"},
    "694be3e7f9364fda98d9123a962e4190":{
      "scriptId":"u51"},
    "ae7dd3da28504a7d8f81afc79d34ddba":{
      "scriptId":"u52"},
    "d0976c6a20b146b5b028cca83733a32f":{
      "scriptId":"u53"},
    "4b3c2c9866ec4c56a34b32fdbc771ddf":{
      "scriptId":"u54"},
    "7efb6a29c4c749e685580ec3cc278df0":{
      "scriptId":"u55"},
    "e400e0c8bdcc4ed9ac170db1e4729202":{
      "scriptId":"u56"},
    "b867f51f586f4a9fac445d3c99ed7299":{
      "scriptId":"u57"},
    "4c74dc046ad0416f85722f68985695de":{
      "scriptId":"u58"},
    "95ec07b86f514a339c442fb45bfa92f2":{
      "scriptId":"u59"},
    "bf45057fe307410380a4040256039971":{
      "scriptId":"u60"},
    "fc8e6750dae6406f8b8cff98180bc61e":{
      "scriptId":"u61"},
    "d6310b8c02c2419dafcd76bbf2bb7d48":{
      "scriptId":"u62"},
    "526aa923c4554e8db197ebe542052081":{
      "scriptId":"u63"},
    "26c9a1d27579478fa2fe753f8aff9ec6":{
      "scriptId":"u64"},
    "99550083a79a4421a05f733885d9e7c5":{
      "scriptId":"u65"},
    "2af05c44fc4c4f2aa455144b2206a010":{
      "scriptId":"u66"},
    "b57acd5d49ad4af9b0450a2fd9134bfe":{
      "scriptId":"u67"},
    "2d76ccd4059a4f169076dcd470ce1d3b":{
      "scriptId":"u68"},
    "f5054dc37925406d9076a9115d30f24a":{
      "scriptId":"u69"},
    "d9ca37460e994b63ac52186cb54f9c45":{
      "scriptId":"u70"},
    "65c06adbd14f41d9979dd3076aa13674":{
      "scriptId":"u71"},
    "33054adfb9e04d1b89a8ff84040ee541":{
      "scriptId":"u72"},
    "7a1e63a94c914280a85101e818108a47":{
      "scriptId":"u73"},
    "d1a130f66581414f9a89e3e3a652c6d9":{
      "scriptId":"u74"},
    "b1300693aaec484eb09dcf99e16d739b":{
      "scriptId":"u75"},
    "497cd9c9e3294a8dbac0cedb00688d4b":{
      "scriptId":"u76"},
    "860badeffc6f433192ad3537a932fcd1":{
      "scriptId":"u77"},
    "633e0c30a622493184c902a4976bac09":{
      "scriptId":"u78"},
    "6562d92a8dc840f0ac624afb6f395368":{
      "scriptId":"u79"},
    "d0377285a82a49e3ba431a28eccb5d8d":{
      "scriptId":"u80"},
    "e050193fd12b47e6a44f719f9b01e452":{
      "scriptId":"u81"},
    "bc3044396679450bb80ae1fd163c715e":{
      "scriptId":"u82"},
    "b2421f3ec2a6430dbc3d81184e9f7dad":{
      "scriptId":"u83"},
    "396eabf77e6f4d039e8e595040687a60":{
      "scriptId":"u84"},
    "5c71fd9726874656854125d50deb8210":{
      "scriptId":"u85"},
    "cb2211fbefce46cba9a93e739363413d":{
      "scriptId":"u86"},
    "e9a1eef12c474cc4a3a98cd9fc78a6b2":{
      "scriptId":"u87"},
    "c5eead21bffc4b16976385c567fda7cf":{
      "scriptId":"u88"},
    "1c43830fd6374ae1b622045ac1eb405d":{
      "scriptId":"u89"},
    "c57a78d1ce8f4fe2b10fd6913cdfce37":{
      "scriptId":"u90"},
    "4163a435d41b46c0bed63c85f7985aa0":{
      "scriptId":"u91"},
    "7b8a54eb429842fdab4d055ad53cc323":{
      "scriptId":"u92"},
    "ffcb24681fe64df9b92e22eb4790b993":{
      "scriptId":"u93"},
    "4ac793ad4ed94cf98c4df38934260bbc":{
      "scriptId":"u94"},
    "b8bc4a78a7154fa08664a8934602d50e":{
      "scriptId":"u95"},
    "7eb7f18abee141a789e233c66bdf2334":{
      "scriptId":"u96"},
    "5a22dc573bbb4a5ca2c625d9a2c20d18":{
      "scriptId":"u97"},
    "47af1b1f1db84b99a14c3d84f612e8e9":{
      "scriptId":"u98"},
    "40af036674834a86bdda8a04cda901ff":{
      "scriptId":"u99"},
    "a18b6c56d5bb43dcb1fe646178710989":{
      "scriptId":"u100"},
    "3633be8af26d43398e79fe6f5563dd4d":{
      "scriptId":"u101"},
    "ef77f7d70a5c435482103780d9ee7167":{
      "scriptId":"u102"},
    "7e2cd5ae7560477c80f8590362375127":{
      "scriptId":"u103"},
    "9f95ad133e9242219f26477e405c7b28":{
      "scriptId":"u104"},
    "85da388ae8e8413ab46008706e6d7be3":{
      "scriptId":"u105"},
    "360c0a4c3e3144aab7a277b4812d1827":{
      "scriptId":"u106"},
    "15aae8ed559c4fef8d020632b6947888":{
      "scriptId":"u107"},
    "a5a57104c7474517a0e916953332afd4":{
      "scriptId":"u108"},
    "70e4e90eedda43329e5fb4592457c8c0":{
      "scriptId":"u109"},
    "4505e7b0922f4d5a8b062820976764b7":{
      "scriptId":"u110"},
    "57310c21727b47a79dc56a4fe430a6cf":{
      "scriptId":"u111"},
    "5238d977a3584455bd4c1814dab9003c":{
      "scriptId":"u112"},
    "6ca1141e73d742588ae89a6dae505c1b":{
      "scriptId":"u113"},
    "9a08f99cbdd54d59988c6dcd2c0bc442":{
      "scriptId":"u114"},
    "3460ea67c596415090bb1a4b30f535fe":{
      "scriptId":"u115"},
    "d8b7d88350a6472eaf3e2c87915d2b62":{
      "scriptId":"u116"},
    "fdc507b5cab943b78a11011342cd01da":{
      "scriptId":"u117"},
    "92f7f5c8b9ad4115898b3d2cd12beb9c":{
      "scriptId":"u118"},
    "0d0522f994134000a6a56c663b2cdb3e":{
      "scriptId":"u119"},
    "5ee5f612cbb44b4b967591c839fa6f6a":{
      "scriptId":"u120"},
    "3e7829554b3f49328c0dfb0149dc7f10":{
      "scriptId":"u121"},
    "5956cf7adacb4c68969bfe353ca97b2e":{
      "scriptId":"u122"},
    "0ff622d3c9d84a3f958b131051c43d41":{
      "scriptId":"u123"},
    "2079d44b35db4f20ad4e1e45b4d1701e":{
      "scriptId":"u124"},
    "7c1c23b462a74001ac13764e296d1be5":{
      "scriptId":"u125"},
    "049d7b689a5a4849a474079c0eaef5de":{
      "scriptId":"u126"},
    "8f7d8d8f7e9c4cf0bada4b3071788f43":{
      "scriptId":"u127"},
    "9cff79d4d8b148fb9a43d2960a10f420":{
      "scriptId":"u128"},
    "2c63467c871b41ff9ad5277f6ae1e3a7":{
      "scriptId":"u129"},
    "b40b041ecff24a80ab43335f3b2d741b":{
      "scriptId":"u130"},
    "bbd67799e0eb4b14961f3ba92730725a":{
      "scriptId":"u131"},
    "b33e2bbb9f784f14a79643db9ddf9831":{
      "scriptId":"u132"},
    "ad82b8a04eec49899b596c2936d0a1eb":{
      "scriptId":"u133"},
    "c728b147d9684b008350ff143b272a80":{
      "scriptId":"u134"},
    "bd8675b6e74043b0bfe35fda5a8f49eb":{
      "scriptId":"u135"},
    "6b054328b1af4654986d92456df7444c":{
      "scriptId":"u136"},
    "6e3c72923a414735906f290d38b07e30":{
      "scriptId":"u137"},
    "1ef1ceec34e94592820552a605fe6058":{
      "scriptId":"u138"},
    "fb1226424a714156a6d6debd79ca5e85":{
      "scriptId":"u139"},
    "775190b0b202484b8957df20d6e1508a":{
      "scriptId":"u140"},
    "2705aef1d48f4030864f34145f5643bd":{
      "scriptId":"u141"},
    "61d3679b6c4047faae903ddf9178b798":{
      "scriptId":"u142"}}});