$axure.loadCurrentPage({
  "url":"资料详情.html",
  "generationDate":new Date(1397446860772.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c69056cedbdf4fa6b490ef413022a2c2",
    "type":"Axure:Page",
    "name":"资料详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"17bfa2767f024f26bc16ef3b7d2bd3db",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd2ed64d91504e1697cfedcc81bb7c15"},
{
          "id":"73e1f70a054d4748bec285a37c79bd7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":90},
            "size":{
              "width":830,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b78bdc015df4465993e397d5ae27128",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":90},
                "size":{
                  "width":830,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户查询/u185.png"}},
{
          "id":"5d2732a68a614c24a683b0872852a9cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":130},
            "size":{
              "width":830,
              "height":990},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e23a21e615455b948402313de2cfec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":130},
                "size":{
                  "width":830,
                  "height":990},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资料详情/u57.png"}},
{
          "id":"931d137a7508432190a38b08fd53cc10",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":200,
              "y":99},
            "size":{
              "width":111,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e41a62a66954466ab01f7a9096088bf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":99},
                "size":{
                  "width":111,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e194b796039467fa414a0ea4bf5f9de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":224,
              "y":976},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a20811e872d148c38331fd2f2b74affa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":224,
                  "y":976},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2a493d2d1614ab9a61c167c07896bda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":222,
              "y":499},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f21a4e52afd4b6d863a0d69060d5472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":222,
                  "y":499},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c083b7da0b34e95a5ce18a56146aa54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":224,
              "y":1045},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e53271fe12574767bfdaf502bc2af72d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":224,
                  "y":1045},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"523eb6262b9041489b928d52c4033b5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":224,
              "y":1080},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cffd302839d4a9aa053438850e91c7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":224,
                  "y":1080},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59dbb906b5a14eaea1b817234efd7a7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":222,
              "y":183},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a01a95c6cead4469b18f662c110a866c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":222,
                  "y":183},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6b01546f3d744a58e426d4365ccc5dc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":214},
            "size":{
              "width":122,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f81a941b7b84204824b36fe813039b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":299,
                  "y":214},
                "size":{
                  "width":122,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情/u201.png"}},
{
          "id":"96fdb6ac35b743f3b072be38ad2b57d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":222,
              "y":392},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54c6dce329e644819ce0ea0a934b6ba7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":222,
                  "y":392},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99a969b844ff44fda2feebec8fc39f6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":224,
              "y":533},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee8d0ab9d6ba43a09ea1c7541d423a7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":224,
                  "y":533},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"426537dbff194fd38e5044c467010a9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":224,
              "y":570},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f308ba5526c84620818671ad2327225d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":224,
                  "y":570},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c333beca20ff4a4c859e54385c28b5f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":222,
              "y":352},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c69b0d36cacd4d45b6526c9f6b0cbeea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":222,
                  "y":352},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bdb21d0255247a09439add09f6a7b15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":224,
              "y":604},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b1b708f7c8a4a4da8654e505e19848e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":224,
                  "y":604},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d482c7e98fa34ae2b0340b81d15a0e27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":224,
              "y":465},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0040b7dc556e4cdca4120562b92a45c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":224,
                  "y":465},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b393e98f3adf40eaa58d5c867568aac8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":224,
              "y":634},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f290f4039ba4a8087e5af7eb2989aba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":224,
                  "y":634},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"126a35390140402abb4668e8d0107607",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":222,
              "y":213},
            "size":{
              "width":68,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22236cc818b8476f9129e273f19f04dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":222,
                  "y":213},
                "size":{
                  "width":68,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e1225c989ae4625abad3cf8592bc53c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":302,
              "y":742},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f5896a603f24cbfb84426b5bfc9482a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":302,
                  "y":742},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情/u219.png"}},
{
          "id":"1ba2776cf850427bab94e57e60fa0d9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":224,
              "y":742},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7760ee7bc9b2455cb03321d777d1cfa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":224,
                  "y":742},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d211b3cb8b074c318ede620246c62e16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":305,
              "y":976},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c33ade9b548e452dab7980b2777152ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":305,
                  "y":976},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"824b37599dbf429dbd50c4367107a8dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":303,
              "y":499},
            "size":{
              "width":65,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecad7a4396624825982218d604ae47a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":303,
                  "y":499},
                "size":{
                  "width":65,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3888369caf3432db84007752f4d5eb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":305,
              "y":1045},
            "size":{
              "width":132,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07a5f9f5b7fd41bf9010ca4750a44e04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":305,
                  "y":1045},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99f3a569ffc14316b7dad890bef5f020",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":305,
              "y":1080},
            "size":{
              "width":71,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b7fee5569ef416994f853ea91fdf070",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":305,
                  "y":1080},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ab6dbd51b8e4cfc892c58ded67050b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":303,
              "y":183},
            "size":{
              "width":198,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d32f107c4fe4b8485ac93c8bdc99b4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":303,
                  "y":183},
                "size":{
                  "width":198,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a7450ba631f46a2963d295492767392",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":303,
              "y":392},
            "size":{
              "width":62,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83aeea8dd83f4e77906460e28df011c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":303,
                  "y":392},
                "size":{
                  "width":62,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ace858901484e198797abaea30a73b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":305,
              "y":533},
            "size":{
              "width":40,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34c9752dfc6945ff8f6611337763d8d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":305,
                  "y":533},
                "size":{
                  "width":40,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"971c4da5392b4055b7aeab25a1310399",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":305,
              "y":570},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d72bb273ccd431b9fb2829fd05a9d27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":305,
                  "y":570},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b9a1eed4a5541fd89c52558dcda484c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":303,
              "y":352},
            "size":{
              "width":89,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6de0c5a2cf2b420c896093bfd376dc3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":303,
                  "y":352},
                "size":{
                  "width":89,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2dd9ade003e34e42a80ff2cf1aaf1985",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":305,
              "y":604},
            "size":{
              "width":498,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fb6c8650cf946fa85aff89b65db3f12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":305,
                  "y":604},
                "size":{
                  "width":498,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5aa24050ea6841a2ae6973ac84e99ea7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":305,
              "y":465},
            "size":{
              "width":22,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daeb18d3aeb64b39ba347e64fbe523ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":305,
                  "y":465},
                "size":{
                  "width":22,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"482e35b5a20d404f8f2b55283497f316",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":305,
              "y":634},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63cff3beae48449485846da147b415c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":305,
                  "y":634},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97675d596a1e4000a5c7a9c8b375e8c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":479,
              "y":742},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef8c9a256ac5455e84684e36ce293012",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":479,
                  "y":742},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情/u219.png"}},
{
          "id":"408f69067b52414a9a6e119ddeb0b1b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":237,
              "y":1013},
            "size":{
              "width":53,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"072a6e767be841c49b3f713c5ec67cc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":237,
                  "y":1013},
                "size":{
                  "width":53,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d446acfb724a4287af7577ce05d43269",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":305,
              "y":1013},
            "size":{
              "width":40,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd8c8976b5ef4aa7a9946b2bffad3b12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":305,
                  "y":1013},
                "size":{
                  "width":40,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79dea2b614fa4c7aa7a2ecc1c408b032",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "location":{
              "x":224,
              "y":931},
            "size":{
              "width":91,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5310709a7fa4f04bf746d56f3c26adf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "location":{
                  "x":224,
                  "y":931},
                "size":{
                  "width":91,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"544d017c5602468691388366aeb549a2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":956},
            "size":{
              "width":91,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户详情/u256_line.png"}},
{
          "id":"101adb1a01d24c26ae92b001f867c873",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"left",
            "location":{
              "x":221,
              "y":143},
            "size":{
              "width":65,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dc46a7ca65445769fa03c87974bf038",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"left",
                "location":{
                  "x":221,
                  "y":143},
                "size":{
                  "width":65,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12f0279ed1c14c1db1dc7401a65c7099",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":163},
            "size":{
              "width":92,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户详情/u259_line.png"}},
{
          "id":"7d81c873ca9943c4b4ad0d30812d9a4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":222,
              "y":429},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00b461194bb94dfdb84ed699a897bd5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":222,
                  "y":429},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddaccb6ee655441eba4228020e5d000e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":305,
              "y":429},
            "size":{
              "width":95,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e47f3a9c93c4f0998f534e7a7bb0bdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":305,
                  "y":429},
                "size":{
                  "width":95,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "fd2ed64d91504e1697cfedcc81bb7c15":{
      "packageId":"fd2ed64d91504e1697cfedcc81bb7c15",
      "type":"Axure:Master",
      "name":"商户头部/导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3496b00b35034b57afc56e9131fd79c0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "size":{
                "width":1120,
                "height":80},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4603d49a56b5439fa4b8c19626b2e607",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "size":{
                    "width":1120,
                    "height":80},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/商户查询/u1.png"}},
{
            "id":"fa64700b64d44c10b00935db2997f877",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":225,
                "y":6},
              "size":{
                "width":10,
                "height":69},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/商户查询/u3_line.png"}},
{
            "id":"6943a575259842e1a7218e907b8f643c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "horizontalAlignment":"left",
              "location":{
                "x":245,
                "y":30},
              "size":{
                "width":255,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8ba9b90728b24bf88f157567f6b88f5c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "horizontalAlignment":"left",
                  "location":{
                    "x":245,
                    "y":30},
                  "size":{
                    "width":255,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"245deaa9b7bf403ba8f15a6357adc6d9",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":7.5},
              "size":{
                "width":191,
                "height":65}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a81ac0dfa8e4995bd264cb1e72a78dd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":7.5},
                  "size":{
                    "width":191,
                    "height":65}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u9.jpg"}},
{
            "id":"de415f578919453bb879d24845e0589c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":90},
              "size":{
                "width":160,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e6c3b471cff14a4bac7999e4a18e5971",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":90},
                  "size":{
                    "width":160,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/优惠券核销/u8.png"}},
{
            "id":"5989ad95f5e94eaca47a761e9ea92ae0",
            "label":"",
            "type":"treeNodeObject",
            "styleType":"treeNodeObject",
            "visible":true,
            "style":{
              "location":{
                "x":11,
                "y":100},
              "size":{
                "width":133,
                "height":140}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8497bdc2d4424272885751235658c3e8",
                "label":"",
                "type":"treeNodeObject",
                "styleType":"treeNodeObject",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":80},
                  "size":{
                    "width":100,
                    "height":20}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"70911644b44447e28a6258516905a906",
                    "label":"",
                    "isContained":true,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6fe081f0b5374bc0a4301cb57ac17e44",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"e8bce3a182a6417a98605df8656f04f4",
                    "label":"",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "stateStyles":{
                        "selected":{
}},
                      "location":{
                        "x":6,
                        "y":6},
                      "size":{
                        "width":9,
                        "height":9}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"27d4b56981634d3d8906b66df51d4e1d",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "stateStyles":{
                            "selected":{
}},
                          "location":{
                            "x":6,
                            "y":6},
                          "size":{
                            "width":9,
                            "height":9}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "selected~":"resources/images/transparent.gif"}},
{
                    "id":"aff2c4678a7d4bfc9f016cc465e192ca",
                    "label":"",
                    "type":"treeNodeObject",
                    "styleType":"treeNodeObject",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":40},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5ff24eb2c76a45179dac16f817ab4cca",
                        "label":"",
                        "isContained":true,
                        "type":"buttonShape",
                        "styleType":"buttonShape",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":20,
                            "y":40},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"9b2908efa67c4ffd8380396eb1d1bbae",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":20,
                                "y":40},
                              "size":{
                                "width":100,
                                "height":20}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"f016c2b02a07436e89c1e46df00c457a",
                        "label":"",
                        "type":"imageBox",
                        "styleType":"imageBox",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":22,
                            "y":2},
                          "size":{
                            "width":16,
                            "height":16}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"17ffde6c99d04c3b85f3e17c51525457",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":22,
                                "y":2},
                              "size":{
                                "width":16,
                                "height":16}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/商户查询/u19.jpg"}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 修改密码",
                                "target":{
                                  "targetType":"page",
                                  "url":"修改密码.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "buttonShapeId":"5ff24eb2c76a45179dac16f817ab4cca"},
{
                    "id":"c8902245a2bd4317a17831f735fffa08",
                    "label":"",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":22,
                        "y":2},
                      "size":{
                        "width":16,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6ec97ba9b9c5423db31690828c313cb5",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":22,
                            "y":2},
                          "size":{
                            "width":16,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/商户查询/u14.jpg"}},
{
                    "id":"b08f075ec4d442f99d4b9299bca23294",
                    "label":"",
                    "type":"treeNodeObject",
                    "styleType":"treeNodeObject",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":20},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e94424006956408b9e13dcfa740b9c3f",
                        "label":"",
                        "isContained":true,
                        "type":"buttonShape",
                        "styleType":"buttonShape",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":20,
                            "y":20},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"9d56da7c1e5b4db583741e2b5b450483",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":20,
                                "y":20},
                              "size":{
                                "width":100,
                                "height":20}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"7d6346c252d941b0b4afc0252b02e9a1",
                        "label":"",
                        "type":"imageBox",
                        "styleType":"imageBox",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":22,
                            "y":2},
                          "size":{
                            "width":16,
                            "height":16}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"7bb81d90afe944c885faf87bc627acef",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":22,
                                "y":2},
                              "size":{
                                "width":16,
                                "height":16}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/商户查询/u19.jpg"}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 资料详情",
                                "target":{
                                  "targetType":"page",
                                  "url":"资料详情.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "buttonShapeId":"e94424006956408b9e13dcfa740b9c3f"}],
                "buttonShapeId":"70911644b44447e28a6258516905a906"},
{
                "id":"fb09953f7b0e4ea0bbda91e258db1c66",
                "label":"",
                "type":"treeNodeObject",
                "styleType":"treeNodeObject",
                "visible":true,
                "style":{
                  "size":{
                    "width":113,
                    "height":20}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"7772b4d299064b7f872beb100376ba9d",
                    "label":"",
                    "isContained":true,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":113,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9e3d9b82e5b24eb69ef4335005433584",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":113,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"abd089bcd0ed44cbbcb78eac530b0b56",
                    "label":"",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":22,
                        "y":2},
                      "size":{
                        "width":16,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1be38d2f55f64362969943591a6694b1",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":22,
                            "y":2},
                          "size":{
                            "width":16,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/商户查询/u14.jpg"}},
{
                    "id":"b36bdea43e3645b1a813e9e62ff1699a",
                    "label":"",
                    "type":"treeNodeObject",
                    "styleType":"treeNodeObject",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":20},
                      "size":{
                        "width":113,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d1fe3005fb964a778c1040df1537e457",
                        "label":"",
                        "isContained":true,
                        "type":"buttonShape",
                        "styleType":"buttonShape",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":20,
                            "y":20},
                          "size":{
                            "width":113,
                            "height":20}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"82775adbcead42a4a56c5ddfc115d6af",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":20,
                                "y":20},
                              "size":{
                                "width":113,
                                "height":20}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"0c3bb24069774494b2f1c99e15abcec4",
                        "label":"",
                        "type":"imageBox",
                        "styleType":"imageBox",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":22,
                            "y":2},
                          "size":{
                            "width":16,
                            "height":16}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"76ce82834ed74d349c0a81b22bb28e37",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":22,
                                "y":2},
                              "size":{
                                "width":16,
                                "height":16}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/商户查询/u19.jpg"}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 优惠券核销",
                                "target":{
                                  "targetType":"page",
                                  "url":"优惠券核销.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "buttonShapeId":"d1fe3005fb964a778c1040df1537e457"},
{
                    "id":"75becb34fe3746ec822a4ca9ad4e7cf9",
                    "label":"",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "stateStyles":{
                        "selected":{
}},
                      "location":{
                        "x":6,
                        "y":6},
                      "size":{
                        "width":9,
                        "height":9}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"39829b1bb34a4e6489888a31b210d3e4",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "stateStyles":{
                            "selected":{
}},
                          "location":{
                            "x":6,
                            "y":6},
                          "size":{
                            "width":9,
                            "height":9}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "selected~":"resources/images/transparent.gif"}},
{
                    "id":"6807ad83c47042d592d00aaef804e107",
                    "label":"",
                    "type":"treeNodeObject",
                    "styleType":"treeNodeObject",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":40},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f5d5eb2602b848aaa3159479f2a4a87e",
                        "label":"",
                        "isContained":true,
                        "type":"buttonShape",
                        "styleType":"buttonShape",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":20,
                            "y":40},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"73faa387ce5c4713805235184fe0a896",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":20,
                                "y":40},
                              "size":{
                                "width":100,
                                "height":20}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"046bc3b6629d4766a90a6eb5dfaee9b4",
                        "label":"",
                        "type":"imageBox",
                        "styleType":"imageBox",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":22,
                            "y":2},
                          "size":{
                            "width":16,
                            "height":16}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"08995a10ea804dbcb74fdd5f37c6f89f",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":22,
                                "y":2},
                              "size":{
                                "width":16,
                                "height":16}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/商户查询/u19.jpg"}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 核销记录",
                                "target":{
                                  "targetType":"page",
                                  "url":"核销记录.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "buttonShapeId":"f5d5eb2602b848aaa3159479f2a4a87e"},
{
                    "id":"140424ac5fb24e369f8d7ff2f7e07f16",
                    "label":"",
                    "type":"treeNodeObject",
                    "styleType":"treeNodeObject",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":60},
                      "size":{
                        "width":113,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c4576ec839ef43cba6525837898ac958",
                        "label":"",
                        "isContained":true,
                        "type":"buttonShape",
                        "styleType":"buttonShape",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":20,
                            "y":60},
                          "size":{
                            "width":113,
                            "height":20}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"e68100e47d764f9d8d0107dee47f69b9",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":20,
                                "y":60},
                              "size":{
                                "width":113,
                                "height":20}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"eb58aae334184a19a6200aefea62d7d9",
                        "label":"",
                        "type":"imageBox",
                        "styleType":"imageBox",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":22,
                            "y":2},
                          "size":{
                            "width":16,
                            "height":16}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"ccd89857d0b44deb967f3ca2d8c790da",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":22,
                                "y":2},
                              "size":{
                                "width":16,
                                "height":16}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/商户查询/u19.jpg"}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 优惠券统计",
                                "target":{
                                  "targetType":"page",
                                  "url":"优惠券统计_1.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "buttonShapeId":"c4576ec839ef43cba6525837898ac958"}],
                "buttonShapeId":"7772b4d299064b7f872beb100376ba9d"}]},
{
            "id":"ad52c8626bf04bed910ea16482f2d73d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":650,
                "y":30},
              "size":{
                "width":180,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f92bde778ffe416bae184d3308e3d1c6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":650,
                    "y":30},
                  "size":{
                    "width":180,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "annotation":{
              "描述":"为商户的名称"},
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0eaa0ee222d34512afb4e0018dd9f1b3",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":950,
                "y":27.5},
              "size":{
                "width":70,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"46154375d8464b578b63e60778d6cebb",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":850,
                "y":30},
              "size":{
                "width":90,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f69096f40a52497499b8df57169f2dad",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":850,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "annotation":{
              "描述":"登陆账号名称"},
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "17bfa2767f024f26bc16ef3b7d2bd3db":{
      "scriptId":"u0",
      "3496b00b35034b57afc56e9131fd79c0":{
        "scriptId":"u1"},
      "4603d49a56b5439fa4b8c19626b2e607":{
        "scriptId":"u2"},
      "fa64700b64d44c10b00935db2997f877":{
        "scriptId":"u3"},
      "6943a575259842e1a7218e907b8f643c":{
        "scriptId":"u4"},
      "8ba9b90728b24bf88f157567f6b88f5c":{
        "scriptId":"u5"},
      "245deaa9b7bf403ba8f15a6357adc6d9":{
        "scriptId":"u6"},
      "8a81ac0dfa8e4995bd264cb1e72a78dd":{
        "scriptId":"u7"},
      "de415f578919453bb879d24845e0589c":{
        "scriptId":"u8"},
      "e6c3b471cff14a4bac7999e4a18e5971":{
        "scriptId":"u9"},
      "5989ad95f5e94eaca47a761e9ea92ae0":{
        "scriptId":"u10"},
      "fb09953f7b0e4ea0bbda91e258db1c66":{
        "scriptId":"u11"},
      "75becb34fe3746ec822a4ca9ad4e7cf9":{
        "scriptId":"u12"},
      "39829b1bb34a4e6489888a31b210d3e4":{
        "scriptId":"u13"},
      "abd089bcd0ed44cbbcb78eac530b0b56":{
        "scriptId":"u14"},
      "1be38d2f55f64362969943591a6694b1":{
        "scriptId":"u15"},
      "7772b4d299064b7f872beb100376ba9d":{
        "scriptId":"u16"},
      "9e3d9b82e5b24eb69ef4335005433584":{
        "scriptId":"u17"},
      "b36bdea43e3645b1a813e9e62ff1699a":{
        "scriptId":"u18"},
      "0c3bb24069774494b2f1c99e15abcec4":{
        "scriptId":"u19"},
      "76ce82834ed74d349c0a81b22bb28e37":{
        "scriptId":"u20"},
      "d1fe3005fb964a778c1040df1537e457":{
        "scriptId":"u21"},
      "82775adbcead42a4a56c5ddfc115d6af":{
        "scriptId":"u22"},
      "6807ad83c47042d592d00aaef804e107":{
        "scriptId":"u23"},
      "046bc3b6629d4766a90a6eb5dfaee9b4":{
        "scriptId":"u24"},
      "08995a10ea804dbcb74fdd5f37c6f89f":{
        "scriptId":"u25"},
      "f5d5eb2602b848aaa3159479f2a4a87e":{
        "scriptId":"u26"},
      "73faa387ce5c4713805235184fe0a896":{
        "scriptId":"u27"},
      "140424ac5fb24e369f8d7ff2f7e07f16":{
        "scriptId":"u28"},
      "eb58aae334184a19a6200aefea62d7d9":{
        "scriptId":"u29"},
      "ccd89857d0b44deb967f3ca2d8c790da":{
        "scriptId":"u30"},
      "c4576ec839ef43cba6525837898ac958":{
        "scriptId":"u31"},
      "e68100e47d764f9d8d0107dee47f69b9":{
        "scriptId":"u32"},
      "8497bdc2d4424272885751235658c3e8":{
        "scriptId":"u33"},
      "e8bce3a182a6417a98605df8656f04f4":{
        "scriptId":"u34"},
      "27d4b56981634d3d8906b66df51d4e1d":{
        "scriptId":"u35"},
      "c8902245a2bd4317a17831f735fffa08":{
        "scriptId":"u36"},
      "6ec97ba9b9c5423db31690828c313cb5":{
        "scriptId":"u37"},
      "70911644b44447e28a6258516905a906":{
        "scriptId":"u38"},
      "6fe081f0b5374bc0a4301cb57ac17e44":{
        "scriptId":"u39"},
      "b08f075ec4d442f99d4b9299bca23294":{
        "scriptId":"u40"},
      "7d6346c252d941b0b4afc0252b02e9a1":{
        "scriptId":"u41"},
      "7bb81d90afe944c885faf87bc627acef":{
        "scriptId":"u42"},
      "e94424006956408b9e13dcfa740b9c3f":{
        "scriptId":"u43"},
      "9d56da7c1e5b4db583741e2b5b450483":{
        "scriptId":"u44"},
      "aff2c4678a7d4bfc9f016cc465e192ca":{
        "scriptId":"u45"},
      "f016c2b02a07436e89c1e46df00c457a":{
        "scriptId":"u46"},
      "17ffde6c99d04c3b85f3e17c51525457":{
        "scriptId":"u47"},
      "5ff24eb2c76a45179dac16f817ab4cca":{
        "scriptId":"u48"},
      "9b2908efa67c4ffd8380396eb1d1bbae":{
        "scriptId":"u49"},
      "ad52c8626bf04bed910ea16482f2d73d":{
        "scriptId":"u50"},
      "f92bde778ffe416bae184d3308e3d1c6":{
        "scriptId":"u51"},
      "0eaa0ee222d34512afb4e0018dd9f1b3":{
        "scriptId":"u52"},
      "46154375d8464b578b63e60778d6cebb":{
        "scriptId":"u53"},
      "f69096f40a52497499b8df57169f2dad":{
        "scriptId":"u54"}},
    "73e1f70a054d4748bec285a37c79bd7e":{
      "scriptId":"u55"},
    "2b78bdc015df4465993e397d5ae27128":{
      "scriptId":"u56"},
    "5d2732a68a614c24a683b0872852a9cb":{
      "scriptId":"u57"},
    "67e23a21e615455b948402313de2cfec":{
      "scriptId":"u58"},
    "931d137a7508432190a38b08fd53cc10":{
      "scriptId":"u59"},
    "e41a62a66954466ab01f7a9096088bf8":{
      "scriptId":"u60"},
    "4e194b796039467fa414a0ea4bf5f9de":{
      "scriptId":"u61"},
    "a20811e872d148c38331fd2f2b74affa":{
      "scriptId":"u62"},
    "a2a493d2d1614ab9a61c167c07896bda":{
      "scriptId":"u63"},
    "1f21a4e52afd4b6d863a0d69060d5472":{
      "scriptId":"u64"},
    "0c083b7da0b34e95a5ce18a56146aa54":{
      "scriptId":"u65"},
    "e53271fe12574767bfdaf502bc2af72d":{
      "scriptId":"u66"},
    "523eb6262b9041489b928d52c4033b5e":{
      "scriptId":"u67"},
    "6cffd302839d4a9aa053438850e91c7a":{
      "scriptId":"u68"},
    "59dbb906b5a14eaea1b817234efd7a7c":{
      "scriptId":"u69"},
    "a01a95c6cead4469b18f662c110a866c":{
      "scriptId":"u70"},
    "c6b01546f3d744a58e426d4365ccc5dc":{
      "scriptId":"u71"},
    "8f81a941b7b84204824b36fe813039b1":{
      "scriptId":"u72"},
    "96fdb6ac35b743f3b072be38ad2b57d8":{
      "scriptId":"u73"},
    "54c6dce329e644819ce0ea0a934b6ba7":{
      "scriptId":"u74"},
    "99a969b844ff44fda2feebec8fc39f6f":{
      "scriptId":"u75"},
    "ee8d0ab9d6ba43a09ea1c7541d423a7a":{
      "scriptId":"u76"},
    "426537dbff194fd38e5044c467010a9a":{
      "scriptId":"u77"},
    "f308ba5526c84620818671ad2327225d":{
      "scriptId":"u78"},
    "c333beca20ff4a4c859e54385c28b5f7":{
      "scriptId":"u79"},
    "c69b0d36cacd4d45b6526c9f6b0cbeea":{
      "scriptId":"u80"},
    "4bdb21d0255247a09439add09f6a7b15":{
      "scriptId":"u81"},
    "8b1b708f7c8a4a4da8654e505e19848e":{
      "scriptId":"u82"},
    "d482c7e98fa34ae2b0340b81d15a0e27":{
      "scriptId":"u83"},
    "0040b7dc556e4cdca4120562b92a45c9":{
      "scriptId":"u84"},
    "b393e98f3adf40eaa58d5c867568aac8":{
      "scriptId":"u85"},
    "3f290f4039ba4a8087e5af7eb2989aba":{
      "scriptId":"u86"},
    "126a35390140402abb4668e8d0107607":{
      "scriptId":"u87"},
    "22236cc818b8476f9129e273f19f04dd":{
      "scriptId":"u88"},
    "3e1225c989ae4625abad3cf8592bc53c":{
      "scriptId":"u89"},
    "6f5896a603f24cbfb84426b5bfc9482a":{
      "scriptId":"u90"},
    "1ba2776cf850427bab94e57e60fa0d9f":{
      "scriptId":"u91"},
    "7760ee7bc9b2455cb03321d777d1cfa9":{
      "scriptId":"u92"},
    "d211b3cb8b074c318ede620246c62e16":{
      "scriptId":"u93"},
    "c33ade9b548e452dab7980b2777152ca":{
      "scriptId":"u94"},
    "824b37599dbf429dbd50c4367107a8dd":{
      "scriptId":"u95"},
    "ecad7a4396624825982218d604ae47a5":{
      "scriptId":"u96"},
    "b3888369caf3432db84007752f4d5eb8":{
      "scriptId":"u97"},
    "07a5f9f5b7fd41bf9010ca4750a44e04":{
      "scriptId":"u98"},
    "99f3a569ffc14316b7dad890bef5f020":{
      "scriptId":"u99"},
    "8b7fee5569ef416994f853ea91fdf070":{
      "scriptId":"u100"},
    "1ab6dbd51b8e4cfc892c58ded67050b1":{
      "scriptId":"u101"},
    "0d32f107c4fe4b8485ac93c8bdc99b4f":{
      "scriptId":"u102"},
    "9a7450ba631f46a2963d295492767392":{
      "scriptId":"u103"},
    "83aeea8dd83f4e77906460e28df011c1":{
      "scriptId":"u104"},
    "0ace858901484e198797abaea30a73b3":{
      "scriptId":"u105"},
    "34c9752dfc6945ff8f6611337763d8d3":{
      "scriptId":"u106"},
    "971c4da5392b4055b7aeab25a1310399":{
      "scriptId":"u107"},
    "5d72bb273ccd431b9fb2829fd05a9d27":{
      "scriptId":"u108"},
    "6b9a1eed4a5541fd89c52558dcda484c":{
      "scriptId":"u109"},
    "6de0c5a2cf2b420c896093bfd376dc3d":{
      "scriptId":"u110"},
    "2dd9ade003e34e42a80ff2cf1aaf1985":{
      "scriptId":"u111"},
    "7fb6c8650cf946fa85aff89b65db3f12":{
      "scriptId":"u112"},
    "5aa24050ea6841a2ae6973ac84e99ea7":{
      "scriptId":"u113"},
    "daeb18d3aeb64b39ba347e64fbe523ab":{
      "scriptId":"u114"},
    "482e35b5a20d404f8f2b55283497f316":{
      "scriptId":"u115"},
    "63cff3beae48449485846da147b415c9":{
      "scriptId":"u116"},
    "97675d596a1e4000a5c7a9c8b375e8c4":{
      "scriptId":"u117"},
    "ef8c9a256ac5455e84684e36ce293012":{
      "scriptId":"u118"},
    "408f69067b52414a9a6e119ddeb0b1b7":{
      "scriptId":"u119"},
    "072a6e767be841c49b3f713c5ec67cc0":{
      "scriptId":"u120"},
    "d446acfb724a4287af7577ce05d43269":{
      "scriptId":"u121"},
    "bd8c8976b5ef4aa7a9946b2bffad3b12":{
      "scriptId":"u122"},
    "79dea2b614fa4c7aa7a2ecc1c408b032":{
      "scriptId":"u123"},
    "b5310709a7fa4f04bf746d56f3c26adf":{
      "scriptId":"u124"},
    "544d017c5602468691388366aeb549a2":{
      "scriptId":"u125"},
    "101adb1a01d24c26ae92b001f867c873":{
      "scriptId":"u126"},
    "4dc46a7ca65445769fa03c87974bf038":{
      "scriptId":"u127"},
    "12f0279ed1c14c1db1dc7401a65c7099":{
      "scriptId":"u128"},
    "7d81c873ca9943c4b4ad0d30812d9a4a":{
      "scriptId":"u129"},
    "00b461194bb94dfdb84ed699a897bd5a":{
      "scriptId":"u130"},
    "ddaccb6ee655441eba4228020e5d000e":{
      "scriptId":"u131"},
    "4e47f3a9c93c4f0998f534e7a7bb0bdb":{
      "scriptId":"u132"}}});