$axure.loadCurrentPage({
  "url":"手机版网址导航.html",
  "generationDate":new Date(1404796804649.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"82f4c910f32641779a7376d50d0ec5d1",
    "type":"Axure:Page",
    "name":"手机版网址导航",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e5811f7c4a29401082e7c4a4b60fd237",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":310,
              "height":550}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d31bc29f224c4733a74ecd7d104825ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":310,
                  "height":550}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首界面/u0.jpg"}},
{
          "id":"655829c70a294428bca2af4e0a256559",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE9EAEF},
            "location":{
              "x":20,
              "y":74},
            "size":{
              "width":309,
              "height":440},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb9cbd5845a84de195331063f0bf881b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE9EAEF},
                "location":{
                  "x":20,
                  "y":74},
                "size":{
                  "width":309,
                  "height":440},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首界面/u2.png"}},
{
          "id":"cddcf583e06a4557bebecb43d8ad308a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":94},
            "size":{
              "width":275,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db339523c3c94c2796614543e6453540",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":37,
                  "y":94},
                "size":{
                  "width":275,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机版网址导航/u4.png"}},
{
          "id":"d936a1ef765944c48883386202615a30",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":182},
            "size":{
              "width":299,
              "height":168}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"261ee25212644b48b2efc3609a6f2f4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":182},
                "size":{
                  "width":299,
                  "height":168}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机版网址导航/u6.png"}},
{
          "id":"20b79541f591462a8c023a566d0f4e48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":30,
              "y":160},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d6ea589162427eb7afecf5f1c22da0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":30,
                  "y":160},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7082021af1074c2bbe26d03799ac42cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":346},
            "size":{
              "width":299,
              "height":168}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19eccaa950004b3a95b6b6cd88d25c58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":346},
                "size":{
                  "width":299,
                  "height":168}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机版网址导航/u6.png"}},
{
          "id":"7509e649ab294d2080555acb5afea6c4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":165},
            "size":{
              "width":256,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/登陆成功（分享注册）/u12_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机版网址导航/u12_line.png"}},
{
          "id":"bcfd1c61e9084b46b39b886634c14255",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":370,
              "y":160},
            "size":{
              "width":136,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aadb69daacc4ce1bb39cbe4991ee5b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":370,
                  "y":160},
                "size":{
                  "width":136,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e5811f7c4a29401082e7c4a4b60fd237":{
      "scriptId":"u0"},
    "d31bc29f224c4733a74ecd7d104825ff":{
      "scriptId":"u1"},
    "655829c70a294428bca2af4e0a256559":{
      "scriptId":"u2"},
    "cb9cbd5845a84de195331063f0bf881b":{
      "scriptId":"u3"},
    "cddcf583e06a4557bebecb43d8ad308a":{
      "scriptId":"u4"},
    "db339523c3c94c2796614543e6453540":{
      "scriptId":"u5"},
    "d936a1ef765944c48883386202615a30":{
      "scriptId":"u6"},
    "261ee25212644b48b2efc3609a6f2f4f":{
      "scriptId":"u7"},
    "20b79541f591462a8c023a566d0f4e48":{
      "scriptId":"u8"},
    "b9d6ea589162427eb7afecf5f1c22da0":{
      "scriptId":"u9"},
    "7082021af1074c2bbe26d03799ac42cf":{
      "scriptId":"u10"},
    "19eccaa950004b3a95b6b6cd88d25c58":{
      "scriptId":"u11"},
    "7509e649ab294d2080555acb5afea6c4":{
      "scriptId":"u12"},
    "bcfd1c61e9084b46b39b886634c14255":{
      "scriptId":"u13"},
    "0aadb69daacc4ce1bb39cbe4991ee5b4":{
      "scriptId":"u14"}}});