$axure.loadCurrentPage({
  "url":"修改密码.html",
  "generationDate":new Date(1397446860912.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f831dbdb275f46f2a81d185826e8eb26",
    "type":"Axure:Page",
    "name":"修改密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"813a3a95268e48429a354c8cce8f71e4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd2ed64d91504e1697cfedcc81bb7c15"},
{
          "id":"3e32fabea66a41a8b25e1fe47ff02c8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":130},
            "size":{
              "width":830,
              "height":440},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ddddd8ecb3245e98a09c9b1375f474c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":130},
                "size":{
                  "width":830,
                  "height":440},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/核销记录/u55.png"}},
{
          "id":"c9f83d4bb10c4d93be109288d7da6581",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":90},
            "size":{
              "width":830,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3afd877058364d90aa12dd9a20539ab8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":90},
                "size":{
                  "width":830,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户查询/u185.png"}},
{
          "id":"1c07d0ce04554e35a2aa0564aeb90602",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":200,
              "y":99},
            "size":{
              "width":220,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5559a04087664e02abc6899bd340eacb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":99},
                "size":{
                  "width":220,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d732831cf6754041881b0e2089abec1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"right",
            "location":{
              "x":410,
              "y":230},
            "size":{
              "width":102,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f02180fae10144f39a56bada937c698a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"right",
                "location":{
                  "x":410,
                  "y":230},
                "size":{
                  "width":102,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe47964c220a4e2cbce6c29e14065936",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":510.5,
              "y":228},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"977f62cdbfca45d08d5ef03cf63217b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"right",
            "location":{
              "x":421,
              "y":272},
            "size":{
              "width":89,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faa432012fa6494d9cfe1e324263a00f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"right",
                "location":{
                  "x":421,
                  "y":272},
                "size":{
                  "width":89,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"459739a805134323b18b37c2b3f6d193",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":510.5,
              "y":270},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"adf223cb616c4571aee74ad513fcdefc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"right",
            "location":{
              "x":410,
              "y":317},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bd54f460c454c6ba5d3154e6737b10d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"right",
                "location":{
                  "x":410,
                  "y":317},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1fa225d7968467dade784eed0822f7a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":510.5,
              "y":315},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d99419bd92dc4f37bf96f6edfda0527a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":405},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "fd2ed64d91504e1697cfedcc81bb7c15":{
      "packageId":"fd2ed64d91504e1697cfedcc81bb7c15",
      "type":"Axure:Master",
      "name":"商户头部/导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3496b00b35034b57afc56e9131fd79c0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "size":{
                "width":1120,
                "height":80},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4603d49a56b5439fa4b8c19626b2e607",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "size":{
                    "width":1120,
                    "height":80},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/商户查询/u1.png"}},
{
            "id":"fa64700b64d44c10b00935db2997f877",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":225,
                "y":6},
              "size":{
                "width":10,
                "height":69},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/商户查询/u3_line.png"}},
{
            "id":"6943a575259842e1a7218e907b8f643c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "horizontalAlignment":"left",
              "location":{
                "x":245,
                "y":30},
              "size":{
                "width":255,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8ba9b90728b24bf88f157567f6b88f5c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "horizontalAlignment":"left",
                  "location":{
                    "x":245,
                    "y":30},
                  "size":{
                    "width":255,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"245deaa9b7bf403ba8f15a6357adc6d9",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":7.5},
              "size":{
                "width":191,
                "height":65}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a81ac0dfa8e4995bd264cb1e72a78dd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":7.5},
                  "size":{
                    "width":191,
                    "height":65}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u9.jpg"}},
{
            "id":"de415f578919453bb879d24845e0589c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":90},
              "size":{
                "width":160,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e6c3b471cff14a4bac7999e4a18e5971",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":90},
                  "size":{
                    "width":160,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/优惠券核销/u8.png"}},
{
            "id":"5989ad95f5e94eaca47a761e9ea92ae0",
            "label":"",
            "type":"treeNodeObject",
            "styleType":"treeNodeObject",
            "visible":true,
            "style":{
              "location":{
                "x":11,
                "y":100},
              "size":{
                "width":133,
                "height":140}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8497bdc2d4424272885751235658c3e8",
                "label":"",
                "type":"treeNodeObject",
                "styleType":"treeNodeObject",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":80},
                  "size":{
                    "width":100,
                    "height":20}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"70911644b44447e28a6258516905a906",
                    "label":"",
                    "isContained":true,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6fe081f0b5374bc0a4301cb57ac17e44",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"e8bce3a182a6417a98605df8656f04f4",
                    "label":"",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "stateStyles":{
                        "selected":{
}},
                      "location":{
                        "x":6,
                        "y":6},
                      "size":{
                        "width":9,
                        "height":9}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"27d4b56981634d3d8906b66df51d4e1d",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "stateStyles":{
                            "selected":{
}},
                          "location":{
                            "x":6,
                            "y":6},
                          "size":{
                            "width":9,
                            "height":9}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "selected~":"resources/images/transparent.gif"}},
{
                    "id":"aff2c4678a7d4bfc9f016cc465e192ca",
                    "label":"",
                    "type":"treeNodeObject",
                    "styleType":"treeNodeObject",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":40},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5ff24eb2c76a45179dac16f817ab4cca",
                        "label":"",
                        "isContained":true,
                        "type":"buttonShape",
                        "styleType":"buttonShape",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":20,
                            "y":40},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"9b2908efa67c4ffd8380396eb1d1bbae",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":20,
                                "y":40},
                              "size":{
                                "width":100,
                                "height":20}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"f016c2b02a07436e89c1e46df00c457a",
                        "label":"",
                        "type":"imageBox",
                        "styleType":"imageBox",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":22,
                            "y":2},
                          "size":{
                            "width":16,
                            "height":16}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"17ffde6c99d04c3b85f3e17c51525457",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":22,
                                "y":2},
                              "size":{
                                "width":16,
                                "height":16}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/商户查询/u19.jpg"}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 修改密码",
                                "target":{
                                  "targetType":"page",
                                  "url":"修改密码.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "buttonShapeId":"5ff24eb2c76a45179dac16f817ab4cca"},
{
                    "id":"c8902245a2bd4317a17831f735fffa08",
                    "label":"",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":22,
                        "y":2},
                      "size":{
                        "width":16,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6ec97ba9b9c5423db31690828c313cb5",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":22,
                            "y":2},
                          "size":{
                            "width":16,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/商户查询/u14.jpg"}},
{
                    "id":"b08f075ec4d442f99d4b9299bca23294",
                    "label":"",
                    "type":"treeNodeObject",
                    "styleType":"treeNodeObject",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":20},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e94424006956408b9e13dcfa740b9c3f",
                        "label":"",
                        "isContained":true,
                        "type":"buttonShape",
                        "styleType":"buttonShape",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":20,
                            "y":20},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"9d56da7c1e5b4db583741e2b5b450483",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":20,
                                "y":20},
                              "size":{
                                "width":100,
                                "height":20}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"7d6346c252d941b0b4afc0252b02e9a1",
                        "label":"",
                        "type":"imageBox",
                        "styleType":"imageBox",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":22,
                            "y":2},
                          "size":{
                            "width":16,
                            "height":16}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"7bb81d90afe944c885faf87bc627acef",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":22,
                                "y":2},
                              "size":{
                                "width":16,
                                "height":16}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/商户查询/u19.jpg"}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 资料详情",
                                "target":{
                                  "targetType":"page",
                                  "url":"资料详情.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "buttonShapeId":"e94424006956408b9e13dcfa740b9c3f"}],
                "buttonShapeId":"70911644b44447e28a6258516905a906"},
{
                "id":"fb09953f7b0e4ea0bbda91e258db1c66",
                "label":"",
                "type":"treeNodeObject",
                "styleType":"treeNodeObject",
                "visible":true,
                "style":{
                  "size":{
                    "width":113,
                    "height":20}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"7772b4d299064b7f872beb100376ba9d",
                    "label":"",
                    "isContained":true,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":113,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9e3d9b82e5b24eb69ef4335005433584",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":113,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"abd089bcd0ed44cbbcb78eac530b0b56",
                    "label":"",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":22,
                        "y":2},
                      "size":{
                        "width":16,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1be38d2f55f64362969943591a6694b1",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":22,
                            "y":2},
                          "size":{
                            "width":16,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/商户查询/u14.jpg"}},
{
                    "id":"b36bdea43e3645b1a813e9e62ff1699a",
                    "label":"",
                    "type":"treeNodeObject",
                    "styleType":"treeNodeObject",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":20},
                      "size":{
                        "width":113,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d1fe3005fb964a778c1040df1537e457",
                        "label":"",
                        "isContained":true,
                        "type":"buttonShape",
                        "styleType":"buttonShape",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":20,
                            "y":20},
                          "size":{
                            "width":113,
                            "height":20}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"82775adbcead42a4a56c5ddfc115d6af",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":20,
                                "y":20},
                              "size":{
                                "width":113,
                                "height":20}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"0c3bb24069774494b2f1c99e15abcec4",
                        "label":"",
                        "type":"imageBox",
                        "styleType":"imageBox",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":22,
                            "y":2},
                          "size":{
                            "width":16,
                            "height":16}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"76ce82834ed74d349c0a81b22bb28e37",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":22,
                                "y":2},
                              "size":{
                                "width":16,
                                "height":16}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/商户查询/u19.jpg"}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 优惠券核销",
                                "target":{
                                  "targetType":"page",
                                  "url":"优惠券核销.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "buttonShapeId":"d1fe3005fb964a778c1040df1537e457"},
{
                    "id":"75becb34fe3746ec822a4ca9ad4e7cf9",
                    "label":"",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "stateStyles":{
                        "selected":{
}},
                      "location":{
                        "x":6,
                        "y":6},
                      "size":{
                        "width":9,
                        "height":9}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"39829b1bb34a4e6489888a31b210d3e4",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "stateStyles":{
                            "selected":{
}},
                          "location":{
                            "x":6,
                            "y":6},
                          "size":{
                            "width":9,
                            "height":9}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "selected~":"resources/images/transparent.gif"}},
{
                    "id":"6807ad83c47042d592d00aaef804e107",
                    "label":"",
                    "type":"treeNodeObject",
                    "styleType":"treeNodeObject",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":40},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f5d5eb2602b848aaa3159479f2a4a87e",
                        "label":"",
                        "isContained":true,
                        "type":"buttonShape",
                        "styleType":"buttonShape",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":20,
                            "y":40},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"73faa387ce5c4713805235184fe0a896",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":20,
                                "y":40},
                              "size":{
                                "width":100,
                                "height":20}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"046bc3b6629d4766a90a6eb5dfaee9b4",
                        "label":"",
                        "type":"imageBox",
                        "styleType":"imageBox",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":22,
                            "y":2},
                          "size":{
                            "width":16,
                            "height":16}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"08995a10ea804dbcb74fdd5f37c6f89f",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":22,
                                "y":2},
                              "size":{
                                "width":16,
                                "height":16}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/商户查询/u19.jpg"}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 核销记录",
                                "target":{
                                  "targetType":"page",
                                  "url":"核销记录.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "buttonShapeId":"f5d5eb2602b848aaa3159479f2a4a87e"},
{
                    "id":"140424ac5fb24e369f8d7ff2f7e07f16",
                    "label":"",
                    "type":"treeNodeObject",
                    "styleType":"treeNodeObject",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":60},
                      "size":{
                        "width":113,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c4576ec839ef43cba6525837898ac958",
                        "label":"",
                        "isContained":true,
                        "type":"buttonShape",
                        "styleType":"buttonShape",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":20,
                            "y":60},
                          "size":{
                            "width":113,
                            "height":20}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"e68100e47d764f9d8d0107dee47f69b9",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":20,
                                "y":60},
                              "size":{
                                "width":113,
                                "height":20}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"eb58aae334184a19a6200aefea62d7d9",
                        "label":"",
                        "type":"imageBox",
                        "styleType":"imageBox",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":22,
                            "y":2},
                          "size":{
                            "width":16,
                            "height":16}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"ccd89857d0b44deb967f3ca2d8c790da",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":22,
                                "y":2},
                              "size":{
                                "width":16,
                                "height":16}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/商户查询/u19.jpg"}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 优惠券统计",
                                "target":{
                                  "targetType":"page",
                                  "url":"优惠券统计_1.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "buttonShapeId":"c4576ec839ef43cba6525837898ac958"}],
                "buttonShapeId":"7772b4d299064b7f872beb100376ba9d"}]},
{
            "id":"ad52c8626bf04bed910ea16482f2d73d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":650,
                "y":30},
              "size":{
                "width":180,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f92bde778ffe416bae184d3308e3d1c6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":650,
                    "y":30},
                  "size":{
                    "width":180,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "annotation":{
              "描述":"为商户的名称"},
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0eaa0ee222d34512afb4e0018dd9f1b3",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":950,
                "y":27.5},
              "size":{
                "width":70,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"46154375d8464b578b63e60778d6cebb",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":850,
                "y":30},
              "size":{
                "width":90,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f69096f40a52497499b8df57169f2dad",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":850,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "annotation":{
              "描述":"登陆账号名称"},
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "813a3a95268e48429a354c8cce8f71e4":{
      "scriptId":"u0",
      "3496b00b35034b57afc56e9131fd79c0":{
        "scriptId":"u1"},
      "4603d49a56b5439fa4b8c19626b2e607":{
        "scriptId":"u2"},
      "fa64700b64d44c10b00935db2997f877":{
        "scriptId":"u3"},
      "6943a575259842e1a7218e907b8f643c":{
        "scriptId":"u4"},
      "8ba9b90728b24bf88f157567f6b88f5c":{
        "scriptId":"u5"},
      "245deaa9b7bf403ba8f15a6357adc6d9":{
        "scriptId":"u6"},
      "8a81ac0dfa8e4995bd264cb1e72a78dd":{
        "scriptId":"u7"},
      "de415f578919453bb879d24845e0589c":{
        "scriptId":"u8"},
      "e6c3b471cff14a4bac7999e4a18e5971":{
        "scriptId":"u9"},
      "5989ad95f5e94eaca47a761e9ea92ae0":{
        "scriptId":"u10"},
      "fb09953f7b0e4ea0bbda91e258db1c66":{
        "scriptId":"u11"},
      "75becb34fe3746ec822a4ca9ad4e7cf9":{
        "scriptId":"u12"},
      "39829b1bb34a4e6489888a31b210d3e4":{
        "scriptId":"u13"},
      "abd089bcd0ed44cbbcb78eac530b0b56":{
        "scriptId":"u14"},
      "1be38d2f55f64362969943591a6694b1":{
        "scriptId":"u15"},
      "7772b4d299064b7f872beb100376ba9d":{
        "scriptId":"u16"},
      "9e3d9b82e5b24eb69ef4335005433584":{
        "scriptId":"u17"},
      "b36bdea43e3645b1a813e9e62ff1699a":{
        "scriptId":"u18"},
      "0c3bb24069774494b2f1c99e15abcec4":{
        "scriptId":"u19"},
      "76ce82834ed74d349c0a81b22bb28e37":{
        "scriptId":"u20"},
      "d1fe3005fb964a778c1040df1537e457":{
        "scriptId":"u21"},
      "82775adbcead42a4a56c5ddfc115d6af":{
        "scriptId":"u22"},
      "6807ad83c47042d592d00aaef804e107":{
        "scriptId":"u23"},
      "046bc3b6629d4766a90a6eb5dfaee9b4":{
        "scriptId":"u24"},
      "08995a10ea804dbcb74fdd5f37c6f89f":{
        "scriptId":"u25"},
      "f5d5eb2602b848aaa3159479f2a4a87e":{
        "scriptId":"u26"},
      "73faa387ce5c4713805235184fe0a896":{
        "scriptId":"u27"},
      "140424ac5fb24e369f8d7ff2f7e07f16":{
        "scriptId":"u28"},
      "eb58aae334184a19a6200aefea62d7d9":{
        "scriptId":"u29"},
      "ccd89857d0b44deb967f3ca2d8c790da":{
        "scriptId":"u30"},
      "c4576ec839ef43cba6525837898ac958":{
        "scriptId":"u31"},
      "e68100e47d764f9d8d0107dee47f69b9":{
        "scriptId":"u32"},
      "8497bdc2d4424272885751235658c3e8":{
        "scriptId":"u33"},
      "e8bce3a182a6417a98605df8656f04f4":{
        "scriptId":"u34"},
      "27d4b56981634d3d8906b66df51d4e1d":{
        "scriptId":"u35"},
      "c8902245a2bd4317a17831f735fffa08":{
        "scriptId":"u36"},
      "6ec97ba9b9c5423db31690828c313cb5":{
        "scriptId":"u37"},
      "70911644b44447e28a6258516905a906":{
        "scriptId":"u38"},
      "6fe081f0b5374bc0a4301cb57ac17e44":{
        "scriptId":"u39"},
      "b08f075ec4d442f99d4b9299bca23294":{
        "scriptId":"u40"},
      "7d6346c252d941b0b4afc0252b02e9a1":{
        "scriptId":"u41"},
      "7bb81d90afe944c885faf87bc627acef":{
        "scriptId":"u42"},
      "e94424006956408b9e13dcfa740b9c3f":{
        "scriptId":"u43"},
      "9d56da7c1e5b4db583741e2b5b450483":{
        "scriptId":"u44"},
      "aff2c4678a7d4bfc9f016cc465e192ca":{
        "scriptId":"u45"},
      "f016c2b02a07436e89c1e46df00c457a":{
        "scriptId":"u46"},
      "17ffde6c99d04c3b85f3e17c51525457":{
        "scriptId":"u47"},
      "5ff24eb2c76a45179dac16f817ab4cca":{
        "scriptId":"u48"},
      "9b2908efa67c4ffd8380396eb1d1bbae":{
        "scriptId":"u49"},
      "ad52c8626bf04bed910ea16482f2d73d":{
        "scriptId":"u50"},
      "f92bde778ffe416bae184d3308e3d1c6":{
        "scriptId":"u51"},
      "0eaa0ee222d34512afb4e0018dd9f1b3":{
        "scriptId":"u52"},
      "46154375d8464b578b63e60778d6cebb":{
        "scriptId":"u53"},
      "f69096f40a52497499b8df57169f2dad":{
        "scriptId":"u54"}},
    "3e32fabea66a41a8b25e1fe47ff02c8e":{
      "scriptId":"u55"},
    "8ddddd8ecb3245e98a09c9b1375f474c":{
      "scriptId":"u56"},
    "c9f83d4bb10c4d93be109288d7da6581":{
      "scriptId":"u57"},
    "3afd877058364d90aa12dd9a20539ab8":{
      "scriptId":"u58"},
    "1c07d0ce04554e35a2aa0564aeb90602":{
      "scriptId":"u59"},
    "5559a04087664e02abc6899bd340eacb":{
      "scriptId":"u60"},
    "d732831cf6754041881b0e2089abec1a":{
      "scriptId":"u61"},
    "f02180fae10144f39a56bada937c698a":{
      "scriptId":"u62"},
    "fe47964c220a4e2cbce6c29e14065936":{
      "scriptId":"u63"},
    "977f62cdbfca45d08d5ef03cf63217b5":{
      "scriptId":"u64"},
    "faa432012fa6494d9cfe1e324263a00f":{
      "scriptId":"u65"},
    "459739a805134323b18b37c2b3f6d193":{
      "scriptId":"u66"},
    "adf223cb616c4571aee74ad513fcdefc":{
      "scriptId":"u67"},
    "9bd54f460c454c6ba5d3154e6737b10d":{
      "scriptId":"u68"},
    "c1fa225d7968467dade784eed0822f7a":{
      "scriptId":"u69"},
    "d99419bd92dc4f37bf96f6edfda0527a":{
      "scriptId":"u70"}}});