$axure.loadCurrentPage({
  "url":"优惠券查询.html",
  "generationDate":new Date(1404180835274.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d8f3213722564cff96777f36b9eb6a9b",
    "type":"Axure:Page",
    "name":"优惠券查询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cac655b631f64edfb26960a14d652fce",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":20,
              "y":63},
            "size":{
              "width":91,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c5d243e23b94088a623dc94beb6fa86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":20,
                  "y":63},
                "size":{
                  "width":91,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df8790a527274ea3a440df48c2960110",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":86},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户查询/u16_line.png"}},
{
          "id":"8d2cffed85044d718cb4598db7536b36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":848,
              "y":51},
            "size":{
              "width":85,
              "height":43},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33FF00},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3aef38e9714491b8545afb8942c3339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":848,
                  "y":51},
                "size":{
                  "width":85,
                  "height":43},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF33FF00},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户查询/u0.png"}},
{
          "id":"da185930edf342c399b7e74d91324044",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":860,
              "y":60},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5fd1fc25477e4efdb3f83389e014b16b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":119},
            "size":{
              "width":911,
              "height":161}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ff78c6938834fc5af734d753f48aab6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":119},
                "size":{
                  "width":911,
                  "height":161}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/优惠券查询/u6.png"}},
{
          "id":"9c4265c82d05484ca916060816fbad15",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":226},
            "size":{
              "width":90,
              "height":27}},
          "adaptiveStyles":{
}},
{
          "id":"8ba8f9cf84fa4a27b0be304d3ef30515",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":35,
              "y":218},
            "size":{
              "width":165,
              "height":42},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33FF00},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6992ab526fe34a1c8334215aa1d640a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":35,
                  "y":218},
                "size":{
                  "width":165,
                  "height":42},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF33FF00},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/优惠券查询/u9.png"}},
{
          "id":"f0ef45c73f0447fa963e12dcc173231e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":711,
              "y":264},
            "size":{
              "width":113,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c7d3a5d5b3749bfa899cef9e354a64d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":711,
                  "y":264},
                "size":{
                  "width":113,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73a763d3217b4186b671d50894056e6b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":237},
            "size":{
              "width":770,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/会员查询/u355_end.png",
            "line~":"images/优惠券查询/u13_line.png"}},
{
          "id":"c554d2a8e8244fd095b26f5925cb3918",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":930,
              "y":226},
            "size":{
              "width":90,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1c01083f0174ceb935c9f0411d17dfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":930,
                  "y":226},
                "size":{
                  "width":90,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7795ddb60bb545e9b41d06bcbd1be5c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":290},
            "size":{
              "width":900,
              "height":620}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"486f0c57985a47ca8622177f34f78a2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":290},
                "size":{
                  "width":900,
                  "height":620}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/优惠券查询/u16.png"}},
{
          "id":"476671931c014ecca591d52ded13cf38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":695,
              "y":250},
            "size":{
              "width":175,
              "height":40},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33FF00},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a93d0aa69db4d13a5610253cc99d60f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":695,
                  "y":250},
                "size":{
                  "width":175,
                  "height":40},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF33FF00},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/优惠券查询/u18.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "cac655b631f64edfb26960a14d652fce":{
      "scriptId":"u0"},
    "1c5d243e23b94088a623dc94beb6fa86":{
      "scriptId":"u1"},
    "df8790a527274ea3a440df48c2960110":{
      "scriptId":"u2"},
    "8d2cffed85044d718cb4598db7536b36":{
      "scriptId":"u3"},
    "f3aef38e9714491b8545afb8942c3339":{
      "scriptId":"u4"},
    "da185930edf342c399b7e74d91324044":{
      "scriptId":"u5"},
    "5fd1fc25477e4efdb3f83389e014b16b":{
      "scriptId":"u6"},
    "2ff78c6938834fc5af734d753f48aab6":{
      "scriptId":"u7"},
    "9c4265c82d05484ca916060816fbad15":{
      "scriptId":"u8"},
    "8ba8f9cf84fa4a27b0be304d3ef30515":{
      "scriptId":"u9"},
    "6992ab526fe34a1c8334215aa1d640a3":{
      "scriptId":"u10"},
    "f0ef45c73f0447fa963e12dcc173231e":{
      "scriptId":"u11"},
    "8c7d3a5d5b3749bfa899cef9e354a64d":{
      "scriptId":"u12"},
    "73a763d3217b4186b671d50894056e6b":{
      "scriptId":"u13"},
    "c554d2a8e8244fd095b26f5925cb3918":{
      "scriptId":"u14"},
    "b1c01083f0174ceb935c9f0411d17dfb":{
      "scriptId":"u15"},
    "7795ddb60bb545e9b41d06bcbd1be5c2":{
      "scriptId":"u16"},
    "486f0c57985a47ca8622177f34f78a2d":{
      "scriptId":"u17"},
    "476671931c014ecca591d52ded13cf38":{
      "scriptId":"u18"},
    "5a93d0aa69db4d13a5610253cc99d60f":{
      "scriptId":"u19"}}});