$axure.loadCurrentPage({
  "url":"注册成功.html",
  "generationDate":new Date(1402913061887.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e33064a0f4c04dbaae0bd5a3c4497f98",
    "type":"Axure:Page",
    "name":"注册成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ca27cfb834d74e2b8be5d478ddb415d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":480},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7915def1cd2c4e0c8986ce5445ac4bff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":480},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u0.png"}},
{
          "id":"bc1cf1fcb0ed4d4ea2e8b29dde1a3ba5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":57,
              "y":450},
            "size":{
              "width":273,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42bf0488f2a44bfea43b35a264210436",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":57,
                  "y":450},
                "size":{
                  "width":273,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u2.png"}},
{
          "id":"dcb5c0636b224352a32b959c151e2705",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1350edf80f6c46af8012d7a5efe67d6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u8.png"}},
{
          "id":"a3b8fde065d74fcebe92f004abd5d9ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":40,
              "y":16},
            "size":{
              "width":29,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7989131725204563ab89c0ec6cfcbb65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":40,
                  "y":16},
                "size":{
                  "width":29,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18d0a61afb804cfa9e7ea6fd5e795c4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":79,
              "y":22},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d107378081654ec7b723aec9f9247627",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":79,
                  "y":22},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b018ee58e6e49aca7ac26c540ef1921",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":450},
            "size":{
              "width":48,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2900fcc597224b35a5c1ff39fd5b9458",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":450},
                "size":{
                  "width":48,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u14.png"}},
{
          "id":"2db6c290fca645e0919df86971a56155",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":299,
              "y":455},
            "size":{
              "width":25,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b70a36a0338e40b38190e32cf1c25962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":299,
                  "y":455},
                "size":{
                  "width":25,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c760d18ddb424348a72ccc256bcc434f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":69,
              "y":460},
            "size":{
              "width":17,
              "height":20},
            "rotation":"45",
            "textRotation":"45"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10b0be0657bb4141b92a648aa3a19a60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":69,
                  "y":460},
                "size":{
                  "width":17,
                  "height":20},
                "rotation":"45",
                "textRotation":"45"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31973956f42344b38044ac815f05b4b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":455},
            "size":{
              "width":207,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a858fb0541354573ae95ec5f1330f9b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":455},
                "size":{
                  "width":207,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u16.png"}},
{
          "id":"da82d89ee4514cf4bcc90d7b90d45e18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":272,
              "y":460},
            "size":{
              "width":18,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"454ab22ccb264157949f82840ab9005a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":272,
                  "y":460},
                "size":{
                  "width":18,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85a55490cf4a47d5ba5629021f0ce929",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "horizontalAlignment":"left",
            "paddingTop":"8",
            "paddingBottom":"0",
            "location":{
              "x":69,
              "y":108},
            "size":{
              "width":248,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c4bc752a06746bfa11e3dba17b9965c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "horizontalAlignment":"left",
                "paddingTop":"8",
                "paddingBottom":"0",
                "location":{
                  "x":69,
                  "y":108},
                "size":{
                  "width":248,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册成功/u20.png"}},
{
          "id":"83b39985a63e47719450f0d6b1f72802",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":118},
            "size":{
              "width":10,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":-1,
              "offsetY":0,
              "blurRadius":0,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16ce3886f3f14f43a150103197ce36f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":118},
                "size":{
                  "width":10,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":-1,
                  "offsetY":0,
                  "blurRadius":0,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u22.png"}},
{
          "id":"23f1bb6e9ef241538dd7cb74c844b882",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":105},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04e47bc407184488bb044b89b94e877a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":105},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u24.png"}},
{
          "id":"de5ebf8c008a4b67b7c01f5db3d4f920",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":60},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"966a403c96b141d683810560f11b28e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":60},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u24.png"}},
{
          "id":"6a45d52e8dff497e83920eb46cc1fb2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF33CC00},
            "paddingTop":"8",
            "paddingBottom":"0",
            "location":{
              "x":169,
              "y":60},
            "size":{
              "width":98,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"700758d336b346a7a8f0fc82f4fc0f12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33CC00},
                "paddingTop":"8",
                "paddingBottom":"0",
                "location":{
                  "x":169,
                  "y":60},
                "size":{
                  "width":98,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/验证码/u30.png"}},
{
          "id":"87ba214a33cc4a299ee7b2aab657a65a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF33CC00},
            "location":{
              "x":264,
              "y":70},
            "size":{
              "width":10,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":0,
              "blurRadius":0,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d09803c0f8024d58a86ad00f69d03492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33CC00},
                "location":{
                  "x":264,
                  "y":70},
                "size":{
                  "width":10,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":0,
                  "blurRadius":0,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/验证码/u32.png"}},
{
          "id":"efb6b59b9b3847c5902c2f95d6303d01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":238},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36b632bd96fe4c7b91265450c7fce0ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":238},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u24.png"}},
{
          "id":"cec76a45cbe84577aa2b006ff6c43731",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF33CC00},
            "paddingTop":"8",
            "paddingBottom":"0",
            "location":{
              "x":169,
              "y":238},
            "size":{
              "width":98,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43f558ddd2864830a2ed53bc14387432",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33CC00},
                "paddingTop":"8",
                "paddingBottom":"0",
                "location":{
                  "x":169,
                  "y":238},
                "size":{
                  "width":98,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/验证码/u30.png"}},
{
          "id":"739960dce8f34f3e8dd1b06f51201456",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF33CC00},
            "location":{
              "x":264,
              "y":248},
            "size":{
              "width":10,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":0,
              "blurRadius":0,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2866170b07d48c4b373eeb4d870a062",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33CC00},
                "location":{
                  "x":264,
                  "y":248},
                "size":{
                  "width":10,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":0,
                  "blurRadius":0,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/验证码/u32.png"}},
{
          "id":"d8c512b41ed542aebf342876c32844df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "horizontalAlignment":"left",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":69,
              "y":284},
            "size":{
              "width":248,
              "height":163},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc96d2823ceb45659484a0912d26f6cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "horizontalAlignment":"left",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":69,
                  "y":284},
                "size":{
                  "width":248,
                  "height":163},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册成功/u38.png"}},
{
          "id":"6a182bc63bce4d3eb18a5930c2491967",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":297},
            "size":{
              "width":10,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":-1,
              "offsetY":0,
              "blurRadius":0,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"206dd9e0d5074c44894402d02ee8c625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":297},
                "size":{
                  "width":10,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":-1,
                  "offsetY":0,
                  "blurRadius":0,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册成功/u40.png"}},
{
          "id":"d007b712d6454a299215e9c3dec4c501",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":285},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"253ee592401a4121b8ed83f51be1a70e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":285},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ca27cfb834d74e2b8be5d478ddb415d3":{
      "scriptId":"u0"},
    "7915def1cd2c4e0c8986ce5445ac4bff":{
      "scriptId":"u1"},
    "bc1cf1fcb0ed4d4ea2e8b29dde1a3ba5":{
      "scriptId":"u2"},
    "42bf0488f2a44bfea43b35a264210436":{
      "scriptId":"u3"},
    "dcb5c0636b224352a32b959c151e2705":{
      "scriptId":"u4"},
    "1350edf80f6c46af8012d7a5efe67d6a":{
      "scriptId":"u5"},
    "a3b8fde065d74fcebe92f004abd5d9ee":{
      "scriptId":"u6"},
    "7989131725204563ab89c0ec6cfcbb65":{
      "scriptId":"u7"},
    "18d0a61afb804cfa9e7ea6fd5e795c4e":{
      "scriptId":"u8"},
    "d107378081654ec7b723aec9f9247627":{
      "scriptId":"u9"},
    "3b018ee58e6e49aca7ac26c540ef1921":{
      "scriptId":"u10"},
    "2900fcc597224b35a5c1ff39fd5b9458":{
      "scriptId":"u11"},
    "2db6c290fca645e0919df86971a56155":{
      "scriptId":"u12"},
    "b70a36a0338e40b38190e32cf1c25962":{
      "scriptId":"u13"},
    "c760d18ddb424348a72ccc256bcc434f":{
      "scriptId":"u14"},
    "10b0be0657bb4141b92a648aa3a19a60":{
      "scriptId":"u15"},
    "31973956f42344b38044ac815f05b4b4":{
      "scriptId":"u16"},
    "a858fb0541354573ae95ec5f1330f9b6":{
      "scriptId":"u17"},
    "da82d89ee4514cf4bcc90d7b90d45e18":{
      "scriptId":"u18"},
    "454ab22ccb264157949f82840ab9005a":{
      "scriptId":"u19"},
    "85a55490cf4a47d5ba5629021f0ce929":{
      "scriptId":"u20"},
    "6c4bc752a06746bfa11e3dba17b9965c":{
      "scriptId":"u21"},
    "83b39985a63e47719450f0d6b1f72802":{
      "scriptId":"u22"},
    "16ce3886f3f14f43a150103197ce36f9":{
      "scriptId":"u23"},
    "23f1bb6e9ef241538dd7cb74c844b882":{
      "scriptId":"u24"},
    "04e47bc407184488bb044b89b94e877a":{
      "scriptId":"u25"},
    "de5ebf8c008a4b67b7c01f5db3d4f920":{
      "scriptId":"u26"},
    "966a403c96b141d683810560f11b28e8":{
      "scriptId":"u27"},
    "6a45d52e8dff497e83920eb46cc1fb2d":{
      "scriptId":"u28"},
    "700758d336b346a7a8f0fc82f4fc0f12":{
      "scriptId":"u29"},
    "87ba214a33cc4a299ee7b2aab657a65a":{
      "scriptId":"u30"},
    "d09803c0f8024d58a86ad00f69d03492":{
      "scriptId":"u31"},
    "efb6b59b9b3847c5902c2f95d6303d01":{
      "scriptId":"u32"},
    "36b632bd96fe4c7b91265450c7fce0ee":{
      "scriptId":"u33"},
    "cec76a45cbe84577aa2b006ff6c43731":{
      "scriptId":"u34"},
    "43f558ddd2864830a2ed53bc14387432":{
      "scriptId":"u35"},
    "739960dce8f34f3e8dd1b06f51201456":{
      "scriptId":"u36"},
    "e2866170b07d48c4b373eeb4d870a062":{
      "scriptId":"u37"},
    "d8c512b41ed542aebf342876c32844df":{
      "scriptId":"u38"},
    "dc96d2823ceb45659484a0912d26f6cb":{
      "scriptId":"u39"},
    "6a182bc63bce4d3eb18a5930c2491967":{
      "scriptId":"u40"},
    "206dd9e0d5074c44894402d02ee8c625":{
      "scriptId":"u41"},
    "d007b712d6454a299215e9c3dec4c501":{
      "scriptId":"u42"},
    "253ee592401a4121b8ed83f51be1a70e":{
      "scriptId":"u43"}}});