$axure.loadCurrentPage({
  "url":"快速登陆.html",
  "generationDate":new Date(1404796804460.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8ffd1cc304174ec4b77d620a4ba681ff",
    "type":"Axure:Page",
    "name":"快速登陆",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"eb0921c33ac54c88a8e8e076c793303a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":310,
              "height":550}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ac9117a5906480a8e730a56748aeb2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":310,
                  "height":550}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首界面/u0.jpg"}},
{
          "id":"bec1a15f61e84264bb9067527bddb831",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE9EAEF},
            "location":{
              "x":20,
              "y":82},
            "size":{
              "width":309,
              "height":440},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3098d7c0cfe5469ea6fabe899171e392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE9EAEF},
                "location":{
                  "x":20,
                  "y":82},
                "size":{
                  "width":309,
                  "height":440},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首界面/u2.png"}},
{
          "id":"1e10ec3e2dbf40f1ba4d4d86b01353eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":48,
              "y":400},
            "size":{
              "width":254,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009999},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d14245ba9fd14cefa1d9382052ea529c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":48,
                  "y":400},
                "size":{
                  "width":254,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证登陆/u8.png"}},
{
          "id":"553c65754d96410abbe3b60d5ac2ff38",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":48,
              "y":375},
            "size":{
              "width":254,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40e0427ef8b94122a2baee2b9dd34951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":48,
                  "y":375},
                "size":{
                  "width":254,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"a9be5295b6144e85b9df3548e41ae6e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":48,
              "y":492},
            "size":{
              "width":254,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"420e44547db0458e89a01700931c5e4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":48,
                  "y":492},
                "size":{
                  "width":254,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9561f2fac6a942e887e636bc4a337de8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":480},
            "size":{
              "width":309,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/认证登陆/u18_line.png"}},
{
          "id":"79ac818978784144a303df60ce408138",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":99},
            "size":{
              "width":290,
              "height":260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac2e196e4d924e4aaa6ba81175de96b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":99},
                "size":{
                  "width":290,
                  "height":260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快速登陆/u11.png"}},
{
          "id":"80be29e4bd1b4472a03b660183a47784",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":400},
            "size":{
              "width":254,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 手机版网址导航",
                      "target":{
                        "targetType":"page",
                        "url":"手机版网址导航.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"72a33f4540764af8b86c81ca98f5c9d7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":140},
            "size":{
              "width":110,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/首界面/u21_start.png",
            "end~":"images/首界面/u21_end.png",
            "line~":"images/首界面/u21_line.png"}},
{
          "id":"8a7938f7609a4d1ca5c8df9e7e4af162",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":400,
              "y":125},
            "size":{
              "width":270,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07cf934db2dc4470973bfa3bf679d720",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":400,
                  "y":125},
                "size":{
                  "width":270,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "eb0921c33ac54c88a8e8e076c793303a":{
      "scriptId":"u0"},
    "2ac9117a5906480a8e730a56748aeb2f":{
      "scriptId":"u1"},
    "bec1a15f61e84264bb9067527bddb831":{
      "scriptId":"u2"},
    "3098d7c0cfe5469ea6fabe899171e392":{
      "scriptId":"u3"},
    "1e10ec3e2dbf40f1ba4d4d86b01353eb":{
      "scriptId":"u4"},
    "d14245ba9fd14cefa1d9382052ea529c":{
      "scriptId":"u5"},
    "553c65754d96410abbe3b60d5ac2ff38":{
      "scriptId":"u6"},
    "40e0427ef8b94122a2baee2b9dd34951":{
      "scriptId":"u7"},
    "a9be5295b6144e85b9df3548e41ae6e2":{
      "scriptId":"u8"},
    "420e44547db0458e89a01700931c5e4e":{
      "scriptId":"u9"},
    "9561f2fac6a942e887e636bc4a337de8":{
      "scriptId":"u10"},
    "79ac818978784144a303df60ce408138":{
      "scriptId":"u11"},
    "ac2e196e4d924e4aaa6ba81175de96b4":{
      "scriptId":"u12"},
    "80be29e4bd1b4472a03b660183a47784":{
      "scriptId":"u13"},
    "72a33f4540764af8b86c81ca98f5c9d7":{
      "scriptId":"u14"},
    "8a7938f7609a4d1ca5c8df9e7e4af162":{
      "scriptId":"u15"},
    "07cf934db2dc4470973bfa3bf679d720":{
      "scriptId":"u16"}}});