$axure.loadCurrentPage({
  "url":"查坐标.html",
  "generationDate":new Date(1404457228842.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"80e618d526f146fd87b4b7aa9f5e5455",
    "type":"Axure:Page",
    "name":"查坐标",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a404b58e02644ab49e07d75206267106",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":560},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12f7e942d7a447d38567fa79c63016e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":560},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查坐标/u0.png"}},
{
          "id":"d585e3b5435a46c6a6ff64d354a8059f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"521520b2f19946e49eaa88bbe191f885",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u8.png"}},
{
          "id":"2ae5751ba3f340afbb5138e877880bfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":40,
              "y":16},
            "size":{
              "width":29,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa59665517a745e49cf8cdc753bea671",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":40,
                  "y":16},
                "size":{
                  "width":29,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"434ab03d6d764f0abfa87f6a22702aa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":78,
              "y":22},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d137271b713b4ae296878757916f727c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":78,
                  "y":22},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd870c034100472db20dcb536bd4fbe9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":10,
              "y":48},
            "size":{
              "width":320,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f610a52b97af4385a3cb04ef86916c5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":10,
                  "y":48},
                "size":{
                  "width":320,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2784706a2da4249b245f120b6494878",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":119},
            "size":{
              "width":302,
              "height":437}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca175023d2e24f9db2784371f65e8001",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":119},
                "size":{
                  "width":302,
                  "height":437}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查坐标/u10.jpg"}},
{
          "id":"9b8c2cb47d3747cfa37ac9f2b28b73fb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":95},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/关于人信汇/u26_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a404b58e02644ab49e07d75206267106":{
      "scriptId":"u0"},
    "12f7e942d7a447d38567fa79c63016e8":{
      "scriptId":"u1"},
    "d585e3b5435a46c6a6ff64d354a8059f":{
      "scriptId":"u2"},
    "521520b2f19946e49eaa88bbe191f885":{
      "scriptId":"u3"},
    "2ae5751ba3f340afbb5138e877880bfd":{
      "scriptId":"u4"},
    "aa59665517a745e49cf8cdc753bea671":{
      "scriptId":"u5"},
    "434ab03d6d764f0abfa87f6a22702aa4":{
      "scriptId":"u6"},
    "d137271b713b4ae296878757916f727c":{
      "scriptId":"u7"},
    "bd870c034100472db20dcb536bd4fbe9":{
      "scriptId":"u8"},
    "f610a52b97af4385a3cb04ef86916c5a":{
      "scriptId":"u9"},
    "c2784706a2da4249b245f120b6494878":{
      "scriptId":"u10"},
    "ca175023d2e24f9db2784371f65e8001":{
      "scriptId":"u11"},
    "9b8c2cb47d3747cfa37ac9f2b28b73fb":{
      "scriptId":"u12"}}});