$axure.loadCurrentPage({
  "url":"编辑广告.html",
  "generationDate":new Date(1404797672972),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9b3976c143a842c7970bd52f1bf45717",
    "type":"Axure:Page",
    "name":"编辑广告",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"987777ef6b934f54b8d841d59def85cd",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":91},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51dcb8e0747e4f7ebe00ef305851a0c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":91},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"62653dadfc00406889850eec8d5bc3c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":91},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bde5168a75294ba6a27b215219fae6f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":91},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fb6ca422ee7403d8f880b1115874951",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "disabled":true,
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":220,
              "y":91},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4e1dc272b6f4156934e4252016f7dfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":220,
                  "y":91},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e9fb0cbae54e4d6c8288655f0d1dbd8c",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "disabled":true,
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":320,
              "y":91},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e75818e2fbb4ca097ea8f2b6846d98a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":91},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6bd89e15914a4f66b4df5c07a52ee4ec",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":51},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机版wifi营销广告管理/u0_line.png"}},
{
          "id":"d5f1097ee79c4eb19d67f7d70d575eed",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":30},
            "size":{
              "width":240,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a042d6326dba41de96dee8af1c062a5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":30},
                "size":{
                  "width":240,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f980082058694dfba25c9d6bc9167d93",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":96},
            "size":{
              "width":530,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/编辑广告/u11_line.png"}},
{
          "id":"894f34e19b4544f59d7d0983760add15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":940,
              "y":91},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"589cb877c8904b349ff87f97841ca1b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":940,
                  "y":91},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69d09ac9a54b441cb31680533bdc9ba9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":120,
              "y":152},
            "size":{
              "width":200,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97e5ac4b90bf40c3850f8aed20759bf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":120,
                  "y":152},
                "size":{
                  "width":200,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新建广告/u0.png"}},
{
          "id":"d02d78b6c8f5424fa047c3a81a85d219",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":120,
              "y":395},
            "size":{
              "width":500,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"904ccf82b2b94bd2a4f2ad6e5c4b350d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":398},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ede8848bf3b432983d835d8bb52d1ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":398},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb47be6fbdec4b44ab745fff05aaa0a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":120,
              "y":430},
            "size":{
              "width":400,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a8d49681ca044748094a72799adddbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":120,
                  "y":430},
                "size":{
                  "width":400,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27f279bdb4c544229f78fe9a9159003d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":470},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"23cdd25d40df4cacbb8cc58ab652a575",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":120,
              "y":362},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cafbdef31b34387bfa2226858398855",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":120,
                  "y":362},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed30296022de49e28aa5b01e404bd6c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":970,
              "y":320},
            "size":{
              "width":300,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3844cfb50a7a41698ddf416c798f43fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":970,
                  "y":320},
                "size":{
                  "width":300,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd5aaf1a0a01454f8abd2c0e5dcdb9b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":152},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cf7454ee95f448db3b34a13f7298d1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":152},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"696ab56fdd51495a8a6e5f7c644b809b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":367},
            "size":{
              "width":680,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3333FF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/新建广告/u25_end.png",
            "line~":"images/新建广告/u25_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "987777ef6b934f54b8d841d59def85cd":{
      "scriptId":"u0"},
    "51dcb8e0747e4f7ebe00ef305851a0c8":{
      "scriptId":"u1"},
    "62653dadfc00406889850eec8d5bc3c4":{
      "scriptId":"u2"},
    "bde5168a75294ba6a27b215219fae6f1":{
      "scriptId":"u3"},
    "8fb6ca422ee7403d8f880b1115874951":{
      "scriptId":"u4"},
    "a4e1dc272b6f4156934e4252016f7dfb":{
      "scriptId":"u5"},
    "e9fb0cbae54e4d6c8288655f0d1dbd8c":{
      "scriptId":"u6"},
    "9e75818e2fbb4ca097ea8f2b6846d98a":{
      "scriptId":"u7"},
    "6bd89e15914a4f66b4df5c07a52ee4ec":{
      "scriptId":"u8"},
    "d5f1097ee79c4eb19d67f7d70d575eed":{
      "scriptId":"u9"},
    "a042d6326dba41de96dee8af1c062a5f":{
      "scriptId":"u10"},
    "f980082058694dfba25c9d6bc9167d93":{
      "scriptId":"u11"},
    "894f34e19b4544f59d7d0983760add15":{
      "scriptId":"u12"},
    "589cb877c8904b349ff87f97841ca1b9":{
      "scriptId":"u13"},
    "69d09ac9a54b441cb31680533bdc9ba9":{
      "scriptId":"u14"},
    "97e5ac4b90bf40c3850f8aed20759bf1":{
      "scriptId":"u15"},
    "d02d78b6c8f5424fa047c3a81a85d219":{
      "scriptId":"u16"},
    "904ccf82b2b94bd2a4f2ad6e5c4b350d":{
      "scriptId":"u17"},
    "9ede8848bf3b432983d835d8bb52d1ee":{
      "scriptId":"u18"},
    "fb47be6fbdec4b44ab745fff05aaa0a6":{
      "scriptId":"u19"},
    "5a8d49681ca044748094a72799adddbc":{
      "scriptId":"u20"},
    "27f279bdb4c544229f78fe9a9159003d":{
      "scriptId":"u21"},
    "23cdd25d40df4cacbb8cc58ab652a575":{
      "scriptId":"u22"},
    "9cafbdef31b34387bfa2226858398855":{
      "scriptId":"u23"},
    "ed30296022de49e28aa5b01e404bd6c1":{
      "scriptId":"u24"},
    "3844cfb50a7a41698ddf416c798f43fa":{
      "scriptId":"u25"},
    "bd5aaf1a0a01454f8abd2c0e5dcdb9b6":{
      "scriptId":"u26"},
    "2cf7454ee95f448db3b34a13f7298d1a":{
      "scriptId":"u27"},
    "696ab56fdd51495a8a6e5f7c644b809b":{
      "scriptId":"u28"}}});