$axure.loadCurrentPage({
  "url":"活动详情.html",
  "generationDate":new Date(1400556883806.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b79f80fcef9d4de78b490c5286934413",
    "type":"Axure:Page",
    "name":"活动详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e15701292370480da9cdb396d1686066",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":271},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c016ad3fa9c34f6796b4ef9b236f0a7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":271},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"584f4eeccf1147e6a1e27fd6fd26faf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":125},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e90eaf0c48f413380426c72a30c451c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":125},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7195d423063a4462a9589ed3aa7e979f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":647},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b941c7ee3eee4411a1bf01f1b3e6e5e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":647},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e23bf9cb456b4a7dabfe8cbdbd1e6cf3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":130,
              "y":647},
            "size":{
              "width":340,
              "height":212}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b409345677d411a94027735588daa21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":130,
                  "y":647},
                "size":{
                  "width":340,
                  "height":212}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u6.png"}},
{
          "id":"ca1df895828d4f04902c78301dd88b01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":157},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dcd61ad40384392853841209bbda1b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":157},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52ee8bd323dd4237a63508ff0202bef4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":20,
              "y":880},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2133e1e584114825a9c3d9e300ac4dd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":20,
                  "y":880},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1396c53ff1d74636bbcdfca48d379763",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":196},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b90c14e0b92349d2b44535954e0c5514",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":196},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8205768e485e4bafaa49095473fb992d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":233},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be618492a8804fb7b4108d2666452d62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":233},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44a0a6e8bfe74c22a37ab37740e7d823",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":447},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0bc6922a0584a9b9054b10f2fe5a16c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":447},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"adec68cfaa134c41ab9e0af3b5d9acd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":20,
              "y":60},
            "size":{
              "width":73,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8968b82fc2643348dd4b100dd435a45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":20,
                  "y":60},
                "size":{
                  "width":73,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffd83e23e545419a8aa380c84c15840b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":95},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创建_编辑活动/u52_line.png"}},
{
          "id":"edeface2159d4cb0989647ab6a260728",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":130,
              "y":125},
            "size":{
              "width":292,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab718699542f434caecbbfa5035cac2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":125},
                "size":{
                  "width":292,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5c87df2ad9c407fabbef052ca5507ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":130,
              "y":196},
            "size":{
              "width":530,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f9838ce1b3f48afa7a90c8eb90bf86a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":130,
                  "y":196},
                "size":{
                  "width":530,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bebe5bcaf4442549df7adac67457f62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":130,
              "y":447},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7904751bee124f01b49a12aec7f84b8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":130,
                  "y":447},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4238c978cc7442929e241ac68d9f7415",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":311},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b36b6e8b375e4bc5bf3193f1b86ebfd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":311},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b50bdb55365e4e03bbc54e9d70bae550",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":401},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"704193b8d0f14444a658df7863ac190d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":401},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d30d0738da494c76b95a263d5c78aad6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":353},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ee7ca146da3491490b5982039166049",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":353},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0ead7aa8ff54b95946e009deb3abff0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":495},
            "size":{
              "width":80,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/创建_编辑活动/u90_start.png",
            "end~":"images/创建_编辑活动/u90_end.png",
            "line~":"images/活动详情/u33_line.png"}},
{
          "id":"7f9941cb2cc04da797aea6b2032a8d31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":900,
              "y":490},
            "size":{
              "width":230,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71571394215b45178d28d12e4b3edd5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":900,
                  "y":490},
                "size":{
                  "width":230,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47f34d9cbc90478eaf46ca0a22ceac6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":130,
              "y":157},
            "size":{
              "width":292,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3033ab1f1a94481bf1dd41dafa30e8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":157},
                "size":{
                  "width":292,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56686687dc9845869e7c9e97182cf0b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":130,
              "y":271},
            "size":{
              "width":530,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17690e8d88d747b4bc80d667bafbe464",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":130,
                  "y":271},
                "size":{
                  "width":530,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ace996402424e90bfb158c3d4d71828",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":130,
              "y":311},
            "size":{
              "width":530,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02ca2016a3834e07a8706a95632a37f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":130,
                  "y":311},
                "size":{
                  "width":530,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4feafb605a664ef7b5eb228f485a69b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":130,
              "y":401},
            "size":{
              "width":530,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c19a3d340ef148c887a059a0fc282b60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":130,
                  "y":401},
                "size":{
                  "width":530,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a960453a2064e15969e9ff16bb5d28f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":130,
              "y":353},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a84acefb31d749b98332cb1ef8077160",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":130,
                  "y":353},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35fd60e34381418390efc503c77c2788",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":500,
              "y":647},
            "size":{
              "width":340,
              "height":212}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cef9493f56b34c24bc583b2c0b233ed0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":500,
                  "y":647},
                "size":{
                  "width":340,
                  "height":212}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u6.png"}},
{
          "id":"d12df59a38fd4809a593d3659c526cde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":490},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57489dd2ffac45e3baad5fb73968cb6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":490},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ab4c861c1134097aa966e83fa602b32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":680,
              "y":490},
            "size":{
              "width":50,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ca60b8ceb1944be99dba9b94ba3fd61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":680,
                  "y":490},
                "size":{
                  "width":50,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"710c827296554464ae6561710a85099b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "location":{
              "x":130,
              "y":490},
            "size":{
              "width":200,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ec15f3595c948f6bd441e104b41869a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "location":{
                  "x":130,
                  "y":490},
                "size":{
                  "width":200,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u52.png"}},
{
          "id":"86cc6006684245be9b9116e9d6341e04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":330,
              "y":490},
            "size":{
              "width":340,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31d8e792f2f24df090940273fa4543ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":330,
                  "y":490},
                "size":{
                  "width":340,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u54.png"}},
{
          "id":"2ab61b61c6644be4940ff081ba24c7d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":130,
              "y":490},
            "size":{
              "width":200,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73465da3d13b4924a067947cc7441169",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":490},
                "size":{
                  "width":200,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b81f64cc43546d68e67312f99371c7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":730,
              "y":490},
            "size":{
              "width":110,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdcdee4078584702aa7bf45d6ffffba6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":730,
                  "y":490},
                "size":{
                  "width":110,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae5d75b8b1914a62ab9063ae521e467c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":30,
              "y":540},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f946295ac3d2437bbab78c131affd1df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":30,
                  "y":540},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b068ebfa837b4f6ea4b79a03d653c3e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":130,
              "y":540},
            "size":{
              "width":540,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"668324ad7fbc4f3786b70c93394c6f8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":130,
                  "y":540},
                "size":{
                  "width":540,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u62.png"}},
{
          "id":"d08271c8a3b245989c5ee89d74cd41b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":130,
              "y":580},
            "size":{
              "width":240,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af779ea1abf640ffbd7aea9b8704bd16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":130,
                  "y":580},
                "size":{
                  "width":240,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u64.png"}},
{
          "id":"95efb441d0884927abac1c8eee3b668e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":680,
              "y":540},
            "size":{
              "width":50,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b79952c3f94649aba3c57da840d183df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":680,
                  "y":540},
                "size":{
                  "width":50,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2daf2fcb4a64032bcacdc75f3d42f7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":730,
              "y":540},
            "size":{
              "width":110,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76f28bd80f8b43b0b6b47dc3c5802d2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":730,
                  "y":540},
                "size":{
                  "width":110,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d756d5502472449ebb9130cd0c0872f1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":545},
            "size":{
              "width":80,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/创建_编辑活动/u90_start.png",
            "end~":"images/创建_编辑活动/u90_end.png",
            "line~":"images/活动详情/u33_line.png"}},
{
          "id":"423296def54e4ecc879f2bbc7770bc47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":900,
              "y":540},
            "size":{
              "width":230,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7629e88fd564b82a170b15e3b2a2027",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":900,
                  "y":540},
                "size":{
                  "width":230,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e43974768bd84aa5a984c51371f310a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":130,
              "y":880},
            "size":{
              "width":710,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed37639b4b8649d6a1bc43b8df7c4629",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":130,
                  "y":880},
                "size":{
                  "width":710,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddfabc5221474ce4a9b59777c79dfe27",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":130,
              "y":1050},
            "size":{
              "width":710,
              "height":360}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c1fc613d83d4e1fa6a197bdd56b78f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":130,
                  "y":1050},
                "size":{
                  "width":710,
                  "height":360}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u75.png"}},
{
          "id":"24a9c44322c04bc5b92e8f3490a0ff81",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":130,
              "y":1420},
            "size":{
              "width":710,
              "height":360}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6060fe023dd4fd59af8408d640641ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":130,
                  "y":1420},
                "size":{
                  "width":710,
                  "height":360}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u75.png"}},
{
          "id":"6ec07fe58c294dff85528508bbdb2b8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":390},
            "size":{
              "width":790,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eba666482794082a23524c07ddd3e20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":390},
                "size":{
                  "width":790,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u79.png"}},
{
          "id":"7c887b5c187c4da8b806cf6c4a7ff8f2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":440},
            "size":{
              "width":80,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/创建_编辑活动/u90_start.png",
            "end~":"images/创建_编辑活动/u90_end.png",
            "line~":"images/活动详情/u33_line.png"}},
{
          "id":"9ea4c9dbd4d64018b1ccc1856120c9be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":900,
              "y":435},
            "size":{
              "width":210,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee876c35c3a44cceaf42e926800e35cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":900,
                  "y":435},
                "size":{
                  "width":210,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ac9000185e24b3dac906f5b144863b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "lineSpacing":"0px",
            "location":{
              "x":130,
              "y":235},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"264fce56ff0d4c86929e0798dab99a64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "lineSpacing":"0px",
                "location":{
                  "x":130,
                  "y":235},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eeb879c518b0461e98b21a52dae2ec65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":20,
              "y":1838},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59b8ee794da14dfaa2343b07a963944a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":20,
                  "y":1838},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f5cf5b544ff4532a06ec3c399bab459",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":20,
              "y":1880},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ece7f73f18845b69f9e64d4efe11392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":20,
                  "y":1880},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01fab24865c648b598fdbdbf21a8355b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":120,
              "y":1838},
            "size":{
              "width":530,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be4b7a9600364af1acf76e5155424fd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":1838},
                "size":{
                  "width":530,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6add0992c824da1a067a9a8711c06aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":120,
              "y":1880},
            "size":{
              "width":130,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d91d4d9bb3d7497a8b70f73b8a18f526",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":1880},
                "size":{
                  "width":130,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e15701292370480da9cdb396d1686066":{
      "scriptId":"u0"},
    "c016ad3fa9c34f6796b4ef9b236f0a7d":{
      "scriptId":"u1"},
    "584f4eeccf1147e6a1e27fd6fd26faf4":{
      "scriptId":"u2"},
    "4e90eaf0c48f413380426c72a30c451c":{
      "scriptId":"u3"},
    "7195d423063a4462a9589ed3aa7e979f":{
      "scriptId":"u4"},
    "b941c7ee3eee4411a1bf01f1b3e6e5e0":{
      "scriptId":"u5"},
    "e23bf9cb456b4a7dabfe8cbdbd1e6cf3":{
      "scriptId":"u6"},
    "9b409345677d411a94027735588daa21":{
      "scriptId":"u7"},
    "ca1df895828d4f04902c78301dd88b01":{
      "scriptId":"u8"},
    "6dcd61ad40384392853841209bbda1b9":{
      "scriptId":"u9"},
    "52ee8bd323dd4237a63508ff0202bef4":{
      "scriptId":"u10"},
    "2133e1e584114825a9c3d9e300ac4dd5":{
      "scriptId":"u11"},
    "1396c53ff1d74636bbcdfca48d379763":{
      "scriptId":"u12"},
    "b90c14e0b92349d2b44535954e0c5514":{
      "scriptId":"u13"},
    "8205768e485e4bafaa49095473fb992d":{
      "scriptId":"u14"},
    "be618492a8804fb7b4108d2666452d62":{
      "scriptId":"u15"},
    "44a0a6e8bfe74c22a37ab37740e7d823":{
      "scriptId":"u16"},
    "c0bc6922a0584a9b9054b10f2fe5a16c":{
      "scriptId":"u17"},
    "adec68cfaa134c41ab9e0af3b5d9acd9":{
      "scriptId":"u18"},
    "d8968b82fc2643348dd4b100dd435a45":{
      "scriptId":"u19"},
    "ffd83e23e545419a8aa380c84c15840b":{
      "scriptId":"u20"},
    "edeface2159d4cb0989647ab6a260728":{
      "scriptId":"u21"},
    "ab718699542f434caecbbfa5035cac2b":{
      "scriptId":"u22"},
    "c5c87df2ad9c407fabbef052ca5507ae":{
      "scriptId":"u23"},
    "7f9838ce1b3f48afa7a90c8eb90bf86a":{
      "scriptId":"u24"},
    "9bebe5bcaf4442549df7adac67457f62":{
      "scriptId":"u25"},
    "7904751bee124f01b49a12aec7f84b8f":{
      "scriptId":"u26"},
    "4238c978cc7442929e241ac68d9f7415":{
      "scriptId":"u27"},
    "b36b6e8b375e4bc5bf3193f1b86ebfd9":{
      "scriptId":"u28"},
    "b50bdb55365e4e03bbc54e9d70bae550":{
      "scriptId":"u29"},
    "704193b8d0f14444a658df7863ac190d":{
      "scriptId":"u30"},
    "d30d0738da494c76b95a263d5c78aad6":{
      "scriptId":"u31"},
    "6ee7ca146da3491490b5982039166049":{
      "scriptId":"u32"},
    "c0ead7aa8ff54b95946e009deb3abff0":{
      "scriptId":"u33"},
    "7f9941cb2cc04da797aea6b2032a8d31":{
      "scriptId":"u34"},
    "71571394215b45178d28d12e4b3edd5f":{
      "scriptId":"u35"},
    "47f34d9cbc90478eaf46ca0a22ceac6e":{
      "scriptId":"u36"},
    "a3033ab1f1a94481bf1dd41dafa30e8b":{
      "scriptId":"u37"},
    "56686687dc9845869e7c9e97182cf0b0":{
      "scriptId":"u38"},
    "17690e8d88d747b4bc80d667bafbe464":{
      "scriptId":"u39"},
    "4ace996402424e90bfb158c3d4d71828":{
      "scriptId":"u40"},
    "02ca2016a3834e07a8706a95632a37f4":{
      "scriptId":"u41"},
    "4feafb605a664ef7b5eb228f485a69b0":{
      "scriptId":"u42"},
    "c19a3d340ef148c887a059a0fc282b60":{
      "scriptId":"u43"},
    "7a960453a2064e15969e9ff16bb5d28f":{
      "scriptId":"u44"},
    "a84acefb31d749b98332cb1ef8077160":{
      "scriptId":"u45"},
    "35fd60e34381418390efc503c77c2788":{
      "scriptId":"u46"},
    "cef9493f56b34c24bc583b2c0b233ed0":{
      "scriptId":"u47"},
    "d12df59a38fd4809a593d3659c526cde":{
      "scriptId":"u48"},
    "57489dd2ffac45e3baad5fb73968cb6c":{
      "scriptId":"u49"},
    "6ab4c861c1134097aa966e83fa602b32":{
      "scriptId":"u50"},
    "2ca60b8ceb1944be99dba9b94ba3fd61":{
      "scriptId":"u51"},
    "710c827296554464ae6561710a85099b":{
      "scriptId":"u52"},
    "0ec15f3595c948f6bd441e104b41869a":{
      "scriptId":"u53"},
    "86cc6006684245be9b9116e9d6341e04":{
      "scriptId":"u54"},
    "31d8e792f2f24df090940273fa4543ff":{
      "scriptId":"u55"},
    "2ab61b61c6644be4940ff081ba24c7d5":{
      "scriptId":"u56"},
    "73465da3d13b4924a067947cc7441169":{
      "scriptId":"u57"},
    "4b81f64cc43546d68e67312f99371c7c":{
      "scriptId":"u58"},
    "bdcdee4078584702aa7bf45d6ffffba6":{
      "scriptId":"u59"},
    "ae5d75b8b1914a62ab9063ae521e467c":{
      "scriptId":"u60"},
    "f946295ac3d2437bbab78c131affd1df":{
      "scriptId":"u61"},
    "b068ebfa837b4f6ea4b79a03d653c3e3":{
      "scriptId":"u62"},
    "668324ad7fbc4f3786b70c93394c6f8f":{
      "scriptId":"u63"},
    "d08271c8a3b245989c5ee89d74cd41b2":{
      "scriptId":"u64"},
    "af779ea1abf640ffbd7aea9b8704bd16":{
      "scriptId":"u65"},
    "95efb441d0884927abac1c8eee3b668e":{
      "scriptId":"u66"},
    "b79952c3f94649aba3c57da840d183df":{
      "scriptId":"u67"},
    "f2daf2fcb4a64032bcacdc75f3d42f7f":{
      "scriptId":"u68"},
    "76f28bd80f8b43b0b6b47dc3c5802d2c":{
      "scriptId":"u69"},
    "d756d5502472449ebb9130cd0c0872f1":{
      "scriptId":"u70"},
    "423296def54e4ecc879f2bbc7770bc47":{
      "scriptId":"u71"},
    "a7629e88fd564b82a170b15e3b2a2027":{
      "scriptId":"u72"},
    "e43974768bd84aa5a984c51371f310a8":{
      "scriptId":"u73"},
    "ed37639b4b8649d6a1bc43b8df7c4629":{
      "scriptId":"u74"},
    "ddfabc5221474ce4a9b59777c79dfe27":{
      "scriptId":"u75"},
    "1c1fc613d83d4e1fa6a197bdd56b78f1":{
      "scriptId":"u76"},
    "24a9c44322c04bc5b92e8f3490a0ff81":{
      "scriptId":"u77"},
    "a6060fe023dd4fd59af8408d640641ce":{
      "scriptId":"u78"},
    "6ec07fe58c294dff85528508bbdb2b8c":{
      "scriptId":"u79"},
    "5eba666482794082a23524c07ddd3e20":{
      "scriptId":"u80"},
    "7c887b5c187c4da8b806cf6c4a7ff8f2":{
      "scriptId":"u81"},
    "9ea4c9dbd4d64018b1ccc1856120c9be":{
      "scriptId":"u82"},
    "ee876c35c3a44cceaf42e926800e35cb":{
      "scriptId":"u83"},
    "7ac9000185e24b3dac906f5b144863b4":{
      "scriptId":"u84"},
    "264fce56ff0d4c86929e0798dab99a64":{
      "scriptId":"u85"},
    "eeb879c518b0461e98b21a52dae2ec65":{
      "scriptId":"u86"},
    "59b8ee794da14dfaa2343b07a963944a":{
      "scriptId":"u87"},
    "9f5cf5b544ff4532a06ec3c399bab459":{
      "scriptId":"u88"},
    "7ece7f73f18845b69f9e64d4efe11392":{
      "scriptId":"u89"},
    "01fab24865c648b598fdbdbf21a8355b":{
      "scriptId":"u90"},
    "be4b7a9600364af1acf76e5155424fd8":{
      "scriptId":"u91"},
    "e6add0992c824da1a067a9a8711c06aa":{
      "scriptId":"u92"},
    "d91d4d9bb3d7497a8b70f73b8a18f526":{
      "scriptId":"u93"}}});