$axure.loadCurrentPage({
  "url":"报告分析.html",
  "generationDate":new Date(1401876151834.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"375eb63a307948bf97de138ec75f3902",
    "type":"Axure:Page",
    "name":"报告分析",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3445034d7fe540c2b9d4a2921b008f46",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":20,
              "y":50},
            "size":{
              "width":210,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0c03c3551e5480bb7de84813960230b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":20,
                  "y":50},
                "size":{
                  "width":210,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2dad0fa5cd7a4db9af54064adcb6066e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":75},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/短信发送/u6_line.png"}},
{
          "id":"f3256b27a2e048b1bd9090c192d00fc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":19,
              "y":119},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2281ff835657468db54fcc96d76185f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":19,
                  "y":119},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e90e3c401b474156bd15c2b69491a906",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":110},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"afe00966b6194efa8e5a3b46506a2563",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":110},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"45994ea6e5c34ceb8a0b3fad1ef74a33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":112},
            "size":{
              "width":40,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abf6060e7abd4bbc80b7bcf847eeb77e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":112},
                "size":{
                  "width":40,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7604ddec41f40168bcc9e14eab011b4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":539,
              "y":111},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f2830415053a4e40b0455932330c2c95",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":20,
              "y":195},
            "size":{
              "width":37,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5164a414a264a6382d34e0a7db853ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":20,
                  "y":195},
                "size":{
                  "width":37,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7082f7e7e0f54699bced66c091bf8e71",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":220},
            "size":{
              "width":900,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/报告分析/u12_line.png"}},
{
          "id":"e5351188b5fa4eb994473431d05983e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":317},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b401036dcb524e35ae48066d8569ccb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":317},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"289bcad908034721b64c74c52f6188eb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":575},
            "size":{
              "width":900,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/报告分析/u12_line.png"}},
{
          "id":"bf0e1302308f4b56b010d5c5256a7db2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":684},
            "size":{
              "width":900,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/报告分析/u12_line.png"}},
{
          "id":"62b0e7afa8444a9ea4f12ee89847c1e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":607},
            "size":{
              "width":440,
              "height":265}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f82e6d5d77f464c9174b4c9cee5fb19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":607},
                "size":{
                  "width":440,
                  "height":265}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/报告分析/u17.png"}},
{
          "id":"b07345578f2c464d9d01720d94d56446",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":607},
            "size":{
              "width":460,
              "height":265}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca9d58f854ca4bb2b005aff4f85c26ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":607},
                "size":{
                  "width":460,
                  "height":265}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/报告分析/u19.png"}},
{
          "id":"fafb0ba09ebf43b39f940f178c074ac4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":256},
            "size":{
              "width":900,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dce48b396b134ad295f1442fc244e234",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":256},
                "size":{
                  "width":900,
                  "height":310}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/报告分析/u21.png"}},
{
          "id":"f7de9c4963a549f787cc3ca5375d19dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":779,
              "y":231},
            "size":{
              "width":145,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da20d43a557a47d09ca5c5fe4b9cd5ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":779,
                  "y":231},
                "size":{
                  "width":145,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3445034d7fe540c2b9d4a2921b008f46":{
      "scriptId":"u0"},
    "a0c03c3551e5480bb7de84813960230b":{
      "scriptId":"u1"},
    "2dad0fa5cd7a4db9af54064adcb6066e":{
      "scriptId":"u2"},
    "f3256b27a2e048b1bd9090c192d00fc0":{
      "scriptId":"u3"},
    "2281ff835657468db54fcc96d76185f6":{
      "scriptId":"u4"},
    "e90e3c401b474156bd15c2b69491a906":{
      "scriptId":"u5"},
    "afe00966b6194efa8e5a3b46506a2563":{
      "scriptId":"u6"},
    "45994ea6e5c34ceb8a0b3fad1ef74a33":{
      "scriptId":"u7"},
    "abf6060e7abd4bbc80b7bcf847eeb77e":{
      "scriptId":"u8"},
    "a7604ddec41f40168bcc9e14eab011b4":{
      "scriptId":"u9"},
    "f2830415053a4e40b0455932330c2c95":{
      "scriptId":"u10"},
    "d5164a414a264a6382d34e0a7db853ed":{
      "scriptId":"u11"},
    "7082f7e7e0f54699bced66c091bf8e71":{
      "scriptId":"u12"},
    "e5351188b5fa4eb994473431d05983e5":{
      "scriptId":"u13"},
    "b401036dcb524e35ae48066d8569ccb6":{
      "scriptId":"u14"},
    "289bcad908034721b64c74c52f6188eb":{
      "scriptId":"u15"},
    "bf0e1302308f4b56b010d5c5256a7db2":{
      "scriptId":"u16"},
    "62b0e7afa8444a9ea4f12ee89847c1e1":{
      "scriptId":"u17"},
    "5f82e6d5d77f464c9174b4c9cee5fb19":{
      "scriptId":"u18"},
    "b07345578f2c464d9d01720d94d56446":{
      "scriptId":"u19"},
    "ca9d58f854ca4bb2b005aff4f85c26ae":{
      "scriptId":"u20"},
    "fafb0ba09ebf43b39f940f178c074ac4":{
      "scriptId":"u21"},
    "dce48b396b134ad295f1442fc244e234":{
      "scriptId":"u22"},
    "f7de9c4963a549f787cc3ca5375d19dd":{
      "scriptId":"u23"},
    "da20d43a557a47d09ca5c5fe4b9cd5ae":{
      "scriptId":"u24"}}});