$axure.loadCurrentPage({
  "url":"list--loading.html",
  "generationDate":new Date(1403514131276.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a6503ff1c5e84a0dad7ecedb5188df5e",
    "type":"Axure:Page",
    "name":"list--loading",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ee1c4439117a420db721880464c4f0d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":14,
              "y":20},
            "size":{
              "width":320,
              "height":480},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cc3e742e56d43a48d20d9aac33d0556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":14,
                  "y":20},
                "size":{
                  "width":320,
                  "height":480},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list--loading/u0.png"}},
{
          "id":"79ddaddd8b904323a69c3a221a3a7d9b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":14,
              "y":20},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2df950d991d34db281642117f7744e17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":14,
                  "y":20},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list--loading/u2.png"}},
{
          "id":"59b630f9dda448ec819dc1f86ab3647d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "paddingTop":"5",
            "paddingBottom":"5",
            "location":{
              "x":14,
              "y":60},
            "size":{
              "width":104,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a1b84c0d7754c4aafca8984c0011410",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "paddingTop":"5",
                "paddingBottom":"5",
                "location":{
                  "x":14,
                  "y":60},
                "size":{
                  "width":104,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list--loading/u4.png"}},
{
          "id":"a12ba057264f41349eb2252dd02c974e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":44,
              "y":26},
            "size":{
              "width":29,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97893f0c141649e29aff7819c95e1cd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":44,
                  "y":26},
                "size":{
                  "width":29,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list--loading/u6.png"}},
{
          "id":"46a0ac74e7e24b10ad8746502b792f92",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":96},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/list--loading/u8_line.png"}},
{
          "id":"7b26c7d3efcf462ba649303879e689fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":83,
              "y":32},
            "size":{
              "width":200,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c19b38c78b8841b1a742fc861d32f39f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":83,
                  "y":32},
                "size":{
                  "width":200,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list--loading/u9.png"}},
{
          "id":"c05d2b15a1b14cccb7a7bcbbfb135edb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "paddingTop":"5",
            "paddingBottom":"5",
            "location":{
              "x":118,
              "y":60},
            "size":{
              "width":113,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6817780613c746eb8f40060a9bfed96e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "paddingTop":"5",
                "paddingBottom":"5",
                "location":{
                  "x":118,
                  "y":60},
                "size":{
                  "width":113,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list--loading/u11.png"}},
{
          "id":"f47699c0472448bd9996e7e8085ac8ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "paddingTop":"5",
            "paddingBottom":"5",
            "location":{
              "x":231,
              "y":60},
            "size":{
              "width":103,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ef49415a98f42c9a3f95a0c67b857a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "paddingTop":"5",
                "paddingBottom":"5",
                "location":{
                  "x":231,
                  "y":60},
                "size":{
                  "width":103,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list--loading/u13.png"}},
{
          "id":"79ce3775fd2e40e482c3a5cb093e4b3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":102},
            "size":{
              "width":320,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0622236097fe48f38aecd8d020da9ee1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":102},
                "size":{
                  "width":320,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list--loading/u15.png"}},
{
          "id":"d1d39ea326fb4cd2959b76ac8e0d88a2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":108},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69269cb3b7734e798c658d305f64dda1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":109,
                  "y":108},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list--loading/u17.jpg"}},
{
          "id":"63a2473ce68342c9bc4d7ba45dcf950c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Medium', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":148,
              "y":119},
            "size":{
              "width":71,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a5dbf6336a34cefb5d5f157c0aefa40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Medium', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":148,
                  "y":119},
                "size":{
                  "width":71,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list--loading/u19.png"}},
{
          "id":"b83af825fdf84b9aae0993aab1ab4770",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":106,
              "y":202},
            "size":{
              "width":155,
              "height":168}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90a138abec774425a7ed3d3b6df747f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":106,
                  "y":202},
                "size":{
                  "width":155,
                  "height":168}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c46024d61ece4a8c9966983b886597ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":364,
              "y":449},
            "size":{
              "width":320,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a7b11667f8e4bae8f3cae9c0c7c601c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":364,
                  "y":449},
                "size":{
                  "width":320,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list--loading/u15.png"}},
{
          "id":"12bfd18a9b5a4401aa36b9c3072844fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":459,
              "y":455},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4b2ee7640d6407b97fc1f1ad6a9cf8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":459,
                  "y":455},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list--loading/u17.jpg"}},
{
          "id":"0fc60aa9f0b045038f6f09cf2106af4b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Medium', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":498,
              "y":467},
            "size":{
              "width":71,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2047e9df49041bbaf85169be5513241",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Medium', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":498,
                  "y":467},
                "size":{
                  "width":71,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list--loading/u19.png"}},
{
          "id":"de73b901e1bb48209983cc6aa07bafc5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":352,
              "y":58},
            "size":{
              "width":332,
              "height":381}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da7e474ed3944890aa9efd251cbfb4de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":352,
                  "y":58},
                "size":{
                  "width":332,
                  "height":381}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list--loading/u29.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "ee1c4439117a420db721880464c4f0d4":{
      "scriptId":"u0"},
    "8cc3e742e56d43a48d20d9aac33d0556":{
      "scriptId":"u1"},
    "79ddaddd8b904323a69c3a221a3a7d9b":{
      "scriptId":"u2"},
    "2df950d991d34db281642117f7744e17":{
      "scriptId":"u3"},
    "59b630f9dda448ec819dc1f86ab3647d":{
      "scriptId":"u4"},
    "7a1b84c0d7754c4aafca8984c0011410":{
      "scriptId":"u5"},
    "a12ba057264f41349eb2252dd02c974e":{
      "scriptId":"u6"},
    "97893f0c141649e29aff7819c95e1cd6":{
      "scriptId":"u7"},
    "46a0ac74e7e24b10ad8746502b792f92":{
      "scriptId":"u8"},
    "7b26c7d3efcf462ba649303879e689fe":{
      "scriptId":"u9"},
    "c19b38c78b8841b1a742fc861d32f39f":{
      "scriptId":"u10"},
    "c05d2b15a1b14cccb7a7bcbbfb135edb":{
      "scriptId":"u11"},
    "6817780613c746eb8f40060a9bfed96e":{
      "scriptId":"u12"},
    "f47699c0472448bd9996e7e8085ac8ab":{
      "scriptId":"u13"},
    "7ef49415a98f42c9a3f95a0c67b857a5":{
      "scriptId":"u14"},
    "79ce3775fd2e40e482c3a5cb093e4b3b":{
      "scriptId":"u15"},
    "0622236097fe48f38aecd8d020da9ee1":{
      "scriptId":"u16"},
    "d1d39ea326fb4cd2959b76ac8e0d88a2":{
      "scriptId":"u17"},
    "69269cb3b7734e798c658d305f64dda1":{
      "scriptId":"u18"},
    "63a2473ce68342c9bc4d7ba45dcf950c":{
      "scriptId":"u19"},
    "1a5dbf6336a34cefb5d5f157c0aefa40":{
      "scriptId":"u20"},
    "b83af825fdf84b9aae0993aab1ab4770":{
      "scriptId":"u21"},
    "90a138abec774425a7ed3d3b6df747f1":{
      "scriptId":"u22"},
    "c46024d61ece4a8c9966983b886597ae":{
      "scriptId":"u23"},
    "7a7b11667f8e4bae8f3cae9c0c7c601c":{
      "scriptId":"u24"},
    "12bfd18a9b5a4401aa36b9c3072844fc":{
      "scriptId":"u25"},
    "f4b2ee7640d6407b97fc1f1ad6a9cf8a":{
      "scriptId":"u26"},
    "0fc60aa9f0b045038f6f09cf2106af4b":{
      "scriptId":"u27"},
    "f2047e9df49041bbaf85169be5513241":{
      "scriptId":"u28"},
    "de73b901e1bb48209983cc6aa07bafc5":{
      "scriptId":"u29"},
    "da7e474ed3944890aa9efd251cbfb4de":{
      "scriptId":"u30"}}});