$axure.loadCurrentPage({
  "url":"主流程_1.html",
  "generationDate":new Date(1401876151771.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bb747c1bc22b482da6463fab89ba7d2e",
    "type":"Axure:Page",
    "name":"主流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2fac3301669c46cbba02d3a3f027e002",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":8},
            "size":{
              "width":64,
              "height":64},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29d6ee594c19408695a6234e8b1962ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":8},
                "size":{
                  "width":64,
                  "height":64},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主流程/u0.png"}},
{
          "id":"a235fd67d7db45f3ab821b555bdeed01",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":240},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71d55cf8825b48bba6d5e4db2725cd3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":240},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"51660d255bbe4dac908f42e5b1dc8318",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":310},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f886a35d695744a3b11abc4c30eaebb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":310},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主流程/u2.png"}},
{
          "id":"ed4d2ad0b19e4cc5995fde08b307748d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":430},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53168b5ed11c45d1b3a31f583c29cebc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":430},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主流程/u34.png"}},
{
          "id":"5250e3bb731140bbbccdd1ccf23edc37",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":430},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb138c6e9e8d403fa8fe6e257a9b696b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":430},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主流程/u34.png"}},
{
          "id":"ee3cb0bb4d58422a9ee81c665bf9b763",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":340}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b10f0d17c646424d92ee0aa39fa32927",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":340}},
              "adaptiveStyles":{
}}]},
{
          "id":"f48a6a56cc8e4bbeb532fa0b30c65c83",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":340}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9a28655f24d4085ae79e8dddcb2e1fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":340}},
              "adaptiveStyles":{
}}]},
{
          "id":"fd32685151d64f3e9210b2f269f82d18",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":180},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2f164647e4e4d1c8460c285725739f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":180},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主流程/u2.png"}},
{
          "id":"21b3d62cea60414bbecd8efb5b886eb7",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":80},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2abf7a0b248452a82116c69f4e8a4dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":80},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "2fac3301669c46cbba02d3a3f027e002":{
      "scriptId":"u0"},
    "29d6ee594c19408695a6234e8b1962ee":{
      "scriptId":"u1"},
    "a235fd67d7db45f3ab821b555bdeed01":{
      "scriptId":"u2"},
    "71d55cf8825b48bba6d5e4db2725cd3d":{
      "scriptId":"u3"},
    "51660d255bbe4dac908f42e5b1dc8318":{
      "scriptId":"u4"},
    "f886a35d695744a3b11abc4c30eaebb2":{
      "scriptId":"u5"},
    "ed4d2ad0b19e4cc5995fde08b307748d":{
      "scriptId":"u6"},
    "53168b5ed11c45d1b3a31f583c29cebc":{
      "scriptId":"u7"},
    "5250e3bb731140bbbccdd1ccf23edc37":{
      "scriptId":"u8"},
    "bb138c6e9e8d403fa8fe6e257a9b696b":{
      "scriptId":"u9"},
    "ee3cb0bb4d58422a9ee81c665bf9b763":{
      "scriptId":"u10"},
    "b10f0d17c646424d92ee0aa39fa32927":{
      "scriptId":"u11"},
    "f48a6a56cc8e4bbeb532fa0b30c65c83":{
      "scriptId":"u12"},
    "c9a28655f24d4085ae79e8dddcb2e1fd":{
      "scriptId":"u13"},
    "fd32685151d64f3e9210b2f269f82d18":{
      "scriptId":"u14"},
    "a2f164647e4e4d1c8460c285725739f8":{
      "scriptId":"u15"},
    "21b3d62cea60414bbecd8efb5b886eb7":{
      "scriptId":"u16"},
    "e2abf7a0b248452a82116c69f4e8a4dd":{
      "scriptId":"u17"}}});