$axure.loadCurrentPage({
  "url":"我的会员.html",
  "generationDate":new Date(1404457232916.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"23ea6bd19542471f87c6a5bb87104f07",
    "type":"Axure:Page",
    "name":"我的会员",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"85c27868fc2b432a8c5788c5320a243b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":480},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c2174dc43c3460993d56191ebe0f383",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":480},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u0.png"}},
{
          "id":"5e05f7ac5ccc4969bc2377acc2eef145",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "horizontalAlignment":"left",
            "paddingTop":"8",
            "paddingBottom":"0",
            "location":{
              "x":20,
              "y":110},
            "size":{
              "width":300,
              "height":290},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeeb51b2adfc40678185d9f2cd3bc0a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "horizontalAlignment":"left",
                "paddingTop":"8",
                "paddingBottom":"0",
                "location":{
                  "x":20,
                  "y":110},
                "size":{
                  "width":300,
                  "height":290},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的会员/u2.png"}},
{
          "id":"a20b67c0763e4ebb9664813fa7713739",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":30,
              "y":146},
            "size":{
              "width":280,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c504349a24424a5a940164e3a325ff3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":30,
                  "y":146},
                "size":{
                  "width":280,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的会员/u4.png"}},
{
          "id":"9f38af4ad06648689943a7ecfef4ad00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":57,
              "y":450},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79a169dba11e41eabbc477348670aac2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":57,
                  "y":450},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u2.png"}},
{
          "id":"9d980ee789e34f5098128a4186420716",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":148,
              "y":450},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bf2fbf740cb41ce901e78150d05b8aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":148,
                  "y":450},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u2.png"}},
{
          "id":"ddd7e10aa54e4b07af9d30df59467ebe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":238,
              "y":450},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6577667c6fbb44b4b27989a1fa33fabc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":238,
                  "y":450},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u2.png"}},
{
          "id":"c1096ff2915b44cb959544b7a5d6af8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1111e00f190474a9d730d48e0a44ab1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u8.png"}},
{
          "id":"eba55cbae4b54c22aa03b676aec8944c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":40,
              "y":16},
            "size":{
              "width":29,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a27d6ec048248238321ed7ad9c11993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":40,
                  "y":16},
                "size":{
                  "width":29,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03f72aecf76546be8056195cc009291f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":79,
              "y":22},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5ed03b32a504776b23f1cc1e809b74b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":79,
                  "y":22},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88bad3f2781142dcac8e24dd2d4822c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":450},
            "size":{
              "width":48,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bd1f00642ca4d78aa54adf428f0e674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":450},
                "size":{
                  "width":48,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u14.png"}},
{
          "id":"831be35121a54b5e985b2dbb832fd24f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":238,
              "y":410},
            "size":{
              "width":93,
              "height":40},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db93d3bdd0674177bd68772e23f17584",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":238,
                  "y":410},
                "size":{
                  "width":93,
                  "height":40},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__home/u30.png"}},
{
          "id":"092d7d118623403aba215723e88b3ac8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Medium', 'Heiti SC'",
            "fontSize":"24px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCC6666},
            "location":{
              "x":30,
              "y":146},
            "size":{
              "width":119,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59c17e6baf0a44e196cb4b0dee6d3121",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Medium', 'Heiti SC'",
                "fontSize":"24px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC6666},
                "location":{
                  "x":30,
                  "y":146},
                "size":{
                  "width":119,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的会员/u22.png"}},
{
          "id":"bc9719c6e0914c2cb4e4b47ac936ae12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Medium', 'Heiti SC'",
            "fontSize":"24px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":170,
              "y":201},
            "size":{
              "width":109,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"241de2e56ba24f009ee5547600eedb23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Medium', 'Heiti SC'",
                "fontSize":"24px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":170,
                  "y":201},
                "size":{
                  "width":109,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75c67126711040a5901332b2faca25d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":30,
              "y":360},
            "size":{
              "width":162,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a1c5de3858043b2bf1724bc6813f394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":30,
                  "y":360},
                "size":{
                  "width":162,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的会员/u26.png"}},
{
          "id":"3b0c1fa958844968b148dec5ac151348",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":30,
              "y":120},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4875fd3abef043349b3ed374d9515a8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":30,
                  "y":120},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea3f1fd0ba3d46aba6316b60ff26fd42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":30,
              "y":310},
            "size":{
              "width":280,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38fc5515cc0f40939728a624289eb2d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":30,
                  "y":310},
                "size":{
                  "width":280,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的会员/u30.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "85c27868fc2b432a8c5788c5320a243b":{
      "scriptId":"u0"},
    "3c2174dc43c3460993d56191ebe0f383":{
      "scriptId":"u1"},
    "5e05f7ac5ccc4969bc2377acc2eef145":{
      "scriptId":"u2"},
    "eeeb51b2adfc40678185d9f2cd3bc0a0":{
      "scriptId":"u3"},
    "a20b67c0763e4ebb9664813fa7713739":{
      "scriptId":"u4"},
    "c504349a24424a5a940164e3a325ff3c":{
      "scriptId":"u5"},
    "9f38af4ad06648689943a7ecfef4ad00":{
      "scriptId":"u6"},
    "79a169dba11e41eabbc477348670aac2":{
      "scriptId":"u7"},
    "9d980ee789e34f5098128a4186420716":{
      "scriptId":"u8"},
    "0bf2fbf740cb41ce901e78150d05b8aa":{
      "scriptId":"u9"},
    "ddd7e10aa54e4b07af9d30df59467ebe":{
      "scriptId":"u10"},
    "6577667c6fbb44b4b27989a1fa33fabc":{
      "scriptId":"u11"},
    "c1096ff2915b44cb959544b7a5d6af8a":{
      "scriptId":"u12"},
    "c1111e00f190474a9d730d48e0a44ab1":{
      "scriptId":"u13"},
    "eba55cbae4b54c22aa03b676aec8944c":{
      "scriptId":"u14"},
    "2a27d6ec048248238321ed7ad9c11993":{
      "scriptId":"u15"},
    "03f72aecf76546be8056195cc009291f":{
      "scriptId":"u16"},
    "f5ed03b32a504776b23f1cc1e809b74b":{
      "scriptId":"u17"},
    "88bad3f2781142dcac8e24dd2d4822c3":{
      "scriptId":"u18"},
    "5bd1f00642ca4d78aa54adf428f0e674":{
      "scriptId":"u19"},
    "831be35121a54b5e985b2dbb832fd24f":{
      "scriptId":"u20"},
    "db93d3bdd0674177bd68772e23f17584":{
      "scriptId":"u21"},
    "092d7d118623403aba215723e88b3ac8":{
      "scriptId":"u22"},
    "59c17e6baf0a44e196cb4b0dee6d3121":{
      "scriptId":"u23"},
    "bc9719c6e0914c2cb4e4b47ac936ae12":{
      "scriptId":"u24"},
    "241de2e56ba24f009ee5547600eedb23":{
      "scriptId":"u25"},
    "75c67126711040a5901332b2faca25d5":{
      "scriptId":"u26"},
    "2a1c5de3858043b2bf1724bc6813f394":{
      "scriptId":"u27"},
    "3b0c1fa958844968b148dec5ac151348":{
      "scriptId":"u28"},
    "4875fd3abef043349b3ed374d9515a8d":{
      "scriptId":"u29"},
    "ea3f1fd0ba3d46aba6316b60ff26fd42":{
      "scriptId":"u30"},
    "38fc5515cc0f40939728a624289eb2d3":{
      "scriptId":"u31"}}});