$axure.loadCurrentPage({
  "url":"新建广告.html",
  "generationDate":new Date(1404797672870.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ae071c892b9f42e49e4dccacb88389d6",
    "type":"Axure:Page",
    "name":"新建广告",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"325b029d9564434dbd233bc9377d07df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":120,
              "y":152},
            "size":{
              "width":200,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87c3a29cd18847e68ad8ecb229f78c1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":120,
                  "y":152},
                "size":{
                  "width":200,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新建广告/u0.png"}},
{
          "id":"4a7d52ed1fb14686ad05913533b6981c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":120,
              "y":395},
            "size":{
              "width":500,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c772f98e5d954c66a86eb20b34c49a70",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":90},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feabe65092a046c994f4819fd4eb42fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":90},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"281e99a7fe7440d6b5336d4166bc3a85",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":90},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf81fe59f4934cc1825b4fafa5128c24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":90},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"09d6990d882f437dadae21b6e8abccbd",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":90},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"762312cd39f14abdb63627faed473d2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":90},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a4b3bdb9bcff4c88bdee7fb5c235baa4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":51},
            "size":{
              "width":900,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机版wifi营销广告管理/u0_line.png"}},
{
          "id":"54eda24d61a246648b305b828f3e5998",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":31},
            "size":{
              "width":240,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9b8194fb4a345489d8ce2293fc09c6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":31},
                "size":{
                  "width":240,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8452fb63dca844158ff2e61bd4de97fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":398},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4389a47bca6d4c09800d14b33722bb97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":398},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f72b2e5706df478c889dd149616ca8ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":120,
              "y":430},
            "size":{
              "width":400,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87364bdc782349628d942ecf93a3c636",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":120,
                  "y":430},
                "size":{
                  "width":400,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d038fe6f4ec41a99009bc5b610b8865",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":470},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"965f6b90480d4145a43fe6ad53c9ca24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":120,
              "y":362},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcfb3aeb9d8d4045b7a234da1c78730b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":120,
                  "y":362},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e532f15703ce466c9d8820f98f9b8c8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":970,
              "y":320},
            "size":{
              "width":300,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c3f3973f66246c59d2236b663a8ab7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":970,
                  "y":320},
                "size":{
                  "width":300,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"477e875a556e4fd9bcfebf4f7b505b70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":90},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4df040303e374b228a5d0d3dbfb8826e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":90},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59dd0718d75e482eb5f71cac0ef06ca5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":152},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db312264dccc4eff9418b4f9ff777e79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":152},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b3e43a6e60446adab9885fd5d7bd6c1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":367},
            "size":{
              "width":680,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3333FF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/新建广告/u25_end.png",
            "line~":"images/新建广告/u25_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "325b029d9564434dbd233bc9377d07df":{
      "scriptId":"u0"},
    "87c3a29cd18847e68ad8ecb229f78c1d":{
      "scriptId":"u1"},
    "4a7d52ed1fb14686ad05913533b6981c":{
      "scriptId":"u2"},
    "c772f98e5d954c66a86eb20b34c49a70":{
      "scriptId":"u3"},
    "feabe65092a046c994f4819fd4eb42fd":{
      "scriptId":"u4"},
    "281e99a7fe7440d6b5336d4166bc3a85":{
      "scriptId":"u5"},
    "cf81fe59f4934cc1825b4fafa5128c24":{
      "scriptId":"u6"},
    "09d6990d882f437dadae21b6e8abccbd":{
      "scriptId":"u7"},
    "762312cd39f14abdb63627faed473d2d":{
      "scriptId":"u8"},
    "a4b3bdb9bcff4c88bdee7fb5c235baa4":{
      "scriptId":"u9"},
    "54eda24d61a246648b305b828f3e5998":{
      "scriptId":"u10"},
    "d9b8194fb4a345489d8ce2293fc09c6d":{
      "scriptId":"u11"},
    "8452fb63dca844158ff2e61bd4de97fc":{
      "scriptId":"u12"},
    "4389a47bca6d4c09800d14b33722bb97":{
      "scriptId":"u13"},
    "f72b2e5706df478c889dd149616ca8ab":{
      "scriptId":"u14"},
    "87364bdc782349628d942ecf93a3c636":{
      "scriptId":"u15"},
    "1d038fe6f4ec41a99009bc5b610b8865":{
      "scriptId":"u16"},
    "965f6b90480d4145a43fe6ad53c9ca24":{
      "scriptId":"u17"},
    "dcfb3aeb9d8d4045b7a234da1c78730b":{
      "scriptId":"u18"},
    "e532f15703ce466c9d8820f98f9b8c8a":{
      "scriptId":"u19"},
    "8c3f3973f66246c59d2236b663a8ab7f":{
      "scriptId":"u20"},
    "477e875a556e4fd9bcfebf4f7b505b70":{
      "scriptId":"u21"},
    "4df040303e374b228a5d0d3dbfb8826e":{
      "scriptId":"u22"},
    "59dd0718d75e482eb5f71cac0ef06ca5":{
      "scriptId":"u23"},
    "db312264dccc4eff9418b4f9ff777e79":{
      "scriptId":"u24"},
    "5b3e43a6e60446adab9885fd5d7bd6c1":{
      "scriptId":"u25"}}});