$axure.loadCurrentPage({
  "url":"关于人信汇.html",
  "generationDate":new Date(1404457228764.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3c9ecb9d5ac747e1b79fa0cfc075463f",
    "type":"Axure:Page",
    "name":"关于人信汇",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3ae19a6f64214774bf28802aa776d331",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":920},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07982d4391f54b1ea5e56b387fc74d7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":920},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于人信汇/u0.png"}},
{
          "id":"4526284428014e79abe264fb5af9ee6a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d9788397ded44f484ca747e0443b0d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u4.png"}},
{
          "id":"1cfd9663d2cd42faabe975a56cad0cff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":78,
              "y":22},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cce34904c3f54137b18707dab276f7c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":78,
                  "y":22},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4abcc965d32c4667b503e09ef56605ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":40,
              "y":16},
            "size":{
              "width":29,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8625fc94be1e4f0c85ac0489d177f75f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":40,
                  "y":16},
                "size":{
                  "width":29,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注引导/u6.png"}},
{
          "id":"507e91c4d2a547fe9fb8a730aa1023b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":55},
            "size":{
              "width":300,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc174b2a92d64d2d8d7fc084416e66c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":55},
                "size":{
                  "width":300,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce6e78259e38427e9385291350ad5a47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":20,
              "y":110},
            "size":{
              "width":298,
              "height":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56e3122e373443bd8c01e8bb8bdf2397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":20,
                  "y":110},
                "size":{
                  "width":298,
                  "height":140},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于人信汇/u10.png"}},
{
          "id":"8246b1e8c47c426996b81b12f1d5218e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":30,
              "y":260},
            "size":{
              "width":10,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bccdc7193c434a5491a5d85632842cb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":30,
                  "y":260},
                "size":{
                  "width":10,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于人信汇/u12.png"}},
{
          "id":"4a795fc88b904a51ba4588bca4015ccf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":30,
              "y":282},
            "size":{
              "width":14,
              "height":14},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f3313aedf4944d4b81230b90e87816a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":30,
                  "y":282},
                "size":{
                  "width":14,
                  "height":14},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于人信汇/u14.png"}},
{
          "id":"d269b04a378e40cbb3e79ecee07779cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":50,
              "y":260},
            "size":{
              "width":200,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f434acf5de7e4cf287c883c6e742eb53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":260},
                "size":{
                  "width":200,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"063e47c61f2b40028410cec07158f841",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":50,
              "y":286},
            "size":{
              "width":200,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3513f042b3d34bb385ede5a4efd6e06f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":286},
                "size":{
                  "width":200,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4d295e89a784fefa450f71341e11957",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FontAwesome'",
            "fontSize":"14px",
            "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
            "location":{
              "x":30,
              "y":308},
            "size":{
              "width":15,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55530200afb64d10aa6282afe005e321",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FontAwesome'",
                "fontSize":"14px",
                "baseStyle":"f2da49a81e4f49608c19f6ab785428ce",
                "location":{
                  "x":30,
                  "y":308},
                "size":{
                  "width":15,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f39846e8c23b49839b76f027045cf268",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":50,
              "y":308},
            "size":{
              "width":200,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfbced3a46884019ad560c169e6eb84a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":308},
                "size":{
                  "width":200,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec6214f39955495f97a8291a83002aa6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":340},
            "size":{
              "width":270,
              "height":547}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c985280a3654d80974f7725c3b03365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":340},
                "size":{
                  "width":270,
                  "height":547}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7de50e77f55485fbfe2bb9336acf92e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":95},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/关于人信汇/u26_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3ae19a6f64214774bf28802aa776d331":{
      "scriptId":"u0"},
    "07982d4391f54b1ea5e56b387fc74d7f":{
      "scriptId":"u1"},
    "4526284428014e79abe264fb5af9ee6a":{
      "scriptId":"u2"},
    "5d9788397ded44f484ca747e0443b0d7":{
      "scriptId":"u3"},
    "1cfd9663d2cd42faabe975a56cad0cff":{
      "scriptId":"u4"},
    "cce34904c3f54137b18707dab276f7c8":{
      "scriptId":"u5"},
    "4abcc965d32c4667b503e09ef56605ce":{
      "scriptId":"u6"},
    "8625fc94be1e4f0c85ac0489d177f75f":{
      "scriptId":"u7"},
    "507e91c4d2a547fe9fb8a730aa1023b0":{
      "scriptId":"u8"},
    "bc174b2a92d64d2d8d7fc084416e66c3":{
      "scriptId":"u9"},
    "ce6e78259e38427e9385291350ad5a47":{
      "scriptId":"u10"},
    "56e3122e373443bd8c01e8bb8bdf2397":{
      "scriptId":"u11"},
    "8246b1e8c47c426996b81b12f1d5218e":{
      "scriptId":"u12"},
    "bccdc7193c434a5491a5d85632842cb9":{
      "scriptId":"u13"},
    "4a795fc88b904a51ba4588bca4015ccf":{
      "scriptId":"u14"},
    "5f3313aedf4944d4b81230b90e87816a":{
      "scriptId":"u15"},
    "d269b04a378e40cbb3e79ecee07779cc":{
      "scriptId":"u16"},
    "f434acf5de7e4cf287c883c6e742eb53":{
      "scriptId":"u17"},
    "063e47c61f2b40028410cec07158f841":{
      "scriptId":"u18"},
    "3513f042b3d34bb385ede5a4efd6e06f":{
      "scriptId":"u19"},
    "b4d295e89a784fefa450f71341e11957":{
      "scriptId":"u20"},
    "55530200afb64d10aa6282afe005e321":{
      "scriptId":"u21"},
    "f39846e8c23b49839b76f027045cf268":{
      "scriptId":"u22"},
    "dfbced3a46884019ad560c169e6eb84a":{
      "scriptId":"u23"},
    "ec6214f39955495f97a8291a83002aa6":{
      "scriptId":"u24"},
    "4c985280a3654d80974f7725c3b03365":{
      "scriptId":"u25"},
    "e7de50e77f55485fbfe2bb9336acf92e":{
      "scriptId":"u26"}}});